codenvy/codenvy

- dashboard/src/app/factories/load-factory/load-factory.controller.js
- dashboard/src/app/factories/load-factory/load-factory.html
> fix logs output on factory loading

- dashboard/src/app/factories/list-factories/factory-item/factory-item.html
- dashboard/src/components/api/codenvy-factory.factory.js
> CODENVY-318: remove codenvy analytic info from factory details

- pom.xml
> remove codenvy-depmgt, move external dependency management to codenvy

- assembly/onpremises-ide-compiling-war-ide/pom.xml
> Fix prop name whisch used on about window

- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-backup-restore-single-node-with-codenvy4.sh
> Fix test of backup and restore of Codenvy 4.x AIO

- dashboard/src/app/factories/factory-details/configuration-tab/factory-configuration/factory-configuration.controller.js
- dashboard/src/app/factories/factory-details/configuration-tab/factory-configuration/factory-configuration.html
- dashboard/src/app/factories/load-factory/load-factory.controller.js
> fix factory configuration widget

- dashboard/src/app/admin/onprem-administration/installation/configuration/configuration.controller.js
- dashboard/src/app/admin/onprem-administration/installation/configuration/configuration.html
- dashboard/src/app/admin/onprem-administration/installation/configuration/configuration.styl
@ashumilova WDYT?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codenvy/codenvy/35)
> CODENVY-286: fix styles for config widget in administration section

- cdec/installation-manager-cli-assembly/pom.xml
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/InstallManagerArtifact.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestInstallManagerArtifact.java
> CODENVY-233: fix error of executing IM CLI command after update

- core/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManager.java
- core/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManagerTest.java
- platform-api-client-java/core/src/main/java/com/codenvy/client/core/DefaultWorkspaceClient.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codenvy/codenvy/32)
> CHE-716 getting workspaces via complex key

- dashboard/src/app/admin/user-management/add-user/add-user.html
> CODENVY-299: improve fields title for add user widget

- assembly/onpremises-ide-packaging-war-ext-server/pom.xml
- assembly/onpremises-ide-packaging-war-ext-server/src/main/java/com/codenvy/ext/java/server/MachineModule.java
- assembly/onpremises-ide-packaging-war-ext-server/src/main/java/com/codenvy/ext/java/server/MachineServletModule.java
- assembly/onpremises-ide-packaging-war-ext-server/src/main/webapp/WEB-INF/classes/codenvy/che-machine-configuration.properties
- assembly/onpremises-ide-packaging-war-platform-api/pom.xml
- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
- assembly/onpremises-ide-packaging-war-platform-api/src/main/webapp/WEB-INF/classes/codenvy/codenvy-api-configuration.properties
- core/codenvy-hosted-workspace-activity-agent/pom.xml
- core/codenvy-hosted-workspace-activity-agent/src/main/java/com/codenvy/workspace/LastAccessTimeFilter.java
- core/codenvy-hosted-workspace-activity-agent/src/main/java/com/codenvy/workspace/WorkspaceActivityNotifier.java
- core/codenvy-hosted-workspace-activity-agent/src/main/java/com/codenvy/workspace/websocket/WorkspaceWebsocketConnectionListener.java
- core/codenvy-hosted-workspace-activity-agent/src/main/java/com/codenvy/workspace/websocket/WorkspaceWebsocketMessageReceiver.java
- core/codenvy-hosted-workspace-activity/pom.xml
- core/codenvy-hosted-workspace-activity/src/main/java/com/codenvy/activity/server/WorkspaceActivityManager.java
- core/codenvy-hosted-workspace-activity/src/main/java/com/codenvy/activity/server/WorkspaceActivityService.java
- core/codenvy-hosted-workspace-activity/src/main/java/com/codenvy/activity/server/inject/WorkspaceActivityModule.java
- core/codenvy-hosted-workspace-activity/src/test/java/com/codenvy/activity/server/WorkspaceActivityManagerTest.java
- core/pom.xml
- pom.xml
@skabashnyuk @evoevodin @sleshchenko @garagatyi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codenvy/codenvy/23)
> CODENVY-224: Enable workspace shutdown wait timeout

- dashboard/src/app/admin/onprem-administration/software/software.html
> fix info message for download widget

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.0.1/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.1.0-RC1-SNAPSHOT/codenvy-single-server.properties
> Add properties of Codenvy on-pren 4.0.1 and 4.1.0-SNAPSHOT

- cdec/installation-manager-core/pom.xml
@riuvshin: please, accept this request.
> Restore generation of BuildInfo.properties file by default

- dashboard/src/app/onprem/license-nag-message-management/nag-message.service.js
- dashboard/src/app/onprem/license-nag-message-management/nag-message.styl
> fix style for license message

- dashboard/src/app/onprem/license-nag-message-management/nag-message.styl
> CODENVY-335: fix style for license message

- pom.xml
> Update selenium version

- pom.xml
Add missing <repositories> section
> add repomanagement

- dashboard/src/app/navbar/codenvy-navbar.html
In phase 1 codenvy classic url should point to codenvy.com
@ashumilova @benoitf @TylerJewell
> CODENVY-141: fix codenvy classic url

- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
> CODENVY-235: check write access to install directory; code cleanup

- dashboard/src/app/factories/load-factory/load-factory.html
- dashboard/src/app/factories/load-factory/load-factory.styl
> rework logs output

- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/helper/NodeManagerHelperCodenvy4Impl.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/helper/TestNodeManagerHelperCodenvy4Impl.java
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-add-remove-codenvy-nodes-with-codenvy4.sh
> CODENVY-236: disconnect removing node from the puppet master

- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-add-remove-codenvy-nodes-with-codenvy4.sh
> CODENVY-236: fix test-add-remove-codenvy-nodes-with-codenvy4

- core/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManager.java
- core/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManagerTest.java
Allowed to dissable limits, such as:
```
limits.user.workspaces.count
limits.user.workspaces.ram
limits.workspace.env.ram
```
by setting value to `-1`.
@skabashnyuk, @akorneta please review
> CODENVY-326: Allow to dissable limits

- core/codenvy-hosted-workspace-activity/pom.xml
- core/codenvy-hosted-workspace-activity/src/main/java/com/codenvy/activity/server/WorkspaceActivityManager.java
- core/codenvy-hosted-workspace-activity/src/main/java/com/codenvy/activity/shared/Constants.java
- plugins/plugin-hosted/codenvy-hosted-ext-hosted/pom.xml
- plugins/plugin-hosted/codenvy-hosted-ext-hosted/src/main/java/com/codenvy/ide/hosted/client/HostedLocalizationConstant.java
- plugins/plugin-hosted/codenvy-hosted-ext-hosted/src/main/java/com/codenvy/ide/hosted/client/inject/HostedEnvironmentGinModule.java
- plugins/plugin-hosted/codenvy-hosted-ext-hosted/src/main/java/com/codenvy/ide/hosted/client/workspace/HostedWorkspaceStoppedHandler.java
- plugins/plugin-hosted/codenvy-hosted-ext-hosted/src/main/java/com/codenvy/ide/hosted/client/workspace/WorkspaceNotRunningPresenter.java
- plugins/plugin-hosted/codenvy-hosted-ext-hosted/src/main/java/com/codenvy/ide/hosted/client/workspace/WorkspaceNotRunningView.java
- plugins/plugin-hosted/codenvy-hosted-ext-hosted/src/main/java/com/codenvy/ide/hosted/client/workspace/WorkspaceNotRunningViewImpl.java
- plugins/plugin-hosted/codenvy-hosted-ext-hosted/src/main/java/com/codenvy/ide/hosted/client/workspace/WorkspaceNotRunningViewImpl.ui.xml
- plugins/plugin-hosted/codenvy-hosted-ext-hosted/src/main/resources/com/codenvy/ide/hosted/client/HostedLocalizationConstant.properties
Show special dialog when workspace has been stopped due to inactivity
> CODENVY-334 Handle hosted workspace stop dialogs

- cdec/installation-manager-cli-assembly/pom.xml
- cdec/installation-manager-cli-bundle/src/main/java/com/codenvy/im/cli/command/VersionCommand.java
- cdec/installation-manager-cli-bundle/src/test/java/com/codenvy/im/cli/command/TestVersionCommand.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECArtifactHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECSingleServerHelper.java
> Fix IM CLI messages

- dashboard/src/app/factories/factory-details/factory-details.html
> CHE-793: replace button style to open in IDE

- dashboard/src/app/factories/create-factory/create-factory.controller.js
- dashboard/src/app/factories/create-factory/create-factory.html
- dashboard/src/app/factories/factory-details/information-tab/factory-information/factory-information.html
- dashboard/src/app/factories/list-factories/factory-item/factory-item.html
> CODENVY-273: improvements to handle Factory's pretty name

- dashboard/src/app/factories/create-factory/create-factory.html
> CODENVY-316: update reference to factory documentation in UD

- cdec/installation-manager-core/src/main/java/com/codenvy/im/license/CodenvyLicenseManager.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/StorageManager.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/StorageNotFoundException.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/StorageManagerTest.java
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-add-remove-codenvy-nodes-with-codenvy4.sh
> CODENVY-345: don't create storage in time of reading it

- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/Config.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/ConfigManager.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/TestConfigManager.java
@tolusha: please, review this request. 
There was *ConfigManager.setupProxyProperties(properties)* method added + small refactoring performed.
> CODENVY-124: setup proxy variables in the IM CLI

- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-backup-restore-single-node-with-codenvy4.sh
@tolusha: please, review my request.
> Fix IM integration test of backup-restore codenvy4

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.1.0-RC1-SNAPSHOT/codenvy-single-server.properties
> Add new default properties to Codenvy on-prem 4.1.0

- dashboard/src/app/factories/create-factory/action/factory-action-box.controller.js
- dashboard/src/app/factories/create-factory/action/factory-action-box.directive.js
- dashboard/src/app/factories/create-factory/action/factory-action-box.html
- dashboard/src/app/factories/create-factory/action/factory-action-box.styl
- dashboard/src/app/factories/create-factory/action/factory-action-widget-dialog-add.controller.js
- dashboard/src/app/factories/create-factory/action/factory-action-widget-dialog-add.html
- dashboard/src/app/factories/create-factory/action/factory-action-widget-dialog-edit.controller.js
- dashboard/src/app/factories/create-factory/action/factory-action-widget-dialog-edit.html
- dashboard/src/app/factories/create-factory/action/factory-action-widget.controller.js
- dashboard/src/app/factories/create-factory/action/factory-action-widget.directive.js
- dashboard/src/app/factories/create-factory/action/factory-action-widget.html
- dashboard/src/app/factories/create-factory/command/factory-command-edit.controller.js
- dashboard/src/app/factories/create-factory/command/factory-command-edit.html
- dashboard/src/app/factories/create-factory/command/factory-command.controller.js
- dashboard/src/app/factories/create-factory/command/factory-command.directive.js
- dashboard/src/app/factories/create-factory/command/factory-command.html
- dashboard/src/app/factories/create-factory/command/factory-command.styl
- dashboard/src/app/factories/create-factory/create-factory-config.js
- dashboard/src/app/factories/create-factory/create-factory.controller.js
- dashboard/src/app/factories/create-factory/create-factory.html
- dashboard/src/app/factories/create-factory/create-factory.styl
- dashboard/src/app/factories/create-factory/git/create-factory-git.controller.js
- dashboard/src/app/factories/create-factory/git/create-factory-git.directive.js
- dashboard/src/app/factories/create-factory/git/create-factory-git.html
- dashboard/src/app/factories/factory-details/information-tab/delete-factory/delete-factory.html
- dashboard/src/app/factories/list-factories/list-factories.html
- dashboard/src/app/index.styl
- introduce banner in the list of factories to explain factory
- add new workflow for creating factories.
first, only source is asked (by introducing new items like git or github)
then you have a working factory and you can update name, recipe (based on stack), add commands and IDE actions or keep updating JSON file
> CODENVY-135 open source factories

- cdec/installation-manager-core/src/main/java/com/codenvy/im/utils/HttpTransport.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/utils/TestHttpTransport.java
> CODENVY-313: fix requesting through authenticated proxy

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.1.0/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.2.0-RC1-SNAPSHOT/codenvy-single-server.properties
@riuvshin: please, approve this request as well as set here https://github.com/riuvshin/cdec-bundle/blob/master/pom.xml version 4.1.0 to place Codenvy 4.1.0 bundle into nightly Updater Server for testing before it deploying to production.
> Add default properties for Codenvy 4.1.0, 4.2.0-RC1-SNAPSHOT

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.1.0/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.2.0-RC1-SNAPSHOT/codenvy-single-server.properties
> Encrease default codenvy machine inactivity timeout to 8 hours

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.1.0/codenvy-single-server.properties
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-update-single-node-from-binary-with-codenvy4.sh
- cdec/installation-manager-tests/src/test/java/com/codenvy/im/TestInstallationManagerCliWithCodenvy4.java
@tolusha: please, review this request
> CODENVY-368: add test of update Codenvy 4 on-prem from binary

- dashboard/src/app/factories/create-factory/action/factory-action-widget.directive.js
- dashboard/src/app/factories/create-factory/create-factory.html
- dashboard/src/app/factories/factory-details/configuration-tab/factory-configuration/factory-configuration.html
- dashboard/src/app/factories/factory-details/information-tab/factory-information/factory-information.html
Change-Id: I9079765578ce0e0fd13dbeca93a9af086c1f3409
> Use end HTML markup to avoid some missing tags

- assembly/onpremises-ide-packaging-zip-terminal/pom.xml
- assembly/onpremises-ide-packaging-zip-terminal/src/assembly/assembly.xml
> CHE-930: fix build after changes in terminal

- plugins/plugin-hosted/codenvy-hosted-ext-hosted/src/main/java/com/codenvy/ide/hosted/client/HostedLocalizationConstant.java
- plugins/plugin-hosted/codenvy-hosted-ext-hosted/src/main/java/com/codenvy/ide/hosted/client/inject/CodenvyProductInfoDataProvider.java
- plugins/plugin-hosted/codenvy-hosted-ext-hosted/src/main/resources/com/codenvy/ide/hosted/client/HostedLocalizationConstant.properties
Title contain product name and workspace name if workspace is running or starting
> CODENVY-209: Change title of loading page of IDE.

- core/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManager.java
- core/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManagerTest.java
- dashboard/src/app/factories/list-factories/factory-item/factory-item.html
- dashboard/src/app/factories/load-factory/load-factory.controller.js
- dashboard/src/app/factories/load-factory/load-factory.html
> CODENVY-363: add error messages when user reach the RAM limits

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.1.1/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.2.0-RC1-SNAPSHOT/codenvy-single-server.properties
> Fix java_naming_security_principal property; add properties for 4.1.1

- cdec/installation-manager-cli-bundle/src/test/java/com/codenvy/im/cli/command/TestInstallCommand.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECMultiServerHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECSingleServerHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/ConfigManager.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifact.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/TestConfigManager.java
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.1.1/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.2.0-RC1-SNAPSHOT/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/patches/4.1.0/single_server/update_mongo.js
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-update-single-node-from-binary-with-codenvy4.sh
- cdec/patch-and-upload-codenvy-bundle.sh
@tolusha, @riuvshin: please, review this request.
1) add merge of properties in time of update Codenvy from binary
2) add script to migrate from 4.0.1 to 4.1.0
3) add scripts to prepare Codenvy bundle and upload it to update server
4) don't replace default properties in time of update Codenvy
> CODENVY-368: fix merge of properties, add scripts for migration

- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
Replace existed proxy settings by bootstrap script.
Enclose bash variables into quotes, according to this recommendations https://google.github.io/styleguide/shell.xml?showone=Quoting#Quoting
> Replace existed proxy settings; bootstrap script improvements.

- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/vcs/GitVcsService.java
- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/resources/com/codenvy/plugin/pullrequest/PullRequest.gwt.xml
> Fix PullRequest Plugin according chnages in GitServiceClient

- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-install-single-node-behind-the-proxy-with-codenvy4.sh
> CODENVY-408: fix setting codenvy properties from bootstrap script

- core/codenvy-hosted-workspace-activity/src/main/java/com/codenvy/activity/server/WorkspaceActivityManager.java
@skabashnyuk @garagatyi @mkuznyetsov
> Fixed updating of runtime workspace in activity manager and formatting

- core/codenvy-hosted-api-admin/src/main/java/com/codenvy/api/dao/ldap/AdminUserDaoImpl.java
- core/codenvy-hosted-api-admin/src/main/java/com/codenvy/api/user/server/AdminUserService.java
- core/codenvy-hosted-api-admin/src/main/java/com/codenvy/api/user/server/dao/AdminUserDao.java
- core/codenvy-hosted-api-admin/src/test/java/com/codenvy/api/dao/ldap/AdminUserDaoTest.java
- core/codenvy-hosted-api-admin/src/test/java/com/codenvy/api/user/server/AdminUserServiceTest.java
Add page links for gettings users.
> CHE-243: Return link header describing page links

- core/codenvy-hosted-api-admin/src/main/java/com/codenvy/api/dao/ldap/AdminUserDaoImpl.java
- core/codenvy-hosted-api-admin/src/main/java/com/codenvy/api/user/server/AdminUserService.java
- core/codenvy-hosted-api-admin/src/main/java/com/codenvy/api/user/server/dao/AdminUserDao.java
- core/codenvy-hosted-api-admin/src/test/java/com/codenvy/api/dao/ldap/AdminUserDaoTest.java
- core/codenvy-hosted-api-admin/src/test/java/com/codenvy/api/user/server/AdminUserServiceTest.java
> Revert "CHE-243: Return link header describing page links"

- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
Signed-off-by: Mykola Morhun <mmorhun@codenvy.com>
> CODENVY-350: Set up workspaces to work behind the proxy

- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-backup-restore-single-node-with-codenvy4.sh
> Fix test of backup/restore Codenvy on-prem 4.x

- core/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManager.java
- core/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManagerTest.java
- dashboard/src/app/factories/load-factory/load-factory.controller.js
> CODENVY-363: modify error messages for dashboard

- plugins/plugin-hosted/codenvy-swarm-machine/src/main/java/com/codenvy/swarm/client/SwarmDockerConnector.java
Also require new property in puppet swarm.client.node_description_length
@riuvshin @skabashnyuk Please review
> CODENVY-423: fixed swarm nodes info parsing

- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECMultiServerHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECSingleServerHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/commands/CommandLibrary.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/ConfigManager.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/LdapManager.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifact.java
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.1.1/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.2.0-RC1-SNAPSHOT/codenvy-single-server.properties
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-install-single-node-behind-the-proxy-with-codenvy4.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-update-single-node-from-binary-with-codenvy4.sh
@tolusha: please, reveiw this request.
> Fix codenvy.properties; backup manifest before update Codenvy

- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECMultiServerHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECSingleServerHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/ConfigManager.java
> CODENVY-417: fix error of installing puppet as a root user

- dashboard/src/assets/branding/product.json
> CHE-771: change not configured oAuth message

- dashboard/src/app/factories/load-factory/load-factory.html
> use che-steps-container directive

- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECMultiServerHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECSingleServerHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/ConfigManager.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifact.java
> Codenvy 417: refactoring; add unit tests.

- assembly/onpremises-ide-packaging-war-ext-server/src/main/webapp/WEB-INF/classes/codenvy/che-machine-configuration.properties
- core/codenvy-hosted-workspace-activity-agent/src/main/java/com/codenvy/workspace/WorkspaceActivityNotifier.java
Activity notification will be send as soon as activity is occured,
but not more than once in a specific amount of time (60 seconds).
> CODENVY-428 Improve workspace activity notification

- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECSingleServerHelper.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifact.java
> CODENVY-296: remove wrong 'local' prefix

- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECSingleServerHelper.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifact.java
> CODENVY-417: fix export http(s) proxy settings to 'yum install puppet… command'

- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-install-single-node-behind-the-proxy-with-codenvy4.sh
> Fix wait workspace timeout in IM test

- cdec/installation-manager-resources/src/main/resources/patches/4.2.0/single_server/patch_before_update.sh
- cdec/installation-manager-resources/src/main/resources/patches/4.2.0/single_server/update_mongo.js
> Add script to  migrate from  Codenvy 4.1.1 to 4.2.0

- platform-api-client-java/core/pom.xml
- platform-api-client-java/core/src/test/resources/codenvy-sdk.properties
Fix for platform-api-client-java integration tests.
@skabashnyuk @benoitf
> CODENVY-434 Adapt Che URL and port config

- dashboard/src/app/account/details/account-update-password.html
- dashboard/src/app/account/details/account-update-password.styl
- dashboard/src/app/admin/user-management/add-user/add-user.html
- dashboard/src/app/admin/user-management/add-user/add-user.styl
> CODENVY-272: change UI for password fields

- dashboard/src/app/factories/list-factories/factory-item/factory-item.html
- dashboard/src/app/factories/list-factories/factory-item/factory-item.styl
> CHE-769: remove icon from factories

- assembly/onpremises-ide-packaging-war-platform-api/src/main/webapp/WEB-INF/classes/codenvy/codenvy-api-configuration.properties
> CHE-323: improve readability of stacks config

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.2.0/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.3.0-RC1-SNAPSHOT/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/patches/4.2.0/single_server/patch_before_update.sh
> Fix machine_ws_agent_max_start_time_ms codenvy property

- cdec/installation-manager-resources/src/main/resources/patches/4.2.0/single_server/patch_before_update.sh
> Add quotes around machine_ws_agent_max_start_time_ms value

- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
> CODENVY-353: improve checking sudo rights before installing Codenvy

- plugins/plugin-hosted/codenvy-hosted-ext-factory/src/main/java/com/codenvy/ide/factory/client/accept/AcceptFactoryHandler.java
- plugins/plugin-hosted/codenvy-hosted-ext-factory/src/main/java/com/codenvy/ide/factory/client/json/ImportFromConfigPresenter.java
- plugins/plugin-hosted/codenvy-hosted-ext-factory/src/main/java/com/codenvy/ide/factory/client/utils/FactoryProjectImporter.java
- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/parts/contribute/ContributePartPresenter.java
- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/steps/AuthorizeCodenvyOnVCSHostStep.java
- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/steps/CommitWorkingTreeStep.java
- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/steps/DefineWorkBranchStep.java
- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/steps/DetectPullRequestStep.java
- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/steps/DetermineUpstreamRepositoryStep.java
- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/steps/GenerateReviewFactoryStep.java
- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/steps/InitializeWorkflowContextStep.java
- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/utils/NotificationHelper.java
Signed-off-by: Roman Nikitenko <rnikitenko@codenvy.com>
> CHE-362. Changes according to adding display modes in  StatusNotification

- cdec/installation-manager-tests/src/main/resources/bin/im-install/test-install-sudo-password-required.sh
> CODENVY-353: fix integration test

- cdec/installation-manager-core/src/main/java/com/codenvy/im/agent/AbstractAgent.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/agent/AgentException.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/agent/ConnectionException.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/agent/LocalAgent.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/agent/LocalAsyncAgent.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/agent/SecureShellAgent.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/commands/CommandLibrary.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/commands/SimpleCommand.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/NodeManager.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/helper/NodeManagerHelper.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/BaseTest.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/agent/TestSecureShellAgent.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/TestNodeManager.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/helper/TestNodeManagerHelperCodenvy3Impl.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/helper/TestNodeManagerHelperCodenvy4Impl.java
1) check if puppet master is accessible from the node
2) validate if user has sudo rights in node to add.
> Codenvy-275: improve validation of node to add

- cdec/installation-manager-core/src/test/java/com/codenvy/im/agent/TestSecureShellAgent.java
> CODENVY-273: fix TestSecureShellAgent

- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-backup-restore-single-node-with-codenvy4.sh
> Fix test-backup-restore-single-node-with-codenvy4

- dashboard/src/app/navbar/codenvy-navbar.html
- dashboard/src/app/navbar/codenvy-navbar.styl
- dashboard/src/app/navbar/logout/logout.html
- dashboard/src/app/navbar/navbar.controller.js
1. rework the "Avatar" section 
- fix alignment of avatar;
- remove theability to expand/remove the "Avatar" section;
2. show number of workspaces in Sidebar 
3. add label for "Logout" icon
> Navbar menu improvements

- core/codenvy-hosted-sso-client/src/main/java/com/codenvy/auth/sso/client/HttpSsoServerClient.java
- core/codenvy-hosted-sso-client/src/test/java/com/codenvy/auth/sso/client/HttpSsoServerClientTest.java
> Fix url for unregistering client

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.3.0-RC1-SNAPSHOT/codenvy-single-server.properties
> Fix default properties of Codenvy 4.3.0-RC1-SNAPSHOT

- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECArtifactHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECSingleServerHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/SystemProxySettings.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifact.java
- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
> CODENVY-473: add proxy settings into 'user' section of puppet.conf

- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECArtifactHelper.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifact.java
Remove redundant quotes from puppet.conf.
> fixup! CODENVY-473: add proxy settings into 'user' section of puppet.conf

- plugins/plugin-hosted/codenvy-hosted-ext-factory/src/main/java/com/codenvy/ide/factory/client/welcome/GreetingPartPresenter.java
- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/parts/contribute/ContributePartPresenter.java
> Update code in accordance with Part API changes

- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECArtifactHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECSingleServerHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/SystemProxySettings.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/ConfigManager.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/utils/HttpTransport.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifact.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/helper/SystemProxySettingsTest.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/TestConfigManager.java
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.3.0-RC1-SNAPSHOT/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
> CODENVY-473: IM: fix yum.conf, fix http(s)_proxy settings

- assembly/onpremises-ide-packaging-war-platform-api/pom.xml
> CHE-747:Move ProjectTemplateService to separate module

- dashboard/src/app/factories/load-factory/load-factory.controller.js
> CHE-1026: rework wsagent usage

- cdec/installation-manager-cli-bundle/pom.xml
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/LdapManager.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/facade/TestInstallationManagerFacade.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/saas/SaasAuthServiceProxyTest.java
- cdec/installation-manager-server-war/src/main/java/com/codenvy/im/service/InstallationManagerService.java
- cdec/installation-manager-server-war/src/test/java/com/codenvy/im/service/InstallationManagerServiceContractTest.java
- cdec/installation-manager-server-war/src/test/java/com/codenvy/im/service/InstallationManagerServiceTest.java
@skabashnyuk, @tolusha: please review this request.
> CODENVY-478: fix installation manager to work without che-core-api-account

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.2.2/codenvy-single-server.properties
@riuvshin: please review this request.
> Add Codenvy on-prem 4.2.2 default properties

- cdec/installation-manager-cli-bundle/pom.xml
> CODENVY-473: add missed library for IM CLI

- cdec/installation-manager-core/src/test/java/com/codenvy/im/facade/TestInstallationManagerFacade.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/DownloadManagerTest.java
- cdec/installation-manager-tests/src/main/resources/bin/im-download/test-download-all-updates.sh
> CODENVY-473: add IM unit tests; fix integration tests

- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECSingleServerHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/Config.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/LdapManager.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/TestConfig.java
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-install-single-node-and-change-config-with-codenvy4.sh
> CODENVY-503: fix path to codenvy conf dir

- assembly/onpremises-ide-packaging-war-ext-server/src/main/webapp/WEB-INF/web.xml
- assembly/onpremises-ide-packaging-war-platform-api/src/main/webapp/WEB-INF/web.xml
- dashboard/src/app/factories/load-factory/load-factory.controller.js
- plugins/plugin-bitbucket/codenvy-plugin-bitbucket-ext-bitbucket/src/main/java/org/eclipse/che/ide/ext/bitbucket/client/BitbucketClientService.java
- plugins/plugin-bitbucket/codenvy-plugin-bitbucket-ext-bitbucket/src/main/java/org/eclipse/che/ide/ext/bitbucket/server/rest/BitbucketService.java
- plugins/plugin-microsoft/codenvy-plugin-microsoft-vsts-ext-client/src/main/java/org/eclipse/che/ide/ext/microsoft/client/MicrosoftServiceClientImpl.java
- plugins/plugin-microsoft/codenvy-plugin-microsoft-vsts-ext-server/src/main/java/org/eclipse/che/ide/ext/microsoft/server/rest/MicrosoftVstsService.java
> CHE-1081: remove workspace id usage in wsagent services

- core/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManager.java
- core/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManagerTest.java
> Add parameters for auto-snapshot and auto-restore of the workspace state

- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
> Add binding for components separated in che

- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-backup-restore-single-node-with-codenvy4.sh
> Fix integration test of backup/restore Codenvy 4.x

- assembly/onpremises-ide-packaging-war-ide-resources/src/main/webapp/initializer/init.js
> CODENVY-531: cleanup init.js

- assembly/onpremises-ide-packaging-war-ext-server/pom.xml
https://github.com/eclipse/che/pull/1306
> CHE-956 remove dependency on che-jdt-ext-machine

- assembly/onpremises-ide-packaging-war-platform-api/pom.xml
add che-core-api-project instead
> remove dependency on che-plugin-java-ext-lang-server

- assembly/onpremises-ide-packaging-war-factory/src/main/java/com/codenvy/onpremises/factory/FactoryServlet.java
- assembly/onpremises-ide-packaging-war-factory/src/main/java/com/codenvy/onpremises/factory/filter/FactoryParamsFilter.java
- assembly/onpremises-ide-packaging-war-factory/src/main/java/com/codenvy/onpremises/factory/filter/FactoryRetrieverFilter.java
- assembly/onpremises-ide-packaging-war-factory/src/test/java/com/codenvy/onpremises/factory/FactoryParamsFilterTest.java
- assembly/onpremises-ide-packaging-war-factory/src/test/java/com/codenvy/onpremises/factory/FactoryServletTest.java
- assembly/onpremises-ide-packaging-war-platform-api/pom.xml
- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
- dashboard/src/app/factories/factories-config.js
- dashboard/src/app/factories/load-factory/load-factory.controller.js
- dashboard/src/components/api/codenvy-factory.factory.js
- plugins/plugin-github/codenvy-plugin-github-factory-resolver/pom.xml
- plugins/plugin-github/codenvy-plugin-github-factory-resolver/src/main/java/com/codenvy/plugin/factory/github/factory/resolver/GithubFactoryParametersResolver.java
- plugins/plugin-github/codenvy-plugin-github-factory-resolver/src/test/java/com/codenvy/plugin/factory/github/factory/resolver/GithubFactoryParametersResolverTest.java
- plugins/plugin-github/pom.xml
- pom.xml
Change-Id: Ic5707936dfb9682126f14a2ed7b1716becde31cd
> CODENVY-502 allow to create factories by providing github URL

- assembly/onpremises-ide-compiling-war-ide/pom.xml
- assembly/onpremises-ide-packaging-war-ext-server/pom.xml
- assembly/onpremises-ide-packaging-war-ext-server/src/main/java/com/codenvy/ext/java/server/MachineModule.java
> CODENVY-541: Add needed dependency. Install DebugModule

- dashboard/src/app/account/details/account-config.js
- dashboard/src/app/account/details/profile/account-profile.controller.js
- dashboard/src/app/account/details/profile/account-profile.directive.js
- dashboard/src/app/account/details/profile/account-profile.html
> CODENVY-516: modify 'Job title' input with the 'Role' drop down list

- analytics/pom.xml
- plugins/plugin-github/pom.xml
- plugins/plugin-pullrequest/pom.xml
(mainly due to the merge of multiple repositories into one single repository)
Change-Id: I6846667fda14380725a4278f0636cac05d31aee4
> CODENVY-549 Remove invalid settings found in pom.xml

- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-update-codenvy4-config.sh
- cdec/installation-manager-tests/src/main/resources/bin/config.sh
> CODENVY-511: add --config option to point custom codenvy.properties

- cdec/installation-manager-tests/src/main/resources/bin/im-config/test-config-check-im-config.sh
> CODENVY-512: fix IM integration test of checking IM config

- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-setup-and-update-codenvy4-config.sh
- cdec/installation-manager-tests/src/main/resources/bin/config.sh
- cdec/installation-manager-tests/src/test/java/com/codenvy/im/TestInstallationManagerCliWithCodenvy4.java
> CODENVY-511: update codenvy.properties file in case of --config option; add test

- plugins/plugin-bitbucket/codenvy-plugin-bitbucket-ext-bitbucket/pom.xml
- plugins/plugin-bitbucket/codenvy-plugin-bitbucket-ext-bitbucket/src/main/java/org/eclipse/che/ide/ext/bitbucket/server/BitbucketKeyUploader.java
This is needed for merging Jgit implementation
> CHE-336: Refactoring of GitUrl class

- dashboard/src/app/factories/factory-details/information-tab/delete-factory/delete-factory.html
- dashboard/src/app/factories/list-factories/factory-item/factory-item.html
- dashboard/src/app/factories/list-factories/factory-item/factory-item.styl
> CHE-797: correct switch to mobile view for list of factories

- cdec/installation-manager-core/pom.xml
- cdec/installation-manager-tests/src/main/resources/bin/config.sh
- cdec/upload-installation-manager.sh
> Replace codenvy-stg.com on codenvy-dev.com in integration tests

- pom.xml
Fix dependency management section in accordance with [customer saas](https://github.com/codenvy/customer-saas/blob/master/pom.xml#L46)
> remove needless dependencies to site versions

- cdec/installation-manager-server-war/src/main/java/com/codenvy/im/service/InstallationManagerService.java
- cdec/installation-manager-server-war/src/test/java/com/codenvy/im/service/InstallationManagerServiceContractTest.java
> Fix service which returns IM server config

- dashboard/src/app/admin/user-management/user-management.controller.js
- dashboard/src/app/admin/user-management/user-management.html
- dashboard/src/app/admin/user-management/user-management.styl
- dashboard/src/app/index.module.js
- dashboard/src/components/api/builder/codenvy-api-builder.factory.js
- dashboard/src/components/api/builder/codenvy-user-builder.js
- dashboard/src/components/api/codenvy-api-config.js
- dashboard/src/components/api/codenvy-user.factory.js
- dashboard/src/components/api/codenvy-user.spec.js
- dashboard/src/components/api/test/codenvy-http-backend-provider.factory.js
- dashboard/src/components/api/test/codenvy-http-backend.factory.js
- dashboard/src/components/api/test/codenvy-http-backend.js
> CODENVY-40: add pagination to list of users

- core/codenvy-hosted-sso-server/src/main/java/com/codenvy/auth/sso/server/ticket/InMemoryTicketManager.java
In case if sso server is not able to send logout request.
Added  clienurl to be able to detect some failures.
> CODENVY-594 Log cleanup 

- core/codenvy-hosted-machine-authentication/src/main/java/com/codenvy/machine/authentication/server/MachineServiceAuthLinksInjector.java
- core/codenvy-hosted-machine-authentication/src/test/java/com/codenvy/machine/authentication/server/MachineServiceAuthLinksInjectorTest.java
> CHE-1269: Add check for machine runtime during links formation

- core/codenvy-hosted-sso-client/pom.xml
- core/codenvy-hosted-sso-client/src/main/java/com/codenvy/auth/sso/client/MachineSsoServerClient.java
- core/codenvy-hosted-sso-client/src/test/java/com/codenvy/auth/sso/client/MachineSsoServerClientTest.java
> CODENVY-495: Replaced api token to machine token in sso principal

- assembly/onpremises-ide-packaging-war-platform-api/src/main/webapp/WEB-INF/classes/codenvy/codenvy-api-configuration.properties
- core/codenvy-hosted-events/src/main/java/com/codenvy/user/interceptor/CreateUserInterceptor.java
- core/codenvy-hosted-events/src/test/java/com/codenvy/user/interceptor/CreateUserInterceptorTest.java
- core/codenvy-hosted-recoverpassword/src/main/java/com/codenvy/service/password/PasswordService.java
- core/codenvy-hosted-recoverpassword/src/test/java/com/codenvy/service/password/PasswordServiceTest.java
- core/codenvy-hosted-sso-auth-bearer/pom.xml
- core/codenvy-hosted-sso-auth-bearer/src/main/java/com/codenvy/auth/sso/server/BearerTokenAuthenticationService.java
- core/codenvy-hosted-sso-auth-bearer/src/test/java/com/codenvy/auth/sso/server/BearerTokenAuthenticationServiceTest.java
- core/codenvy-hosted-sso-auth-bearer/src/test/resources/email-templates/verify_email_address.html
@riuvshin will create new mail sender address property in puppet if this PR is ok
> CODENVY-513: Replace hardcoded email sender to property

- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiServletModule.java
required to make workspace export feature working
Change-Id: Ia5e99c3fc762e68cb526eec858a8ca9bdba4c694
> CODENVY-566 restore (again and again) CORS on platform API

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.3.0-RC2-SNAPSHOT/codenvy-single-server.properties
> Update default codenvy on-prem properties to 4.3.0-R2-SNAPSHOT

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.3.0-RC2-SNAPSHOT/codenvy-single-server.properties
> CODENVY-617: add property of docker privilege mode

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.3.0-RC2-SNAPSHOT/codenvy-single-server.properties
> CODENVY-610: add possibility to config no_proxy property

- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
@TylerJewell: is it the same what you requested?
> CODENVY-610: add --no-proxy option to bootstrap script

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/AuthDockerInstanceProvider.java
@garagatyi @vparfonov @skabashnyuk @evoevodin  please review
> CODENVY-595: add possibility to adjust machine swap size

- assembly/onpremises-ide-packaging-war-ext-server/pom.xml
- assembly/onpremises-ide-packaging-war-ext-server/src/main/java/com/codenvy/ext/java/server/MachineModule.java
- core/codenvy-hosted-machine-authentication-ide/pom.xml
- core/codenvy-hosted-machine-authentication-ide/src/main/java/com/codenvy/machine/authentication/ide/CodenvyMachineLinksModifier.java
- core/codenvy-hosted-machine-authentication-ide/src/main/java/com/codenvy/machine/authentication/ide/inject/MachineAuthGinModule.java
- core/codenvy-hosted-machine-authentication/src/main/java/com/codenvy/machine/authentication/server/WorkspaceServiceAuthLinksInjector.java
- pom.xml
- wsagent/pom.xml
- wsagent/wsagent-codenvy/pom.xml
- wsagent/wsagent-codenvy/src/main/java/com/codenvy/api/agent/WsAgentURLProvider.java
This pull request provides implementation for url modifier that adds machine token as a query parameter into specified url.
@skabashnyuk, @vparfonov
> CODENVY-583: Fix JavaDoc feature

- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-setup-and-update-codenvy4-config.sh
> Fix IM test of update single node with Codenvy 4

- dashboard/src/app/factories/factory-details/factory-details.html
- dashboard/src/app/index.module.js
- dashboard/src/app/workspace/share-workspace/share-workspace.controller.js
- dashboard/src/app/workspace/share-workspace/share-workspace.directive.js
- dashboard/src/app/workspace/share-workspace/share-workspace.html
- dashboard/src/app/workspace/share-workspace/share-workspace.styl
- dashboard/src/app/workspace/share-workspace/user-item/user-item.controller.js
- dashboard/src/app/workspace/share-workspace/user-item/user-item.directive.js
- dashboard/src/app/workspace/share-workspace/user-item/user-item.html
- dashboard/src/app/workspace/share-workspace/user-item/user-item.styl
- dashboard/src/app/workspace/workspace-config.js
- dashboard/src/components/api/codenvy-api-config.js
- dashboard/src/components/api/codenvy-api.factory.js
- dashboard/src/components/api/codenvy-permissions.factory.js
> CHE-1222: add ability to share workspace with other users

- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
- core/codenvy-hosted-machine-authentication/pom.xml
- core/codenvy-hosted-machine-authentication/src/main/java/com/codenvy/machine/authentication/server/MachineTokenService.java
- core/codenvy-hosted-machine-authentication/src/main/java/com/codenvy/machine/authentication/server/interceptor/InterceptorModule.java
- core/codenvy-hosted-machine-authentication/src/main/java/com/codenvy/machine/authentication/server/interceptor/MachineTokenInterceptor.java
- core/codenvy-hosted-machine-authentication/src/test/java/com/codenvy/machine/authentication/server/interceptor/MachineTokenInterceptorTest.java
> Revert machine token interceptor

- core/codenvy-hosted-sso-oauth/src/main/java/com/codenvy/auth/sso/oauth/OAuthLoginServlet.java
Use BadRequestException instead of InputDataException
> Replace missing exception

- core/codenvy-hosted-mail-server/pom.xml
- core/codenvy-hosted-mail-server/src/main/java/com/codenvy/mail/MailSender.java
This will resolve problem when two users send request for sending email at the same time, and sending second email fails.
> CODENVY-635: Create attachment files in separate temp directory

- assembly/onpremises-ide-packaging-war-platform-api/pom.xml
- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
- pom.xml
- wsmaster/codenvy-hosted-api-factory/pom.xml
- wsmaster/codenvy-hosted-api-factory/src/main/java/com/codenvy/api/factory/server/filters/FactoryPermissionsFilter.java
- wsmaster/codenvy-hosted-api-factory/src/test/java/com/codenvy/api/factory/server/filters/FactoryPermissionsFilterTest.java
- wsmaster/pom.xml
Now factory service getFromJson method permissions will be covered by FactoryPermissionsFilter
@skabashnyuk, @sleshchenko please review
> CODENVY-641: Add factory permission filter

- dashboard/src/app/navbar/codenvy-navbar.html
- dashboard/src/app/navbar/navbar.controller.js
> CHE-1315: remove 'Team' from dashboard

- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
> CODENVY-480 Fix creation of user

- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECMultiServerHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/SystemProxySettings.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/commands/CommandLibrary.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/Config.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/ConfigManager.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifact.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/helper/SystemProxySettingsTest.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/commands/TestCommandLibrary.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/TestConfigManager.java
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.3.0-RC2-SNAPSHOT/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-install-single-node-behind-the-proxy-with-codenvy4.sh
- cli/assembly/src/main/resources/bin/unix/codenvy
@riuvshin, @benoitf: please, review this request.
> CODENVY-631: divide bootstrap script proxy options

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.3.0/codenvy-single-server.properties
> Add docker property into Codenvy on-prem config

- core/codenvy-hosted-api-permission/pom.xml
- core/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/PermissionsService.java
> CODENVY-606 Add swagger annotations for Permissions API

- cdec/update-server-packaging-war/src/main/java/com/codenvy/im/UpdateServerServletModule.java
@sleshchenko: please, review your changes which I just committed.
> CODENVY-653: fix error of logging event by using Update Server

- cdec/installation-manager-resources/src/main/resources/patches/4.3.1/single_server/update_mongo.js
@mshaposhnik: please, review this request.
> CODENVY-446: add mongo script to update snapshots in time of migration

- cdec/installation-manager-resources/src/main/resources/patches/4.3.2/single_server/update_mongo.js
@mshaposhnik: please, review this request.
> CODENVY-466: fix migrate snapshot script to work around incomplete data

- cdec/installation-manager-resources/src/main/resources/patches/4.3.2/single_server/update_mongo.js
> CODENVY-446: fix script to migrate Codenvy 4.2.2 to 4.3.2

- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/LdapManager.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/LdapManagerCodenvy3Test.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/LdapManagerCodenvy4Test.java
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-update-single-node-from-binary-with-codenvy4.sh
> CODENVY-547: fix error of changing of non-default admin password

- dashboard/src/app/workspace/share-workspace/share-workspace.controller.js
> CHE-1326: check recipe location exists before setting permissions

- assembly/onpremises-ide-packaging-war-platform-api/src/main/webapp/WEB-INF/classes/predefined-recipes.json
- core/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/PermissionManager.java
- core/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/PermissionsService.java
- core/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/filter/GetPermissionsFilter.java
- core/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/WorkspaceApiModule.java
- core/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/filters/AclSetPermissionsFilter.java
- core/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/filters/RecipePermissionsFilter.java
- core/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/filters/StackPermissionsFilter.java
- core/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/recipe/RecipeDomain.java
- core/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/recipe/RecipePermissionStorage.java
- core/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/stack/StackDomain.java
- core/codenvy-hosted-api-workspace/src/test/java/com/codenvy/api/workspace/server/filters/AclSetPermissionsFilterTest.java
- core/codenvy-hosted-api-workspace/src/test/java/com/codenvy/api/workspace/server/filters/RecipeCreatorPermissionsProviderTest.java
- core/codenvy-hosted-api-workspace/src/test/java/com/codenvy/api/workspace/server/filters/RecipePermissionsFilterTest.java
- core/codenvy-hosted-api-workspace/src/test/java/com/codenvy/api/workspace/server/filters/StackPermissionsFilterTest.java
- core/codenvy-hosted-authorization/src/main/java/com/codenvy/api/permission/server/PermissionChecker.java
- core/codenvy-hosted-authorization/src/main/java/com/codenvy/api/permission/server/PermissionCheckerImpl.java
- core/codenvy-hosted-authorization/src/main/java/com/codenvy/api/permission/server/PermissionTokenHandler.java
- core/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/dao/mongo/recipe/RecipeDaoImpl.java
- core/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/dao/mongo/stack/StackDaoImpl.java
- core/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/dao/mongo/RecipeDaoImplTest.java
- core/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/dao/mongo/StackDaoImplTest.java
> CODENVY-667 Add 'search' action for stacks and recipes

- dashboard/package.json
> fix UD transitive dependency of gulp-angular-templatecache

- dashboard/src/app/index.module.js
> CHE-1301: add not modified condition to the machine token response

- assembly/onpremises-ide-compiling-war-ide/pom.xml
- assembly/onpremises-ide-compiling-war-ide/src/main/resources/com/codenvy/ide/IDE.gwt.xml
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/AuthDockerInstanceProvider.java
Signed-off-by: Mykola Morhun <mmorhun@codenvy.com>
> CHE-1296: Use docker auth config saved in user preferences to start machine from private image

- dashboard/src/app/navbar/navbar.controller.js
> CHE-1342: improve navbar styles

- dashboard/src/app/factories/load-factory/load-factory.controller.js
> CODENVY-677: fix factories loading

- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/NodeConfig.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/helper/AdditionalNodesConfigHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/helper/AdditionalNodesConfigHelperCodenvy4Impl.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/helper/NodeManagerHelperCodenvy4Impl.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/TestNodeConfig.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/helper/TestAdditionalNodesConfigHelperCodenvy4.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/helper/TestNodeManagerHelperCodenvy4Impl.java
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-add-remove-codenvy-nodes-with-codenvy4.sh
> CODENVY-456: rename 'MACHINE' node type to 'MACHINE NODE'

- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-add-remove-codenvy-nodes-with-codenvy4.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-backup-restore-single-node-with-codenvy4.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-install-single-node-behind-the-proxy-with-codenvy4.sh
- cdec/installation-manager-tests/src/main/resources/bin/install/test-install-im-cli-in-rhel-os.sh
- cdec/installation-manager-tests/src/main/resources/bin/install/test-install-im-cli.sh
- cdec/installation-manager-tests/src/main/resources/bin/lib.sh
- cdec/installation-manager-tests/src/test/java/com/codenvy/im/TestInstallationManagerCli.java
- cdec/installation-manager-tests/src/test/java/com/codenvy/im/TestInstallationManagerCliWithCodenvy4.java
> CODENVY-309: check subscription of RHEL when installing Codenvy on-prem

- dashboard/src/app/navbar/navbar.controller.js
> CHE-1180: add ability to configure private docker registries

- lib/websocket-terminal/pom.xml
- pom.xml
> add che.lib.version property

- core/codenvy-hosted-api-admin/src/test/java/com/codenvy/api/user/server/AdminUserServiceTest.java
These changes are needed to avoid directly binding ApiExceptionMapper
that produces exception in other tests with everrest assured
> Rework AdminUserServiceTests with everrest assured

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.4.0-RC1-SNAPSHOT/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-install-single-node-behind-the-proxy-with-codenvy4.sh
> CODENVY-644: add --no-proxy-for-docker-daemon option to bootstrap script

- assembly/onpremises-ide-packaging-tomcat-api/src/assembly/assembly.xml
- assembly/onpremises-ide-packaging-tomcat-codenvy-allinone/src/assembly/assembly.xml
- assembly/onpremises-ide-packaging-war-platform-api/src/main/webapp/WEB-INF/classes/codenvy/codenvy-api-configuration.properties
> CODENVY-614: rename folder che-templates to templates

- dashboard/src/app/navbar/navbar.controller.js
> Fix redirect to site login page on logout

- core/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManager.java
- core/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManagerTest.java
Fix limits checking user on ws startup
> Codenvy 694 Fix limits checking user on ws startup

- cdec/installation-manager-tests/src/main/resources/bin/config.sh
- cdec/installation-manager-tests/src/main/resources/vagrant/single-codenvy4-with-additional-nodes/CentOS7/Vagrantfile
- cdec/installation-manager-tests/src/main/resources/vagrant/single-codenvy4-with-additional-nodes/RHEL7/Vagrantfile
- cdec/installation-manager-tests/src/main/resources/vagrant/single/CentOS7/Vagrantfile
- cdec/installation-manager-tests/src/main/resources/vagrant/single/RHEL7/Vagrantfile
@skryzhny: please, review this request.
> Switch to temporary address updater-nightly2.codenvy-dev.com

- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/CDECArtifact.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECArtifactHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/utils/Version.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifact.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifactGetInstalledVersion.java
> CODENVY-701: fix Codenvy version where the path is changed

- cdec/installation-manager-tests/src/main/resources/bin/config.sh
- cdec/installation-manager-tests/src/main/resources/vagrant/single-codenvy4-with-additional-nodes/CentOS7/Vagrantfile
- cdec/installation-manager-tests/src/main/resources/vagrant/single-codenvy4-with-additional-nodes/RHEL7/Vagrantfile
- cdec/installation-manager-tests/src/main/resources/vagrant/single/CentOS7/Vagrantfile
- cdec/installation-manager-tests/src/main/resources/vagrant/single/RHEL7/Vagrantfile
> Restore update server address for integration tests

- core/codenvy-hosted-machine-authentication-ide/src/main/java/com/codenvy/machine/authentication/ide/MachineAsyncRequestFactory.java
- plugins/plugin-hosted/codenvy-hosted-ext-hosted/pom.xml
- plugins/plugin-hosted/codenvy-hosted-ext-hosted/src/main/java/com/codenvy/ide/hosted/client/workspace/HostedWorkspaceStoppedHandler.java
Signed-off-by: Vitaliy Guliy <vguliy@codenvy.com>
> CHE-1277 Move machines output to project perpective

- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
- cdec/installation-manager-tests/src/main/resources/bin/install/test-install-im-cli-in-rhel-os.sh
> CODENVY-309: simplify verification of RHEL subscription

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/swarm/client/SwarmDockerConnector.java
> CHE-1276: Move DockerException to package exception

- cdec/installation-manager-tests/src/main/resources/bin/lib.sh
> Fix tear down steps on exit in IM CLI integration tests

- assembly/onpremises-ide-packaging-war-ide-resources/src/main/webapp/initializer/init.js
Signed-off-by: Vitaliy Guliy <vguliy@codenvy.com>
> CHE-1396 Double nav bar in some cases

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.4.0/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.5.0-RC1-SNAPSHOT/codenvy-single-server.properties
> Add default properties of Codenvy on-prem 4.4.0

- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECSingleServerHelper.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifact.java
> CODENVY-702: fix command which hangs up when changing Codenvy hostname

- cdec/installation-manager-cli-bundle/src/main/java/com/codenvy/im/cli/command/AbstractIMCommand.java
- cdec/installation-manager-cli-bundle/src/test/java/com/codenvy/im/cli/command/TestDownloadCommand.java
- cdec/installation-manager-tests/src/main/resources/bin/install/test-install-update-im-cli-client.sh
> Fix update IM CLI message

- assembly/onpremises-ide-packaging-war-ext-server/pom.xml
- assembly/onpremises-ide-packaging-war-ext-server/src/main/java/com/codenvy/ext/java/server/MachineModule.java
> CHE-1256: Set Jgit implementation as default Git implementation

- dashboard/src/app/account/details/account-config.js
- dashboard/src/app/admin/admin-config.js
- dashboard/src/app/admin/user-management/user-management-config.js
- dashboard/src/app/factories/create-factory/create-factory-config.js
- dashboard/src/app/factories/factories-config.js
- dashboard/src/app/factories/factory-details/factory-details-config.js
- dashboard/src/app/factories/load-factory/load-factory.controller.js
- dashboard/src/app/index.module.js
- dashboard/src/assets/branding/product.json
- dashboard/src/index.html
> CHE-1395: fix browser titles

- plugins/plugin-hosted/codenvy-machine-hosted/pom.xml
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/RemoteDockerNode.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/swarm/client/SwarmDockerConnector.java
Cleanup code after refactoring of docker client in Che
@skabashnyuk @evoevodin @mmorhun @AndrienkoAleksandr Please review
> CHE-1365: remove usage of deprecated methods

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/swarm/client/SwarmDockerConnector.java
Swarm changed output of API, so I've added workaround to be able to use that code with newest and older versions of swarm.
@riuvshin @skabashnyuk @evoevodin @mmorhun Please review
> CODENVY-720: Fix snapshot recovering

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/swarm/client/SwarmDockerConnector.java
Depends on [Che PR](https://github.com/eclipse/che/pull/1663)
> CHE-1144: fix in accordance with changes in che

- dashboard/src/app/index.module.js
- dashboard/src/app/navbar/codenvy-navbar.html
- dashboard/src/app/navbar/navbar.controller.js
> CHE-1390: remove projects from main menu

- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-backup-restore-single-node-with-codenvy4.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-install-single-node-behind-the-proxy-with-codenvy4.sh
- cdec/installation-manager-tests/src/main/resources/bin/login/test-login-to-saas-through-im-cli.sh
> Fix user creation url in integration tests of IM CLI

- cdec/installation-manager-core/src/main/java/com/codenvy/im/agent/SecureShellAgent.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/commands/CommandLibrary.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/NodeManager.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/helper/NodeManagerHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/helper/NodeManagerHelperCodenvy3Impl.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/helper/NodeManagerHelperCodenvy4Impl.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/commands/TestCommandLibrary.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/helper/TestNodeManagerHelperCodenvy4Impl.java
- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-install-single-node-behind-the-proxy-with-codenvy4.sh
- cdec/installation-manager-tests/src/main/resources/vagrant/multi-with-additional-nodes/CentOS7/Vagrantfile
- cdec/installation-manager-tests/src/main/resources/vagrant/multi/CentOS7/Vagrantfile
- cdec/installation-manager-tests/src/main/resources/vagrant/single-codenvy4-with-additional-nodes/CentOS7/Vagrantfile
- cdec/installation-manager-tests/src/main/resources/vagrant/single-codenvy4-with-additional-nodes/RHEL7/Vagrantfile
- cdec/installation-manager-tests/src/main/resources/vagrant/single/CentOS7/Vagrantfile
- cdec/installation-manager-tests/src/main/resources/vagrant/single/RHEL7/Vagrantfile
> CODENVY-418: make Codenvy machine node add/remove behind the proxy

- cdec/installation-manager-server-war/src/main/resources/codenvy/installation-manager-server.properties
- cdec/update-server-packaging-war/src/main/resources/codenvy/update-server.properties
> Add 'auth.sso.client_allow_anonymous=false' property

- cdec/installation-manager-tests/src/main/resources/bin/login/test-login-to-saas-through-im-cli.sh
> Restore user creation url in integration tests of Codenvy 3.x

- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-add-remove-codenvy-nodes-with-codenvy4.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-install-single-node-behind-the-proxy-with-codenvy4.sh
- cdec/installation-manager-tests/src/main/resources/bin/lib.sh
> Fix integration test of adding nodes behind the proxy

- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/AuthDockerInstanceProvider.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedDockerInstanceProvider.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/swarm/client/SwarmDockerConnector.java
Workaround issue with pull on multi-node installation by replacing pull operation with build
> Codenvy 361

- assembly/onpremises-ide-packaging-war-ide-resources/src/main/webapp/initializer/init.css
- assembly/onpremises-ide-packaging-war-ide-resources/src/main/webapp/initializer/init.js
> CHE-1397: change styles of error page

- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-install-single-node-behind-the-proxy-with-codenvy4.sh
- cdec/installation-manager-tests/src/main/resources/bin/lib.sh
> CODENVY-418: fix test to create project on node behind the proxy

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.5.0/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.6.0-RC1-SNAPSHOT/codenvy-single-server.properties
> Update default Codenvy on-prem properties

- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/ConfigManager.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/TestConfigManager.java
> CODENVY-726: fix Codenvy on-prem apiEndpoint url

- cdec/installation-manager-core/src/main/java/com/codenvy/im/utils/HttpTransport.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/utils/TestHttpTransport.java
> CODENVY-726: fix checking if Codenvy on-prem is alive behind the proxy

- cli/assembly/src/main/resources/bin/unix/codenvy
> CODENVY-756: replace comma separator on pipeline in -Dhttp.nonProxyHosts

- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-update-single-node-from-binary-with-codenvy4.sh
@skryzhny: please, review this request.
> CODENVY-718: add bootstrap script option to disable monitoring tools

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/RemoteDockerNode.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/RemoteDockerNodeTest.java
Sometimes `IndexOutOfBoundsException` appears when starting workspace.
@garagatyi @mmorhun please review
> CODENVY-673: Fix IndexOutOfBoundsException

- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/CDECArtifact.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECArtifactHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECMultiServerHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECSingleServerHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/commands/CommandLibrary.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/NodeManager.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/helper/NodeManagerHelper.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifact.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/commands/TestCommandLibrary.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/TestNodeManager.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/helper/TestNodeManagerHelperCodenvy4Impl.java
- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-setup-and-update-codenvy4-config.sh
> CODENVY-702: check availability of Codenvy hostname

- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/ConfigManager.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/utils/HttpTransport.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/TestConfigManager.java
> CODENVY-726: fix error of waiting on aliveness of Codenvy behind the proxy.

- assembly/onpremises-ide-compiling-war-ide/src/main/resources/com/codenvy/ide/IDE.gwt.xml
> Use Model.gwt.xml see https://github.com/eclipse/che/pull/1869

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/launcher/WsAgentWithAuthLauncherImpl.java
This is related to https://github.com/eclipse/che/pull/1831
> CODENVY-572: Add exception to method signature

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/backup/MachineBackupManager.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/backup/WorkspaceFsBackupScheduler.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/backup/WorkspaceIdHashLocationFinder.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/backup/MachineBackupManagerTest.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/backup/WorkspaceFsBackupSchedulerTest.java
This PR prevents simultaneously run of several backup/restore processes for a workspace
> CODENVY-601: Do not run new backup/restore process when another one is still running

- dashboard/src/components/api/codenvy-user.factory.js
- dashboard/src/components/api/codenvy-user.spec.js
- dashboard/src/components/api/test/codenvy-http-backend.js
@olexii4  @akurinnoy @sleshchenko review please.
fix for https://github.com/codenvy/codenvy/issues/435
> codenvy-435: Fix user creation by Admin dashboard

- core/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/filters/WorkspacePermissionsFilter.java
- core/codenvy-hosted-api-workspace/src/test/java/com/codenvy/api/workspace/server/filters/WorkspacePermissionsFilterTest.java
- core/codenvy-hosted-machine-authentication/src/main/java/com/codenvy/machine/authentication/server/interceptor/InterceptorModule.java
- core/codenvy-hosted-machine-authentication/src/test/java/com/codenvy/machine/authentication/server/interceptor/MachineTokenInterceptorTest.java
- core/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManager.java
- core/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManagerTest.java
Fixes tests and other classes according to changes in Workspace API
https://github.com/eclipse/che/issues/1849
@evoevodin @sleshchenko please review
> CHE-1849 Fix according to changes in Workspace API

- core/codenvy-hosted-api-admin/src/main/java/com/codenvy/api/user/server/UserServicePermissionsFilter.java
- core/codenvy-hosted-api-admin/src/test/java/com/codenvy/api/user/server/UserServicePermissionsFilterTest.java
- dashboard/src/app/account/details/account-delete.controller.js
- dashboard/src/app/account/details/account-delete.html
- dashboard/src/components/api/codenvy-user.factory.js
> CODENVY-509: remove current user instead of sending email

- Vagrantfile
1. Added in the appropriate new proxy installation options.
2. Migrated some variables to be configurable
> Updated to support 4.4.x proxy installation

- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/ContributionExtension.java
Fixes plugin-pullrequest appearing on projects where it it available.
#458 
###Expected behavior:
Pull Request panel should be on its place.
###Observed behavior:
There is no Pull Request panel in the IDE.
No
None
> CODENVY-458; fix plugin pullrequest appearing;

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/3.13.4.4/codenvy-multi-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/3.13.4.4/codenvy-single-server.properties
- cdec/installation-manager-tests/src/main/resources/bin/test-backup-restore-single-node.sh
> (#407) fix codenvy 3.x integration tests

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/backup/MachineBackupManager.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/backup/MachineBackupManagerTest.java
Fixes bug in backup manager
Fixes #488 
Partially rewritten tests to improve stability and speed. Tests can look complicated, so further improvements are welcomed and can be added later.
> CODENVY-488: fix bug in backup manager, update tests

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.6.0/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.7.0-SNAPSHOT/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/patches/4.6.0/single_server/patch_before_update.sh
- cdec/installation-manager-resources/src/main/resources/patches/4.6.0/single_server/update_mongo.js
> (#496) add Codenvy on-prem 4.6.0 properies and migration script

- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
> fixup! (#404) validate options of Codenvy bootstrap script

- site/app/site/account-deleted.html
Create a new page to be displayed after user is deleted
> CODENVY-380 Create a page to be displayed after user is deleted

- cdec/installation-manager-cli-bundle/src/main/java/com/codenvy/im/cli/command/VersionCommand.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifact.java
@skabashnyuk: please, review this request.
> Fix tests to conform ErrorProne rules

- dashboard/src/app/factories/load-factory/load-factory.controller.js
> CHE-1369: rework UD to listen to environment channels

- cdec/installation-manager-cli-bundle/src/main/java/com/codenvy/im/cli/command/ConfigCommand.java
- cdec/installation-manager-cli-bundle/src/test/java/com/codenvy/im/cli/command/TestConfigCommand.java
> Add ability to store empty codenvy properties

- assembly/onpremises-ide-packaging-war-ext-server/pom.xml
Adapt to changes in Che
https://github.com/eclipse/che/issues/2033
> CHE-2033 Remove Che Git Provider module

- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/CDECArtifact.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECMultiServerHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECSingleServerHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/commands/CommandLibrary.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifact.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/commands/TestCommandLibrary.java
- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-add-remove-codenvy-nodes-with-codenvy4.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-install-single-node-and-change-config-with-codenvy4.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-setup-and-update-codenvy4-config.sh
- cdec/installation-manager-tests/src/main/resources/bin/install/test-install-multi-nodes-and-change-config.sh
- cdec/installation-manager-tests/src/main/resources/bin/install/test-install-single-node-and-change-config.sh
> (#464) update /etc/hosts when changing Codenvy hostname

- assembly/onpremises-ide-packaging-war-platform-api/pom.xml
- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
- plugins/plugin-hosted/codenvy-machine-hosted/pom.xml
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/auth/aws/ecr/AwsEcrAuthResolver.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/auth/aws/ecr/AwsInitialAuthConfig.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/auth/aws/ecr/AwsEcrAuthResolverTest.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/auth/aws/ecr/AwsInitialAuthConfigTest.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/backup/MachineBackupManagerTest.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/backup/WorkspaceFsBackupSchedulerTest.java
- pom.xml
Adds support of dynamic passwords for AWS ECR
#453 
No support of dynamic passwords for AWS ECR
Adds ability to create workspace from an image which is stored in AWS ECR
Yes
No
> CODENVY-453: Add support of AWS ECR dynamic passwords

- cdec/installation-manager-cli-bundle/src/main/java/com/codenvy/im/cli/command/AbstractIMCommand.java
- cdec/installation-manager-cli-bundle/src/test/java/com/codenvy/im/cli/command/TestDownloadCommand.java
- cdec/installation-manager-core/pom.xml
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/CDECArtifact.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECArtifactHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/ConfigManager.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/BaseTest.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifact.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifactGetInstalledVersion.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/LdapManagerCodenvy3Test.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/LdapManagerCodenvy4Test.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/TestConfigManager.java
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.6.1/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-add-remove-codenvy-nodes-with-codenvy4.sh
- cdec/installation-manager-tests/src/main/resources/bin/config.sh
- cdec/installation-manager-tests/src/main/resources/bin/install/test-install-im-cli.sh
- cdec/installation-manager-tests/src/main/resources/bin/lib.sh
- cdec/upload-installation-manager.sh
1. Rework checking if Codenvy API service is alive by using **curl** command instead of HttpTransport:request() method:
`curl -X OPTIONS {host_protocol}//:{host_url}/api/`
2. Fix bootstrap script message "Checking access to external dependencies...".
3. Fix IM error message "WARNING: automatic update of IM CLI client has been failed".
4. Fix deployment scripts and integration tests to use staging for deployment and testing.
> (#459) fix requesting to Codenvy API throught HTTPS

- plugins/plugin-bitbucket/codenvy-plugin-bitbucket-ext-bitbucket/src/main/java/org/eclipse/che/ide/ext/bitbucket/server/rest/BitbucketService.java
- plugins/plugin-bitbucket/codenvy-plugin-bitbucket-git-provider/src/main/java/org/eclipse/che/ide/ext/git/server/nativegit/BitbucketOAuthCredentialProvider.java
- plugins/plugin-microsoft/codenvy-plugin-microsoft-git-provider/src/main/java/org/eclipse/che/ide/ext/git/server/nativegit/MicrosoftOAuthCredentialsProvider.java
- plugins/plugin-projectlocker/codenvy-plugin-projectlocker-git-provider/src/main/java/org/eclipse/che/ide/ext/git/server/nativegit/ProjectLockerOAuthCredentialProvider.java
- plugins/plugin-wso2/codenvy-plugin-wso2-git-provider/src/main/java/org/eclipse/che/ide/ext/git/server/nativegit/WSO2OAuthCredentialsProvider.java
Fixes wrong GitException import way
> refactoring of GitException

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.6.2/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/patches/4.6.2/single_server/patch_before_update.sh
- cdec/installation-manager-resources/src/main/resources/patches/4.6.2/single_server/update_mongo.js
> Add default properties and migration script of Codenvy on-prem 4.6.2

- cdec/installation-manager-core/pom.xml
- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy-multi.sh
- cdec/installation-manager-resources/src/main/resources/im-scripts/install-im-cli.sh
- cdec/installation-manager-tests/src/main/resources/bin/config.sh
- cdec/patch-and-upload-codenvy-bundle.sh
- cdec/upload-installation-manager.sh
@riuvshin: please, review this changes.
> Installation manager

- cdec/patch-and-upload-codenvy-bundle.sh
- cdec/update.sh
> Fix update.sh to use updater.nightly4.codenvy-stg.com

- cdec/installation-manager-tests/src/main/resources/bin/config.sh
> Fix config of installation manager integration tests

- assembly/onpremises-ide-packaging-tomcat-api/src/assembly/assembly.xml
- assembly/onpremises-ide-packaging-tomcat-codenvy-allinone/src/assembly/assembly.xml
Set correct groupId for mail server so it can be picked up by assembly.
https://github.com/codenvy/codenvy/issues/550
No
> CODENVY-550 Fix mail server groupId

- pom.xml
- wsmaster/codenvy-hosted-api-jdbc-vendor-postgresql/pom.xml
- wsmaster/codenvy-hosted-api-jdbc-vendor-postgresql/src/main/java/org/eclipse/che/api/core/postgresql/jdbc/jpa/eclipselink/PostgreSqlExceptionHandler.java
- wsmaster/codenvy-hosted-api-workspace/pom.xml
- wsmaster/codenvy-integration-tck-jpa/pom.xml
- wsmaster/codenvy-integration-tck-jpa/src/test/java/com/codenvy/api/tck/JpaIntegrationTckModule.java
- wsmaster/codenvy-integration-tck-jpa/src/test/resources/META-INF/persistence.xml
- wsmaster/codenvy-integration-tck-jpa/src/test/resources/META-INF/services/org.eclipse.che.commons.test.tck.TckModule
- wsmaster/codenvy-integration-tck-jpa/src/test/resources/logback-test.xml
- wsmaster/pom.xml
Adds integration test module, where all DAOs are tested on PostgreSQL database.
https://github.com/codenvy/codenvy/issues/396
> Add integration tests for JPA DAOs on PostgreSQL database

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/3.13.4.4/codenvy-multi-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/3.13.4.4/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/3.14.1.1/codenvy-multi-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/3.14.1.1/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/3.14.2-SNAPSHOT/codenvy-multi-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/3.14.2-SNAPSHOT/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.6.1/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.6.2/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.7.0-SNAPSHOT/codenvy-single-server.properties
> (#547) fix zabbix admin name in default Codenvy on-prem properties

- cdec/installation-manager-tests/src/main/resources/bin/lib.sh
- cdec/installation-manager-tests/src/main/resources/vagrant/single-codenvy4-with-additional-nodes/RHEL7/Vagrantfile
- cdec/installation-manager-tests/src/main/resources/vagrant/single/RHEL7/Vagrantfile
> (#575) fix unregistering the RHEL system in IM integration tests

- assembly/onpremises-ide-packaging-war-ext-server/pom.xml
- pom.xml
Use correct groupId for 'wsagent-codenvy' artifact
> Fix codenvy wsagent groupId

- dashboard/src/app/factories/list-factories/list-factories.html
It fixes title in toolbar in list-factories view.
[https://github.com/eclipse/che/issues/1848](https://github.com/eclipse/che/issues/1848)
> CHE-1848: fix title in toolbar in list-factories view.

- assembly/onpremises-ide-packaging-war-ext-server/src/main/java/com/codenvy/ext/java/server/MachineModule.java
Add needed RPC components to the Guice binding
Fix starting ws-agent
> Add needed RPC components to the Guice binding

- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/backup/MachineBackupManagerTest.java
Removes all `sleep` methods in `MachineBackupManagerTest` 
#537 
Multithreaded tests use `sleep` for synchronization, which may cause tests fail in specific environment.
Long tests duration (2-3 seconds per test case).
No `sleep` methods in the tests.
No
> CODENVY-537: Rework MachineBackupManager multithreaded tests

- wsmaster/codenvy-hosted-api-admin/pom.xml
- wsmaster/codenvy-hosted-api-admin/src/main/java/com/codenvy/api/AdminApiModule.java
- wsmaster/codenvy-hosted-api-admin/src/main/java/com/codenvy/api/user/server/AdminUserCreator.java
- wsmaster/codenvy-hosted-api-admin/src/test/java/com/codenvy/api/user/server/AdminUserCreatorTest.java
Adds a component for admin user creation.
Yes
@skabashnyuk, @evoevodin please take a look
> Add Codenvy Admin User creator component

- pom.xml
Add terminal artifact to dependency management section
> Add terminal artifact to dependency management section

- wsmaster/codenvy-hosted-sso-server-organization/src/main/java/com/codenvy/auth/sso/server/OrgServiceUserCreator.java
> Do not add null profile attributes

- dashboard/src/app/factories/last-factories/last-factories.html
- dashboard/src/app/factories/last-factories/last-factories.styl
- dashboard/src/app/factories/list-factories/factory-item/factory-item.html
- dashboard/src/app/factories/list-factories/list-factories.html
This PR updates design for Dashboard page.
[https://github.com/eclipse/che/issues/2158](https://github.com/eclipse/che/issues/2158)
> CHE-2158: simplify boxes' design for Dashboard page

- dashboard/src/app/factories/list-factories/list-factories.html
Adds factory description widget
https://github.com/codenvy/codenvy/issues/613
References this PR: https://github.com/eclipse/che/pull/2210
> CODENVY-613: add factories page description

- dashboard/src/app/factories/list-factories/factory-item/factory-item.html
- dashboard/src/app/factories/list-factories/list-factories.html
Improve list of factories for UD
show url instead if no factory name
> improve list of factories for UD

- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
- cdec/installation-manager-tests/src/main/resources/bin/lib.sh
@benoitf, @riuvshin, @tolusha - please, review this request.
> (#479) add post-flight Codenvy on-prem installation check

- dashboard/src/app/factories/last-factories/last-factories.html
- dashboard/src/app/factories/last-factories/last-factories.styl
Fix the style of last factories empty label and rename Last Factories to Recent Factories.
> Fix empty factories message

- dashboard/src/app/factories/last-factories/last-factories.html
Add button "Create Factory" into "Recent Factories" panel.
> update dashboard view

- dashboard/src/app/navbar/codenvy-navbar.html
Remove the long-click/long-touch behaviour from the left navbar.
> remove che-long-touch behaviour in navbar

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.7.0/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.8.0-SNAPSHOT/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/patches/4.7.0/single_server/patch_before_update.sh
- cdec/installation-manager-resources/src/main/resources/patches/4.7.0/single_server/update_mongo.js
> Migration to 4.7.0

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedComposeMachineProviderImpl.java
- plugins/plugin-urlfactory/pom.xml
- plugins/plugin-urlfactory/src/main/java/com/codenvy/plugin/urlfactory/URLFactoryBuilder.java
- plugins/plugin-urlfactory/src/test/java/com/codenvy/plugin/urlfactory/URLFactoryBuilderTest.java
- wsmaster/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/dao/mongo/WorkspaceImplCodec.java
- wsmaster/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManager.java
- wsmaster/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/dao/mongo/MongoDBFactoryStoreTest.java
- wsmaster/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/dao/mongo/StackDaoImplTest.java
- wsmaster/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/dao/mongo/WorkspaceDaoImplTest.java
- wsmaster/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManagerTest.java
- wsmaster/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/workspace/TestObjects.java
Adds support of new single machine environment types.
> CHE-1818: add new WS environment types for single machine

- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
Enables support for old format of Factories/Stacks/Workspaces
@skabashnyuk, @garagatyi please review
> Enable support for old model objects adaptation

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/5.0.0-M1-SNAPSHOT/codenvy-single-server.properties
> Add codenvy properties for 5.0.0-M1-SNAPSHOT

- cdec/installation-manager-tests/src/main/resources/bin/config.sh
> Fix integration tests to work with Codenvy on-prem 5.x

- pom.xml
- wsmaster/codenvy-hosted-mail-server/pom.xml
- wsmaster/codenvy-hosted-mail-server/src/test/java/com/codenvy/mail/MailSenderTest.java
Used version of dumbster with correct startup implementation and port finder
Fixes https://github.com/codenvy/codenvy/issues/702
periodical deadlocks
no periodical deadlocks
Yes
> Used version of dumbster with correct startup implementation

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedComposeMachineProviderImpl.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/HostedComposeMachineProviderImplTest.java
Fix classes in accordance with changes in eclipse/che#2392
eclipse/che#2392
No
> CHE-2331: fix in accordance with changes in Che

- cdec/installation-manager-tests/src/main/resources/bin/config.sh
> (#701) fix regexp of recognition version to test

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/4.7.2/codenvy-single-server.properties
@riuvshin: please, review this changes.
> Add default properties for Codenvy on-prem 4.7.2

- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
- wsmaster/codenvy-hosted-api-machine/src/main/java/com/codenvy/api/machine/server/jpa/OnPremisesJpaMachineModule.java
- wsmaster/codenvy-hosted-api-machine/src/main/java/com/codenvy/api/machine/server/jpa/OnPremisesJpaRecipeDao.java
- wsmaster/codenvy-hosted-api-machine/src/main/java/com/codenvy/api/machine/server/recipe/OnPremisesRecipeLoader.java
- wsmaster/codenvy-hosted-api-machine/src/test/java/com/codenvy/api/machine/server/jpa/OnPremisesJpaRecipeDaoTest.java
- wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/model/impl/AbstractPermissions.java
- wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/jpa/OnPremisesJpaWorkspaceModule.java
- wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/model/impl/WorkerImpl.java
- wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/spi/jpa/OnPremisesJpaStackDao.java
- wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/spi/jpa/OnPremisesJpaWorkspaceDao.java
- wsmaster/codenvy-hosted-api-workspace/src/test/java/com/codenvy/api/workspace/server/jpa/OnPremisesJpaStackDaoTest.java
- wsmaster/codenvy-hosted-api-workspace/src/test/java/com/codenvy/api/workspace/server/jpa/OnPremisesJpaWorkspaceDaoTest.java
Adds permission-aware recipe and stack DAO.
> Codenvy 686 Rewrite the stack and recipe search in accordance with permissions mechanism

- wsmaster/codenvy-hosted-api-machine/src/main/java/com/codenvy/api/machine/server/recipe/RecipePermissionsImpl.java
- wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/model/impl/WorkerImpl.java
- wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/stack/StackPermissionsImpl.java
Add indexes to Workers, Recipe and Stack Permissions
@evoevodin @akorneta @skabashnyuk @mshaposhnik 
Please review my changes
> Add indexes to Workers, Recipe and Stack Permissions

- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
Add ability to mount extra volumes in Codenvy
> CODENVY-499: Ways to mount folder inside host machine to auxiliary machine

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/5.0.0-M1-SNAPSHOT/codenvy-single-server.properties
> (#730) fix codenvy on-prem property 'machine_server_extra_volume'

- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy/update/test-update-single-node-from-binary.sh
- cdec/installation-manager-tests/src/main/resources/bin/lib.sh
> (#617) remove redundant options --systemAdminName and --systemAdminPassword from bootstrap script

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/5.0.0-M1/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/5.0.0-M2-SNAPSHOT/codenvy-single-server.properties
> (#730) add codenvy on-prem 5.0.0-M1 properties

- wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/LdapConnectionFactoryProvider.java
- wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/LdapAuthenticatedSearchTest.java
- wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/LdapDirectBindTest.java
- wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/MyLdapServer.java
Fixed bug. binddn and credentials are not worked before. Disabled anonymous access in tests
> Fixed bug bind users

- cdec/installation-manager-resources/src/main/resources/patches/5.0.0-M1/single_server/patch_before_update.sh
Fix migration of codenvy licenses stored with comments and line breaks.
@AndrienkoAleksandr: please, review this request.
> (#730) fix migration of codenvy license

- wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/LdapConfiguration.java
- wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/LdapConfigurationBuilder.java
Mark providerClass as connection config parameter
> Mark providerClass as connection config parameter

- pom.xml
- wsmaster/codenvy-ldap/pom.xml
- wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/LdapModule.java
- wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/LdapEntrySelector.java
- wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/LdapEntrySelectorProvider.java
- wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/LdapSynchronizer.java
- wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/LdapSynchronizerService.java
- wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/LookupSelector.java
- wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/MembershipSelector.java
- wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/ProfileMapper.java
- wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/SyncException.java
- wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/UserMapper.java
- wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/LdapAuthenticatedSearchTest.java
- wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/LdapDirectBindTest.java
- wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/MyLdapServer.java
- wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/TestConnectionFactoryProvider.java
- wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/sync/LdapSynchronizationFlowTest.java
- wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/sync/LdapSynchronizerTest.java
- wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/sync/LookupSelectorTest.java
- wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/sync/MembershipSelectorTest.java
- wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/sync/ProfileMapperTest.java
- wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/sync/UserMapperTest.java
- wsmaster/codenvy-ldap/src/test/resources/META-INF/persistence.xml
- wsmaster/pom.xml
Adds Users/Profiles synchronizer from ldap to database
Yes
It'd be nice to provide a documentation for ldap synchronization parameters
and authentication types.
@skabashnyuk, @mshaposhnik wdyt?
> Add users/profiles synchronizer

- pom.xml
- wsmaster/codenvy-hosted-api-admin/pom.xml
- wsmaster/codenvy-hosted-api-admin/src/main/java/com/codenvy/api/user/server/AdminUserCreator.java
- wsmaster/codenvy-hosted-api-admin/src/test/java/com/codenvy/api/user/server/AdminUserCreatorTest.java
- wsmaster/codenvy-hosted-api-machine/pom.xml
- wsmaster/codenvy-hosted-api-machine/src/test/java/com/codenvy/api/machine/server/jpa/JpaRecipePermissionsDaoTest.java
- wsmaster/codenvy-hosted-api-machine/src/test/java/com/codenvy/api/machine/server/jpa/OnPremisesJpaRecipeDaoTest.java
- wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/jpa/AbstractJpaPermissionsDao.java
- wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/jpa/JpaSystemPermissionsDao.java
- wsmaster/codenvy-hosted-api-workspace/src/test/java/com/codenvy/api/workspace/server/jpa/JpaStackPermissionsDaoTest.java
- wsmaster/codenvy-hosted-api-workspace/src/test/java/com/codenvy/api/workspace/server/jpa/OnPremisesJpaStackDaoTest.java
- wsmaster/codenvy-hosted-api-workspace/src/test/java/com/codenvy/api/workspace/server/jpa/OnPremisesJpaWorkspaceDaoTest.java
- wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/auth/LdapAuthenticationHandler.java
- wsmaster/pom.xml
Remove this section if not relevant
This content may also be included in the release notes.
Yes/No
1.  API changes  
2.  User docs changes
> Add admin user creator for ldap

- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/helper/NodeManagerHelperCodenvy4Impl.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/utils/HttpTransport.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/helper/TestNodeManagerHelperCodenvy4Impl.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/utils/TestHttpTransport.java
Fix adding node behind the proxy for default host name
No
1.  API changes  
2.  User docs changes  
> CODENVY-734: Fix adding node behind the proxy for default host name

- dashboard/gulp/build.js
- dashboard/src/app/admin/user-management/user-management.html
- dashboard/src/app/admin/user-management/user-management.styl
- dashboard/src/app/factories/factory-details/factory-details.controller.js
- dashboard/src/app/factories/factory-details/factory-details.html
- dashboard/src/app/factories/factory-details/information-tab/factory-information/factory-information.controller.js
- dashboard/src/app/factories/factory-details/information-tab/factory-information/factory-information.html
- dashboard/src/app/factories/factory-details/information-tab/factory-information/factory-information.styl
- dashboard/src/app/factories/last-factories/last-factories.controller.js
- dashboard/src/app/factories/list-factories/factory-item/factory-item.controller.js
- dashboard/src/app/factories/list-factories/factory-item/factory-item.html
- dashboard/src/app/factories/list-factories/list-factories.controller.js
- dashboard/src/app/factories/list-factories/list-factories.html
- dashboard/src/app/factories/load-factory/load-factory.controller.js
- dashboard/src/app/index.module.js
- dashboard/src/app/index.styl
- dashboard/src/app/navbar/navbar.controller.js
- dashboard/src/app/onprem/license-nag-message-management/nag-message.controller.js
- dashboard/src/app/workspace/share-workspace/user-item/user-item.html
- dashboard/src/app/workspace/share-workspace/user-item/user-item.styl
- dashboard/src/components/api/builder/codenvy-api-builder.factory.js
- dashboard/src/components/api/builder/codenvy-factory-builder.js
- dashboard/src/components/api/codenvy-factory.factory.js
- dashboard/src/components/api/codenvy-factory.spec.js
- dashboard/src/components/api/codenvy-user.factory.js
- dashboard/src/components/api/test/codenvy-http-backend.js
- dashboard/src/components/ims/ims-license.factory.js
Adds  paging for factory list for UD.
https://github.com/eclipse/che/issues/1922
> CHE-1922 add paging for factory list

- cdec/installation-manager-tests/src/main/resources/bin/codenvy/backup/test-backup-restore-single-node.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy/install/test-install-single-node-behind-the-proxy.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy/node/test-add-remove-codenvy-nodes.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy/test-version.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy/update/test-update-single-node.sh
> fix IM CLI integration tests

- dashboard/bower.json
This PR adds new dependency.
[https://github.com/eclipse/che/issues/1772](https://github.com/eclipse/che/issues/1772) Add Environment variables in the workspace configuration
[https://github.com/eclipse/che/issues/1918](https://github.com/eclipse/che/issues/1918) Allow for changes to workspace RAM to existing workspace 
> CHE-1772: add dependency

- dashboard/src/app/factories/factory-details/information-tab/factory-information/factory-information.controller.js
- dashboard/src/app/factories/last-factories/last-factories.controller.js
- dashboard/src/app/factories/list-factories/factory-item/factory-item.controller.js
- dashboard/src/app/factories/list-factories/factory-item/factory-item.html
- dashboard/src/app/workspace/share-workspace/share-workspace.controller.js
Fixes the bugs connected with factories listing and model changes.
https://github.com/codenvy/codenvy/issues/725
https://github.com/codenvy/codenvy/issues/766
https://github.com/codenvy/codenvy/issues/767
> Dashboard bug fixes

- wsmaster/codenvy-hosted-api-license/src/main/java/com/codenvy/api/license/server/CodenvyLicenseManager.java
- wsmaster/codenvy-hosted-api-license/src/test/java/com/codenvy/api/license/server/CodenvyLicenseManagerTest.java
- wsmaster/codenvy-hosted-report/src/main/java/com/codenvy/report/ReportSender.java
- wsmaster/codenvy-hosted-report/src/test/java/com/codenvy/report/ReportSenderTest.java
Use new method to get amount of users in the CodenvyLicenseManager
None. This code improve.
Yes
1.  API changes  
2.  User docs changes  
@dmytro-ndp review please.
> Use new method to get amount of users in the CodenvyLicenseManager

- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
added missing binding
@skabashnyuk, @evoevodin please take a look
> Add FactoryModule binding

- dashboard/src/app/factories/factory-details/factory-details.controller.js
- dashboard/src/app/factories/factory-details/factory-details.html
- dashboard/src/app/factories/factory-details/information-tab/factory-information/factory-information.controller.js
- dashboard/src/app/factories/factory-details/information-tab/factory-information/factory-information.html
- dashboard/src/components/api/codenvy-factory.factory.js
Fixes the accept factory links retrieval, based on name and id. Fixes open factory and display links in factory details page.
https://github.com/codenvy/codenvy/issues/766
> CODENVY-766: fix factory id and named links retrieval

- plugins/plugin-urlfactory/pom.xml
- plugins/plugin-urlfactory/src/main/java/com/codenvy/plugin/urlfactory/URLFactoryBuilder.java
- plugins/plugin-urlfactory/src/test/java/com/codenvy/plugin/urlfactory/URLFactoryBuilderTest.java
Adapts factories in old format to a new one, when downloading them directly.
partly fixes #779 
> Adapt downloaded factories

- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedMachineProviderImpl.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/HostedMachineProviderImplTest.java
- wsmaster/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManager.java
- wsmaster/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/workspace/TestObjects.java
Adapt Codenvy to changes eclipse/che#2487
Related to eclipse/che#2487
No
1.  ~~API changes~~
2.  ~~User docs changes~~
> CHE-2366: Fix volumes_from usage in compose environment

- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/backup/WorkspaceFsBackupSchedulerTest.java
Fix WorkspaceFsBackupSchedulerTest.shouldBackupOtherWorkspacesIfBackupOfPreviousFails test
#601 
The test falls sometimes
> CODENVY-601: fix WorkspaceFsBackupSchedulerTest

- wsmaster/codenvy-hosted-integration-tests/codenvy-integration-jpa-dao/pom.xml
- wsmaster/codenvy-hosted-integration-tests/codenvy-integration-jpa-dao/src/test/java/WaitConnectionListener.java
- wsmaster/codenvy-hosted-integration-tests/codenvy-integration-jpa-dao/src/test/resources/META-INF/persistence.xml
- wsmaster/codenvy-hosted-integration-tests/codenvy-integration-jpa-dao/src/test/resources/META-INF/services/org.testng.ITestNGListener
- wsmaster/codenvy-hosted-integration-tests/codenvy-integration-tck-jpa/pom.xml
- wsmaster/codenvy-hosted-integration-tests/codenvy-integration-tck-jpa/src/test/java/com/codenvy/api/tck/JpaIntegrationTckModule.java
Fixes integration tests.
Adds connection checks before running tests.
> Fix integration tests

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/5.0.0-M2/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/5.0.0-M3-SNAPSHOT/codenvy-single-server.properties
> Add default properties for codenvy on-prem 5.0.0-M2

- cdec/installation-manager-tests/src/main/resources/vagrant/single-with-additional-nodes/RHEL7/Vagrantfile
Fix Vagrantfile for IM CLI integration tests.
> (#456) fix Vagrantfile for RHEL OS

- dashboard/src/app/navbar/codenvy-navbar.html
- dashboard/src/components/api/codenvy-api-config.js
- dashboard/src/components/api/codenvy-api.factory.js
- dashboard/src/components/api/codenvy-system.factory.js
Displays system ram limit notifications.
https://github.com/codenvy/codenvy/issues/502
PR depends on https://github.com/eclipse/che/pull/2529
> CODENVY-502: check system ram limit channel to handle app notifications

- dashboard/gulp/build.js
Add build task for ngClipProvider source.
#808 
> CODENVY-808 fix add build task for ngClipProvider source

- dashboard/src/app/factories/create-factory/create-factory.controller.js
- dashboard/src/app/factories/create-factory/create-factory.html
Fix state of create factory button
#637 
> CODENVY-637 fix state of create factory button for UD

- dashboard/pom.xml
Fix name of the typescript file which is not anymore index.module.js
> [dashboard] Fix name of the index file

- dashboard/src/app/factories/create-factory/config-file-tab/factory-from-file.directive.ts
- dashboard/src/app/factories/create-factory/template-tab/factory-from-template.controller.ts
- dashboard/src/app/factories/create-factory/template-tab/factory-from-template.html
- dashboard/src/app/factories/create-factory/template-tab/factory-from-template.styl
- dashboard/src/app/factories/create-factory/workspaces-tab/factory-from-workpsace.controller.ts
Fixes factory creation by uploading config file and improve message when creating factory from workspace without projects. Adds editor on factory creation from template page.
https://github.com/codenvy/codenvy/issues/819
https://github.com/codenvy/codenvy/issues/820
https://github.com/codenvy/codenvy/issues/821
> Factory fixes

- dashboard/src/app/workspace/share-workspace/share-workspace.controller.ts
Fixes worskpace sharing.
https://github.com/codenvy/codenvy/issues/836
> CODENVY-836: fix sharing workspace

- wsmaster/codenvy-hosted-api-machine/pom.xml
- wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/WorkspaceApiModule.java
- wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/stack/StackCreatorPermissionsProvider.java
- wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/stack/StackDomain.java
- wsmaster/codenvy-hosted-api-workspace/src/test/java/com/codenvy/api/workspace/server/stack/StackCreatorPermissionsProviderTest.java
- wsmaster/codenvy-hosted-integration-tests/codenvy-integration-tck-jpa/pom.xml
Grants permissions for user who creates stack.
#795 
Yes
Merge depends on [this](https://github.com/eclipse/che/pull/2582) pull request.
@skabashnyuk, @sleshchenko please review
> Grant all permissions for user who creates stack

- wsmaster/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManager.java
Fix the NPE for cases when in environments field there is another Map implementation e.g hash-table.
#850 
@skabashnyuk please take a look.
> Fix NPE on getting environment by name

- assembly/onpremises-ide-packaging-war-factory/pom.xml
- assembly/onpremises-ide-packaging-war-platform-api/pom.xml
- assembly/onpremises-ide-packaging-war-website-codenvy/pom.xml
- pom.xml
- site/pom.xml
- wsmaster/codenvy-hosted-api-machine/pom.xml
- wsmaster/codenvy-hosted-integration-tests/codenvy-integration-tck-jpa/pom.xml
Rename group ID for site
https://github.com/codenvy/codenvy/issues/741
> CODENVY-741 rename group id for site

- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECSingleServerHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/BackupConfig.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/BackupManager.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/Config.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/utils/Version.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifact.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/utils/TestVersion.java
- cdec/installation-manager-tests/src/main/resources/bin/codenvy/backup/test-backup-restore-single-node.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy/install/test-install-single-node-behind-the-proxy.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy/update/test-update-single-node.sh
> (#465) Support PostgreSQL when performing backup/restore

- dashboard/src/app/index.module.ts
- dashboard/src/index.html
Improve IDE iframe injection
Depends on https://github.com/eclipse/che/pull/2578
Signed-off-by: Oleksii Orel oorel@codenvy.com
> Iframe injection

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedServersInstanceRuntimeInfo.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/UriTemplateServerProxyTransformer.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/HostedServersInstanceRuntimeInfoTest.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/UriTemplateServerProxyTransformerTest.java
Changes Codenvy in accordance with changes in Che
> CHE-2402: fix in accordance with changes in Che

- dashboard/src/assets/branding/loader.svg
- dashboard/src/assets/branding/product.json
- dashboard/src/index.html
Loader Improving (it changed loader widget content and its styles).
https://github.com/eclipse/che/issues/1754
> CHE-1754: improve loader

- dashboard/src/app/workspace/share-workspace/add-members/add-members.html
- dashboard/src/app/workspace/share-workspace/add-members/add-members.styl
- dashboard/src/app/workspace/share-workspace/share-workspace.html
Changes captions in add member widget in workspace sharing.
https://github.com/codenvy/codenvy/issues/775
> CODENVY-775: renamings in workspace sharing widget

- dashboard/src/app/admin/user-management/user-management.html
- dashboard/src/app/factories/create-factory/create-factory.html
- dashboard/src/app/factories/factory-details/information-tab/factory-information/factory-information.html
- dashboard/src/app/factories/list-factories/list-factories.html
- dashboard/src/app/workspace/share-workspace/share-workspace.html
Fix grammar and typo errors.
https://github.com/codenvy/codenvy/issues/774
> CODENVY-774: fix grammar and typo errors

- wsmaster/codenvy-hosted-machine-authentication/src/main/java/com/codenvy/machine/authentication/server/WorkspaceServiceAuthLinksInjector.java
Inject machines links
#1929
No
@akorneta please review
Signed-off-by: Roman Nikitenko <rnikitenko@codenvy.com>
> CHE-1929. Inject machines links

- cdec/installation-manager-resources/src/main/resources/patches/5.0.0-M4/single_server/patch_before_update.sh
Uncomment row with command to execute jpa-migration-tool.
> fix migration script

- wsmaster/codenvy-ldap/pom.xml
- wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/auth/AuthenticatorProvider.java
- wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/LdapSynchronizer.java
- wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/ProfileMapper.java
- wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/UserMapper.java
Prevents some NPE's or unexpected behavior when not all required LDAP properties are set by
throwing appropriate exceptions in those cases.
> More accurate ldap configuration properties validation

- pom.xml
Changes the current version of PostgreSQL driver on latest.
| Tests     |  Failures   | Skipped | Success Rate |
|:----------|:------------|:--------|:-------------|
| 322       | 53          | 1       | 83.23%       |
@skabashnyuk please take a look.
> Set the next version of postgresql driver

- cdec/installation-manager-cli-bundle/src/main/java/com/codenvy/im/cli/command/InstallCommand.java
- cdec/installation-manager-cli-bundle/src/test/java/com/codenvy/im/cli/command/AbstractTestCommand.java
- cdec/installation-manager-cli-bundle/src/test/java/com/codenvy/im/cli/command/TestInstallCommand.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECMultiServerHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECSingleServerHelper.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/commands/CommandLibrary.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/commands/PatchCDECCommand.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/console/Console.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/ConfigManager.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/utils/InjectorBootstrap.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifact.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/commands/TestCommandLibrary.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/console/TestConsole.java
- cdec/installation-manager-resources/src/main/resources/patches/5.0.0-M4/single_server/patch_before_update.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy/test-setup-and-update-codenvy-config.sh
> (#865) display update info in the IM CLI install command output

- wsmaster/codenvy-ldap/README.md
> Documentation fixes

- wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/LdapSynchronizer.java
Fixes NPE on profile if ID attribute is wrong
> Fix ldap migration

- cdec/installation-manager-resources/src/main/resources/patches/5.0.0-M1/single_server/patch_before_update.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy/node/test-add-remove-codenvy-nodes.sh
- cdec/installation-manager-tests/src/test/java/com/codenvy/im/TestInstallationManagerCliWithCodenvy3.java
- cdec/installation-manager-tests/src/test/resources/MainSuite.xml
1) fixes patch before update to Codenvy on-prem 5.0.0-M1
2) fixes integration test of Im CLI "test-add-remove-codenvy-nodes"
3) turns on testing of Codenvy on-prem 3.x 
> Small fixup of IM CLI

- plugins/plugin-hosted/codenvy-hosted-ext-factory/src/main/java/com/codenvy/ide/factory/client/utils/FactoryProjectImporter.java
1. Сache svn credentials instead storing them in credentials provider
2. Show dialog on remote svn operations that require authentication
https://github.com/codenvy/codenvy/issues/687
No
@vparfonov please review
> CODENVY-687: Сache svn credentials instead of storing them in credentials provider

- assembly/onpremises-ide-compiling-war-ide/pom.xml
- assembly/onpremises-ide-compiling-war-ide/src/main/resources/com/codenvy/ide/IDE.gwt.xml
- assembly/onpremises-ide-packaging-war-ext-server/pom.xml
Add PHP plugin to the dependency 
#879 
@skabashnyuk @riuvshin
> CODENVY-879: add PHP plugins to the deps

- wsmaster/codenvy-hosted-api-machine/src/main/java/com/codenvy/api/machine/server/recipe/RecipePermissionsImpl.java
Fix recipe permission getByUserId query
#905  
@skabashnyuk, @evoevodin please take a look.
> CODENVY-905: Fix recipe permission getByUserId query

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/5.0.0-M5-SNAPSHOT/codenvy-single-server.properties
- cdec/installation-manager-tests/src/test/java/com/codenvy/im/TestInstallationManagerCliWithCodenvy3.java
1) fix version of Codenvy on-prem 5.0.0-M5-SNAPSHOT default property
2) fix list of Codenvy on-prem 3.x tests to don't test previous version 3.12.5.2 which is hanging up on install.
> Minor fix of IM CLI

- cdec/installation-manager-tests/src/main/resources/bin/codenvy/test-login.sh
> Add integration test of login command of IM CLI

- wsmaster/codenvy-hosted-api-machine/src/main/java/com/codenvy/api/machine/server/jpa/OnPremisesJpaRecipeDao.java
- wsmaster/codenvy-hosted-api-machine/src/main/java/com/codenvy/api/machine/server/recipe/RecipeCreatorPermissionsProvider.java
- wsmaster/codenvy-hosted-api-machine/src/main/java/com/codenvy/api/machine/server/recipe/RecipeDomain.java
- wsmaster/codenvy-hosted-api-machine/src/test/java/com/codenvy/api/machine/server/jpa/OnPremisesJpaRecipeDaoTest.java
- wsmaster/codenvy-hosted-api-machine/src/test/java/com/codenvy/api/machine/server/recipe/RecipeCreatorPermissionsProviderTest.java
- wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/WorkspaceApiModule.java
Fix recipe permission search query and recipe permission provider.
#909 
Yes
@skabashnyuk , @evoevodin, @mshaposhnik please take a look
> Fix recipe search query and  add provider for recipe permission

- wsmaster/codenvy-ldap/README.md
LDAP docs improvement regarding SSL and SASL
> Ldap docs improvement

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/5.0.0-M5/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/5.0.0-M6-SNAPSHOT/codenvy-single-server.properties
> Add default properties for Codenvy on-prem 5.0.0-M5

- cdec/installation-manager-tests/src/main/resources/bin/codenvy/backup/test-backup-restore-single-node.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy/install/test-install-single-node-behind-the-proxy.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy/update/test-update-single-node.sh
> Fix Codenvy project creation in integration tests of IM CLI

- cdec/installation-manager-core/src/main/java/com/codenvy/im/commands/CommandLibrary.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifact.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/commands/TestCommandLibrary.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/TestBackupConfig.java
1) fixes unit tests of bakup/restore Codenvy on-prem
2) fixes pack/unpack commands 
> Fix unit tests of backup/restore functions of installation manager

- wsmaster/codenvy-hosted-api-machine/pom.xml
- wsmaster/codenvy-hosted-api-machine/src/main/java/com/codenvy/api/machine/server/jpa/JpaRecipePermissionsDao.java
- wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/event/BeforeOrganizationRemovedEvent.java
- wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/spi/jpa/JpaMemberDao.java
- wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/spi/jpa/OrganizationEntityListener.java
- wsmaster/codenvy-hosted-api-organization/src/test/java/com/codenvy/organization/spi/jpa/RemoveMembersBeforeOrganizationRemovedEventSubscriberTest.java
- wsmaster/codenvy-hosted-api-permission/pom.xml
- wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/jpa/JpaSystemPermissionsDao.java
- wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/jpa/listener/RemovePermissionsOnLastUserRemovedEventSubscriber.java
- wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/spi/jpa/JpaStackPermissionsDao.java
- wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/spi/jpa/JpaWorkerDao.java
- wsmaster/codenvy-hosted-integration-tests/codenvy-integration-cascade-jpa/src/test/java/com/codenvy/integration/jpa/cascaderemoval/JpaEntitiesCascadeRemovalTest.java
Fix tests and components that needed for cascade removing.
[this one](https://github.com/eclipse/che/issues/2438)
@skabashnyuk, @evoevodin please take a look.
> Fix test and components related to cascade remove

- pom.xml
> Sort parent pom.xml

- cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy/backup/test-backup-restore-single-node.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy/install/test-install-single-node-behind-the-proxy.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy/node/test-add-remove-codenvy-nodes.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy/test-login.sh
This request resolves the issue #922 
> Handle absence of 'eth0' network interface by bootstrap script

- wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/permissions/OrganizationDomain.java
Add missed set permissions action to organization domain
> Add missed set permissions action to organization domain

- wsmaster/codenvy-hosted-api-audit/src/main/java/com/codenvy/api/audit/server/AuditManager.java
- wsmaster/codenvy-hosted-api-audit/src/test/java/com/codenvy/api/audit/server/AuditManagerTest.java
Fix usage of org.eclipse.che.api.core.Page after changes following https://github.com/eclipse/che/commit/3df78186c4f511f2ba17965824b06d2966309cf2
> Fix usage of page

- cdec/installation-manager-tests/src/main/resources/bin/codenvy/audit/test-audit.sh
- cdec/installation-manager-tests/src/test/java/com/codenvy/im/TestInstallationManagerCliWithCodenvy.java
> Merge integration test of login command into the test of audit command

- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/ContributionExtension.java
- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/inject/PullRequestGinModule.java
- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/parts/contribute/ContributePartPresenter.java
Fixes plugin-pullrequest initialization, prevents PR flow failures, appearing of empty and/or duplicate panels.
Fixes #906   #910
> CODENVY-906; fix plugin pullrequest presenter initialization

- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/resources/com/codenvy/plugin/pullrequest/PullRequest.gwt.xml
Remove not needed GWT modules declaration
> Remove not needed GWT modules declaration

- cdec/installation-manager-cli-bundle/src/test/java/com/codenvy/im/cli/command/TestAuditCommand.java
Fix TestAuditCommand test
@dmytro-ndp please review
> Fix TestAuditCommand test

- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/backup/MachineBackupManager.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/workspace/WorkspaceFilesCleanUpScriptExecutor.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/workspace/WorkspaceFilesCleanUpScriptExecutorTest.java
- wsmaster/codenvy-hosted-machine-authentication/src/test/java/com/codenvy/machine/authentication/server/interceptor/MachineTokenInterceptorTest.java
Add component for clean up workspace folder after remove workspace.
https://github.com/eclipse/che/issues/2435
Yes/No
1.  API changes  
2.  User docs changes  
@garagatyi  review please.
> CHE-2435: Add component for clean up workspace folder after remove workspace.

- cdec/installation-manager-cli-bundle/src/main/java/com/codenvy/im/cli/command/AuditCommand.java
- cdec/installation-manager-cli-bundle/src/test/java/com/codenvy/im/cli/command/TestAuditCommand.java
- cdec/installation-manager-core/src/main/java/com/codenvy/im/utils/HttpTransport.java
Improvements for IM Audit command and related test.
Small fix in `HttpTransport` class.
@dmytro-ndp @tolusha Please review
> IM Audit command and test improvements

- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/parts/contribute/ContributePartPresenter.java
- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/workflow/Context.java
Displays "Pull request created" if it was created at first or "Pull request updated" if it was updated
https://github.com/codenvy/codenvy/issues/514
"Pull request updated" was shown, even if it was created at first
> CODENVY-518: Fix pull request created message

- wsmaster/codenvy-hosted-api-workspace/src/test/java/com/codenvy/api/workspace/server/filters/WorkspacePermissionsFilterTest.java
Adapts tests.
[2683](https://github.com/eclipse/che/issues/2683)
> Adapt tests to WorkspaceService#stop REST method

- dashboard/bower.json
> Fix codemirror version

- wsmaster/codenvy-hosted-api-machine/src/main/java/com/codenvy/api/machine/server/recipe/RecipeDomain.java
- wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/stack/StackDomain.java
Add missed setPermissions allowed actions for stack and recipe domains
@skabashnyuk @evoevodin @akorneta Please review my changes
> Add missed setPermissions allowed actions for stack and recipe domains

- cdec/installation-manager-tests/src/main/resources/bin/codenvy/install/test-install-single-node-behind-the-proxy.sh
- cdec/installation-manager-tests/src/main/resources/bin/config.sh
It fixes addresses of proxy servers which are aimed for integration testing of IM CLI.
> Change addresses of test proxies for integration tests of IM CLI

- site/app/site/scripts/models/account.js
https://github.com/codenvy/codenvy/issues/992
> CODENVY-992 turn email, username to lowercase on login

- wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/LdapConnectionFactoryProvider.java
Adds connections passivator to prevent badly bind connections to return to the pool;
Fixes #1015 
After incorrect login, the connection can be returned to the pool causing further interchange to fail.
All connections are passivated - returned to their default state before became passive.
> Add connections passivator to prevent badly bind connections to return to the pool;

- wsmaster/codenvy-hosted-api-audit/src/main/java/com/codenvy/api/audit/server/AuditManager.java
Removes unnecessary cast in AuditManager according to https://github.com/eclipse/che/pull/2743 
https://github.com/eclipse/che/issues/2524
> CHE-2524: Remove unnecessary cast in AuditManager

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/5.0.0-M6/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/5.0.0-M7-SNAPSHOT/codenvy-single-server.properties
> Create default codenvy properties for Codenvy on-prem 5.0.0-M6

- cdec/installation-manager-core/pom.xml
> Fix address of Staging Update Server to updater.codenvy-stg.com

- assembly/onpremises-ide-compiling-war-ide/pom.xml
add maven plugin to generate GWT dyna provider implementation
#2459
> #2459 add maven plugin to generate GWT dyna provider implementation

- site/app/site/scripts/views/forgotpasswordform.js
- site/app/site/scripts/views/login.js
This PR related to https://github.com/codenvy/codenvy/issues/1058 issue
> CODENVY-1058 update property name

- assembly/onpremises-ide-compiling-war-ide/pom.xml
- assembly/onpremises-ide-compiling-war-ide/src/main/resources/com/codenvy/ide/IDE.gwt.xml
- assembly/onpremises-ide-packaging-war-ext-server/pom.xml
Add LS, JSON and C# Plugins to Codenvy
#847
Signed-off-by: Vitalii Parfonov vparfonov@codenvy.com
> Add LS, JSON and C# Plugins to Codenvy

- cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/Config.java
- cdec/installation-manager-core/src/test/java/com/codenvy/im/utils/TestInjectorBootstrap.java
- cdec/update-server-packaging-war/src/main/resources/codenvy/update-server.properties
Restore property names which commit 8697852d744af1cf546011ae29f47485b6d6537a had broken.
> Restore properties names

- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/vcs/GitVcsService.java
Adopt changes according to git refactoring
https://github.com/eclipse/che/pull/1515
> Changes according to git refactoring

- wsmaster/codenvy-hosted-api-resource/src/main/java/com/codenvy/resource/api/ram/WorkspaceRamConsumer.java
Fix ClassCastException during starting workspace from config
No
@skabashnyuk please review my changes
> Fix ClassCastException during starting workspace from config

- cdec/installation-manager-tests/src/main/resources/bin/codenvy/install/test-install-single-node-and-update-codenvy-config.sh
> Replace api.enpoint on che.api in IM integration tests

- cdec/installation-manager-resources/src/main/resources/codenvy-properties/5.0.0-M7/codenvy-single-server.properties
- cdec/installation-manager-resources/src/main/resources/codenvy-properties/5.0.0-M8-SNAPSHOT/codenvy-single-server.properties
> Prepare default codenvy properties to release Codenvy on-prem 5.0.0-M7

- cdec/installation-manager-tests/src/main/resources/bin/codenvy/install/test-install-single-node-and-update-codenvy-config.sh
It fixes integration test of install Codenvy on-prem AIO "test-install-single-node-and-update-codenvy-config.sh".
> Fix integration test of install Codenvy on-prem AIO and update its config

- codenvy.sh
- docs/CLI.md
- docs/README.md
- manifests/codenvy.pp
- version/5.0.0-M1/images
- version/5.0.0-M2/images
- version/5.0.0-M3/images
- version/5.1.0/images
- version/latest/images
- version/nightly/images
Merge docker branch into master.
Port changes from docker branch that weren't added on main merge.
> Add small fixes

- codenvy.sh
Add checking for docker client/server & API version
> Docker version check

- dockerfiles/cli/cli.sh
- dockerfiles/cli/codenvy.sh
> fix backup and restore commands

- dockerfiles/cli/cli.sh
> fix cli restart

- dockerfiles/cli/cli.sh
Adds method for upgrading codenvy
Fixes #1033
> Prototype of upgrade method

- dockerfiles/cli/cli.sh
- dockerfiles/cli/codenvy.sh
During the 'init' phase of running the Codenvy CLI, we ask the user to accept the Fair Source 3 license hosted on Codenvy's Web site.
Also, per requests, cleaned up some of the log management to remove unnecessary printf statements.
@riuvshin @benoitf
> Add Codenvy License Acceptance to Docker Installer

- dockerfiles/cli/Dockerfile
- dockerfiles/cli/cli.sh
- dockerfiles/cli/codenvy.sh
> fix license accept, remove cli logs from instance folder

- modules/codenvy/templates/machine.properties.erb
add missing props
@garagatyi @skabashnyuk
> add missing props

- dockerfiles/cli/version/5.0.0-M1/images
- dockerfiles/cli/version/5.0.0-M2/images
- dockerfiles/cli/version/5.0.0-M3/images
- dockerfiles/cli/version/latest/images
- dockerfiles/cli/version/nightly/images
- dockerfiles/socat/Dockerfile
@TylerJewell @skabashnyuk @garagatyi
> use tags for socat and puppet images

- dockerfiles/cli/cmd_init.sh
- dockerfiles/cli/cmd_upgrade.sh
Fix syntax errors in upgrade command
> Syntax fixups for uprgade

- cdec/installation-manager-tests/src/main/resources/bin/codenvy/backup/test-backup-restore-single-node.sh
- cdec/installation-manager-tests/src/main/resources/bin/codenvy/install/test-install-single-node-behind-the-proxy.sh
> Fix url of project creation API in integration tests of IM CLI

- modules/codenvy/templates/general.properties.erb
- modules/compose/templates/docker-compose-container.yml.erb
- modules/compose/templates/docker-compose.yml.erb
> add missing props, allow connect to postgres from host in dev mode

- assembly/onpremises-ide-packaging-war-ext-server/src/main/java/com/codenvy/ext/java/server/CodenvyWebSocketEndpoint.java
- assembly/onpremises-ide-packaging-war-ext-server/src/main/java/com/codenvy/ext/java/server/MachineModule.java
Related to https://github.com/eclipse/che/pull/3143
> Json RPC and websocket architecture reorganization

- dockerfiles/init/modules/compose/templates/docker-compose-container.yml.erb
- dockerfiles/init/modules/registry/manifests/init.pp
- dockerfiles/init/modules/registry/templates/config.yml.erb
needed for https://github.com/codenvy/codenvy/issues/1227
* add docker registry configuration
@skabashnyuk @TylerJewell @benoitf
> add registry configuration

- assembly/onpremises-ide-packaging-war-platform-api/src/main/resources/META-INF/persistence.xml
This must be done by the #1161 pr.
> Remove ddl schema generation from persistence.xml

- wsmaster/codenvy-hosted-api-machine/src/main/java/com/codenvy/api/machine/server/jpa/JpaRecipePermissionsDao.java
- wsmaster/codenvy-hosted-api-machine/src/test/java/com/codenvy/api/machine/server/jpa/JpaRecipePermissionsDaoTest.java
- wsmaster/codenvy-hosted-api-machine/src/test/java/com/codenvy/api/machine/server/spi/tck/RecipePermissionsDaoTest.java
- wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/spi/impl/MemberImpl.java
- wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/spi/jpa/JpaMemberDao.java
- wsmaster/codenvy-hosted-api-organization/src/test/java/com/codenvy/organization/spi/tck/MemberDaoTest.java
- wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/jpa/AbstractJpaPermissionsDao.java
- wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/jpa/JpaSystemPermissionsDao.java
- wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/model/impl/AbstractPermissions.java
- wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/model/impl/SystemPermissionsImpl.java
- wsmaster/codenvy-hosted-api-permission/src/test/java/com/codenvy/api/permission/server/spi/tck/SystemPermissionsDaoTest.java
- wsmaster/codenvy-hosted-api-resource/src/main/java/com/codenvy/resource/spi/impl/ResourceImpl.java
- wsmaster/codenvy-hosted-api-resource/src/main/java/com/codenvy/resource/spi/jpa/JpaFreeResourcesLimitDao.java
- wsmaster/codenvy-hosted-api-resource/src/test/java/com/codenvy/resource/spi/tck/FreeResourcesLimitDaoTest.java
- wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/model/impl/WorkerImpl.java
- wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/spi/jpa/JpaStackPermissionsDao.java
- wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/spi/jpa/JpaWorkerDao.java
- wsmaster/codenvy-hosted-api-workspace/src/test/java/com/codenvy/api/workspace/server/jpa/JpaStackPermissionsDaoTest.java
- wsmaster/codenvy-hosted-api-workspace/src/test/java/com/codenvy/api/workspace/server/spi/tck/StackPermissionsDaoTest.java
- wsmaster/codenvy-hosted-api-workspace/src/test/java/com/codenvy/api/workspace/server/spi/tck/WorkerDaoTest.java
- wsmaster/codenvy-hosted-integration-tests/codenvy-integration-tck-jpa/src/test/java/com/codenvy/api/tck/JpaIntegrationTckModule.java
The problem is described by PR [CHE#3192](https://github.com/eclipse/che/pull/3192).
The issue it fixes is [CHE#2993](https://github.com/eclipse/che/issues/2993).
@skabashnyuk, @akorneta, @sleshchenko please review.
> Include synthetic id into equals & hashcode

- dockerfiles/init/manifests/codenvy.env
- dockerfiles/init/manifests/codenvy.pp
- dockerfiles/init/modules/codenvy/templates/general.properties.erb
- dockerfiles/init/modules/codenvy/templates/machine.properties.erb
* allow to enable / disable auto snapshots and restore
* allow to configure custom registry for workspace snapshots
@benoitf @TylerJewell @garagatyi 
@TylerJewell this may require docs updates, can you please help me with this ?
> Auto snapshots configurability

- dockerfiles/init/modules/compose/templates/docker-compose-container.yml.erb
- dockerfiles/init/modules/compose/templates/docker-compose.yml.erb
- dockerfiles/init/modules/postgres/templates/postgresql.conf.erb
- dockerfiles/init/modules/rsyslog/templates/postgre.conf.erb
needed for https://github.com/codenvy/codenvy/issues/1250
@skabashnyuk @garagatyi
> enable postgre logs

- dockerfiles/init/modules/compose/templates/docker-compose-container.yml.erb
- dockerfiles/init/modules/postgres/templates/postgresql.conf.erb
- dockerfiles/init/modules/rsyslog/manifests/init.pp
- dockerfiles/init/modules/rsyslog/templates/postgre.conf.erb
rework pg loggin due to issues on linux
@skabashnyuk
> rework pg loggin due to issues on linux

- dockerfiles/init/modules/compose/templates/docker-compose-container.yml.erb
- dockerfiles/init/modules/compose/templates/docker-compose.yml.erb
- dockerfiles/init/modules/rsyslog/manifests/init.pp
- dockerfiles/init/modules/rsyslog/templates/postgre.conf.erb
- dockerfiles/init/modules/rsyslog/templates/postgres.conf.erb
> fix names, sync compose files

- wsmaster/codenvy-hosted-integration-tests/codenvy-integration-tck-jpa/pom.xml
> Fix maven warnings

- dockerfiles/init/modules/compose/templates/docker-compose-container.yml.erb
- dockerfiles/init/modules/postgres/templates/postgresql.conf.erb
- dockerfiles/init/modules/rsyslog/manifests/init.pp
- dockerfiles/init/modules/rsyslog/templates/postgres.conf.erb
> move pg logs to pg data folder

- dockerfiles/init/modules/compose/templates/docker-compose-container.yml.erb
- dockerfiles/init/modules/rsyslog/manifests/init.pp
- dockerfiles/init/modules/rsyslog/templates/registry.conf.erb
> introduce logs for registry

- wsmaster/codenvy-hosted-api-license/pom.xml
- wsmaster/codenvy-hosted-api-license/src/main/java/com/codenvy/api/license/CodenvyLicense.java
- wsmaster/codenvy-hosted-api-license/src/main/java/com/codenvy/api/license/CodenvyLicenseFactory.java
- wsmaster/codenvy-hosted-api-license/src/main/java/com/codenvy/api/license/exception/LicenseNotActivatedException.java
- wsmaster/codenvy-hosted-api-license/src/main/java/com/codenvy/api/license/server/CodenvyLicenseActionHandler.java
- wsmaster/codenvy-hosted-api-license/src/main/java/com/codenvy/api/license/server/CodenvyLicenseActivator.java
- wsmaster/codenvy-hosted-api-license/src/main/java/com/codenvy/api/license/server/CodenvyLicenseManager.java
- wsmaster/codenvy-hosted-api-license/src/main/java/com/codenvy/api/license/server/CodenvyLicenseManagerObservable.java
- wsmaster/codenvy-hosted-api-license/src/main/java/com/codenvy/api/license/server/CodenvyLicenseManagerObserver.java
- wsmaster/codenvy-hosted-api-license/src/main/java/com/codenvy/api/license/server/CodenvyLicenseStorage.java
- wsmaster/codenvy-hosted-api-license/src/main/java/com/codenvy/api/license/server/dao/CodenvyLicenseActionDao.java
- wsmaster/codenvy-hosted-api-license/src/main/java/com/codenvy/api/license/server/jpa/JpaCodenvyLicenseActionDao.java
- wsmaster/codenvy-hosted-api-license/src/test/java/com/codenvy/api/license/CodenvyLicenseFactoryTest.java
- wsmaster/codenvy-hosted-api-license/src/test/java/com/codenvy/api/license/CodenvyLicenseTest.java
- wsmaster/codenvy-hosted-api-license/src/test/java/com/codenvy/api/license/server/CodenvyLicenseActionHandlerTest.java
- wsmaster/codenvy-hosted-api-license/src/test/java/com/codenvy/api/license/server/CodenvyLicenseActivatorTest.java
- wsmaster/codenvy-hosted-api-license/src/test/java/com/codenvy/api/license/server/CodenvyLicenseManagerTest.java
- wsmaster/codenvy-hosted-api-license/src/test/java/com/codenvy/api/license/server/CodenvyLicenseStorageTest.java
- wsmaster/codenvy-hosted-api-license/src/test/java/com/codenvy/api/license/server/spi/tck/JpaCodenvyLicenseActionDaoTest.java
- wsmaster/codenvy-sql-schema/src/main/resources/codenvy-schema/5.0.0-M8/1.2__init.sql
Activate Codenvy licenses on Online.license4j
https://github.com/codenvy/enterprise/issues/15
> Support Codenvy license activation

- wsmaster/codenvy-hosted-api-audit/src/main/java/com/codenvy/api/audit/server/AuditManager.java
- wsmaster/codenvy-hosted-api-audit/src/main/java/com/codenvy/api/audit/server/AuditReportPrinter.java
- wsmaster/codenvy-hosted-api-audit/src/test/java/com/codenvy/api/audit/server/AuditManagerTest.java
- wsmaster/codenvy-hosted-api-license/pom.xml
- wsmaster/codenvy-hosted-api-license/src/main/java/com/codenvy/api/license/server/CodenvyLicenseActionHandler.java
- wsmaster/codenvy-hosted-api-license/src/main/java/com/codenvy/api/license/server/model/impl/FairSourceLicenseAcceptanceImpl.java
- wsmaster/codenvy-hosted-api-license/src/test/java/com/codenvy/api/license/server/CodenvyLicenseActionHandlerTest.java
https://github.com/codenvy/enterprise/issues/23
Add codenvy license accepts and reverts into the audit log
> ENT-23: Add codenvy license accepts and reverts into the audit log

- dockerfiles/init/modules/compose/templates/docker-compose-container.yml.erb
- dockerfiles/init/modules/compose/templates/docker-compose.yml.erb
> add depends_on for rsyslog, sync compose files

- wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/filters/WorkspacePermissionsFilter.java
- wsmaster/codenvy-hosted-api-workspace/src/test/java/com/codenvy/api/workspace/server/filters/WorkspacePermissionsFilterTest.java
Adds ability to view server auto-snapshot and auto-restore settings through API
https://github.com/eclipse/che/issues/3287
> Add Workspace settings service

- dashboard/src/app/factories/load-factory/load-factory.controller.ts
Change identifier for import project channel  according to changes in Che project
Signed-off-by: Roman Nikitenko <rnikitenko@codenvy.com>
> Change identifier for import project channel

- plugins/plugin-hosted/codenvy-hosted-ext-factory/src/main/java/com/codenvy/ide/factory/client/welcome/GreetingPartPresenter.java
- plugins/plugin-hosted/codenvy-hosted-ext-factory/src/main/java/com/codenvy/ide/factory/client/welcome/GreetingPartViewImpl.java
- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/parts/contribute/ContributePartPresenter.java
- plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/parts/contribute/ContributePartViewImpl.java
Add the ability to maximize any panel.
https://github.com/eclipse/che/issues/2463
See video for details
https://youtu.be/xSp7lhgF4as
> CHE-2463 Improve Panels behaviors in IDE

- dockerfiles/cli/Dockerfile
this need to make M9-SNAPSHOT available as nightly tag
@benoitf 
@skabashnyuk 
later this will be automated during release process
> set nightly versions for M9-SN iteration

- assembly/onpremises-ide-compiling-war-ide/pom.xml
- assembly/onpremises-ide-compiling-war-ide/src/main/resources/com/codenvy/ide/IDE.gwt.xml
- assembly/onpremises-ide-packaging-war-ext-server/pom.xml
Adds Zend debugger capabilities
https://github.com/eclipse/che/issues/2590
> Zend debugger

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/backup/MachineBackupManager.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/backup/MachineBackupManagerTest.java
Add node URL to the error logging during workspace backup/restore
https://github.com/codenvy/codenvy/issues/1279
> CODENVY-1279 Add node address for loggin errors during backup/workspace

- wsmaster/codenvy-sql-schema/src/main/resources/codenvy-schema/5.0.0-M9/1.1__rename_managecodenvy_action.sql
> Fix license

- assembly/onpremises-ide-packaging-tomcat-codenvy-allinone/src/assembly/assembly.xml
Fixes addition of terminal agent into assembly which fixes start of terminal agent
> Fix start of terminal agent in Codenvy in Docker

- site/app/_layouts/accept-license-page.html
- site/app/site/auth/accept-fair-source-license.html
- site/app/site/custom_pages/onprem-se/templates/create.html
- site/app/site/custom_pages/onprem-se/templates/login.html
- site/app/site/scripts/app.js
- site/app/site/scripts/models/account.js
- site/app/site/scripts/views/accept-fair-source-license.js
- site/app/site/scripts/views/accountformbase.js
- site/app/site/scripts/views/login.js
- site/app/site/styles/style.css
- site/app/site/templates/create.html
- site/app/site/templates/login.html
This PR is needed for https://github.com/codenvy/codenvy/issues/1154
> CODENVY-1154 create accept-license page

- dockerfiles/cli/scripts/cli.sh
Name of the commands were invalid
https://github.com/codenvy/codenvy/issues/1322
unable to call methods
Fix method names
No
Change-Id: I7aa536a25593f3c197b4617c3e89e00eb9abcc8f
> Fix #1322 for node commands

- dashboard/src/app/admin/onprem-administration/license/license.controller.ts
- dashboard/src/app/onprem/license-messages/license-agreement-dialog/cancel-agreement-dialog.controller.ts
- dashboard/src/app/onprem/license-messages/license-agreement-dialog/cancel-agreement-dialog.html
- dashboard/src/app/onprem/license-messages/license-agreement-dialog/cancel-agreement-dialog.styl
- dashboard/src/app/onprem/license-messages/license-agreement-dialog/license-agreement-dialog.controller.ts
- dashboard/src/app/onprem/license-messages/license-agreement-dialog/license-agreement-dialog.html
- dashboard/src/app/onprem/license-messages/license-agreement-dialog/license-agreement-dialog.styl
- dashboard/src/app/onprem/license-messages/license-messages.service.ts
- dashboard/src/app/onprem/onprem-config.ts
- dashboard/src/components/api/codenvy-license.factory.ts
Add popup with license agreement
> ENTERPRISE-12: add popup with license agreement

- dashboard/src/components/api/test/codenvy-http-backend.ts
- dashboard/src/index.html
Displays codenvy version in footer.
https://github.com/codenvy/codenvy/issues/1273
> CODENVY-1273: display codenvy version in footer

- dockerfiles/init/Dockerfile
after remove docs folder from init image docker build is failed.
> fix init image build

- dockerfiles/codenvy/Dockerfile
> update codenvy docker image

- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
Required for https://github.com/eclipse/che/pull/3383
> Fixed logging folder for exec agent

- docs/_docs/admin-guide/runbook
Adds the runbook content from readme.io to these docs. This content still needs to be updated for dockeried codenvy.
> Adding runbook to admin docs

- dockerfiles/init/manifests/codenvy.env
- dockerfiles/init/manifests/codenvy.pp
- dockerfiles/init/modules/codenvy/templates/general.properties.erb
add new org  props, this should be merged once # will be merged to master.
https://github.com/codenvy/codenvy/pull/1319
> add new org props

- site/app/site/auth/create.html
- site/app/site/error/fair-source-license-is-not-accepted-error.html
- site/app/site/scripts/app.js
- site/app/site/scripts/models/account.js
- site/app/site/scripts/views/accept-fair-source-license.js
- site/app/site/scripts/views/fair-source-license-is-not-accepted-error.js
- site/app/site/styles/style.css
This PR is needed for https://github.com/codenvy/enterprise/issues/11
> Logout user if Fear Source License is not accepted by admin

- docs/_docs/index.html
- docs/_sass/_font-awesome.scss
- docs/_sass/_style.scss
Fix Styling in docs:
* inline codebox
* spacing with the headers
* h4 header style
* remove unused images and references
* update footer from index page
* fix font-awesome reference
> Fix styling in docs

- assembly/onpremises-ide-packaging-war-ext-server/src/main/java/com/codenvy/ext/java/server/MachineModule.java
Removes SocketEventBusClient from configuration
https://github.com/codenvy/codenvy/issues/959
> CODENVY-959: Get rid of WSocketEventBusClient

- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
Repairs docker constraint to not to start a container on a node under maintenance.
> Repair maintenance mode of Codenvy node

- wsmaster/codenvy-hosted-workspace-activity/src/main/java/com/codenvy/activity/server/WorkspaceActivityManager.java
Change log level from ERROR to DEBUG when trying to stop workspace in WorkspaceActivityManager
https://github.com/codenvy/codenvy/issues/1358
> CODENVY-1358 Change log level in workspace activity manager

- assembly/onpremises-ide-packaging-tomcat-codenvy-allinone/pom.xml
- assembly/onpremises-ide-packaging-tomcat-codenvy-allinone/src/assembly/assembly.xml
- pom.xml
Add docs war to codenvy packaging
> Add docs war

- dashboard/src/app/onprem/license-messages/license-messages.service.ts
Show 'No valid license detected' nag message to all users.
'No valid license detected' nag message wasn't shown for non-admin user.
> Show 'No valid license detected' nag message to all users.

- dockerfiles/init/modules/compose/templates/docker-compose.yml.erb
As per @skryzhny request, we should have exposed swarm port to the host.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codenvy/codenvy/1470)
> expose swarm port to host

- wsmaster/codenvy-sql-schema/pom.xml
Fix SQL license exclusion filter to work with Maven 3.3.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codenvy/codenvy/1483)
> Fix SQL license exclusion filter

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/swarm/client/SwarmDockerConnector.java
Adds workaround to temporary fix #1215 issue.
This PR just make another try(after pause) to create container if swarm failed to see new image.
Workaround for #1215
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codenvy/codenvy/1480)
> CODENVY-1215: Workaround for unexpected behaviour of swarm

- dockerfiles/build.include
Fix issue #1485
Change-Id: I04dc3e941f99e2afcb3ddca448b3cf8e509d5d43
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codenvy/codenvy/1494)
> Fix sh issue (was working only with bash)

- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/CodenvyDockerServerEvaluationStrategy.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedServersInstanceRuntimeInfo.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/CodenvyDockerServerEvaluationStrategyTest.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/HostedServersInstanceRuntimeInfoTest.java
Fix Codenvy according changes in Che eclipse/che#3282
Related to eclipse/che#3282
Yes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codenvy/codenvy/1444)
> Fix Codenvy according changes in Che

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/CodenvyDockerServerEvaluationStrategy.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/CodenvyDockerServerEvaluationStrategyTest.java
Fix build after merging of out-of-sync PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codenvy/codenvy/1497)
> Fix build after merging of out-of-sync PR

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedDockerInstance.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/HostedDockerInstanceTest.java
Adapts to changes introduced by [che-3561](https://github.com/eclipse/che/pull/3561).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codenvy/codenvy/1441)
> Adapt HostedDockerInstance constructor & tests

- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
- dockerfiles/init/modules/codenvy/templates/machine.properties.erb
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/agent/CodenvyInContainerInfrastructureProvisioner.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/agent/CodenvyInfrastructureProvisioner.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/agent/NativeCodenvyInfrastructureProvisioner.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/agent/WorkspaceInfrastructureModule.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/backup/DockerEnvironmentBackupManager.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/backup/DockerEnvironmentBackupManagerTest.java
- wsmaster/codenvy-hosted-platform-api-impl/pom.xml
- wsmaster/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/workspace/TestObjects.java
Refactor workspace infrastructure provisioning in accordance with changes in Che.
Fixes #1149 
Empty volumes for terminal agent and ws-agent were mounted in Codenvy in container. 
But were not used.
In Codenvy in container unneeded volumes of agents are not mounted.
No
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codenvy/codenvy/1452)
> CODENVY-1149: Refactor workspace infrastructure provisioning.

- dockerfiles/init/manifests/codenvy.env
- dockerfiles/init/manifests/codenvy.pp
- dockerfiles/init/modules/codenvy/templates/logback-additional-appenders.xml.erb
simple changes which allow configure hardcoded configuration.
needed for https://github.com/eclipse/che/issues/3670
> add possibility to configure logback host / port

- dockerfiles/cli/scripts/cli.sh
> cli: Replace Codenvy JMX by jmx to be consistent

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedMachineProviderImpl.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/HostedMachineProviderImplTest.java
Introduces changes needed after merge of eclipse/che#3677
Fixes #1150 
Docker containers of workspace had non needed hosts entry from Che. 
No extra hosts entries is set.
No
> CODENVY-1150: change classes according to changes in CHE

- dockerfiles/cli/scripts/cli.sh
Change-Id: I637c29bb196f181708e69bfc4026a1f73df619f1
> [cli] Fix indent for JMX so [AVAILABLE] tag is aligned with previous lines

- dockerfiles/cli/version/5.0.1/images
as we made bugfix from a branch we need add 5.0.1 version to cli in master
> add 5.0.1 version

- dockerfiles/init/modules/codenvy/templates/machine.properties.erb
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/backup/DockerEnvironmentBackupManager.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/backup/WorkspaceFsBackupScheduler.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/backup/DockerEnvironmentBackupManagerTest.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/backup/WorkspaceFsBackupSchedulerTest.java
- wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/resource/OrganizationResourcesDistributor.java
- wsmaster/codenvy-hosted-api-organization/src/test/java/com/codenvy/organization/api/resource/OrganizationResourcesDistributorTest.java
- wsmaster/codenvy-hosted-api-resource/src/main/java/com/codenvy/resource/api/usage/ResourcesLocks.java
- wsmaster/codenvy-hosted-integration-tests/codenvy-integration-cascade-jpa/src/test/java/com/codenvy/integration/jpa/cascaderemoval/JpaEntitiesCascadeRemovalTest.java
- wsmaster/codenvy-hosted-machine-authentication/src/test/java/com/codenvy/machine/authentication/server/interceptor/MachineTokenInterceptorTest.java
- wsmaster/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManager.java
Adapts the code to changes in eclipse/che#3701
> Adapt changes to start cancellation

- wsmaster/codenvy-hosted-api-permission/pom.xml
- wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/InstanceParameterValidator.java
- wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/PermissionsService.java
- wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/filter/GetPermissionsFilter.java
- wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/filter/RemovePermissionsFilter.java
- wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/filter/SetPermissionsFilter.java
- wsmaster/codenvy-hosted-api-permission/src/test/java/com/codenvy/api/permission/server/filter/GetPermissionsFilterTest.java
- wsmaster/codenvy-hosted-api-permission/src/test/java/com/codenvy/api/permission/server/filter/RemovePermissionsFilterTest.java
- wsmaster/codenvy-hosted-api-permission/src/test/java/com/codenvy/api/permission/server/filter/SetPermissionsFilterTest.java
Add checking instance id to avoid NPE.
https://github.com/codenvy/codenvy/issues/1321
Yes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codenvy/codenvy/1427)
> CODENVY-1321 Add checking instance id to avoid NPE

- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiServletModule.java
- wsmaster/codenvy-hosted-api-node/pom.xml
- wsmaster/codenvy-hosted-api-node/src/main/java/com/codenvy/api/node/server/NodeModule.java
- wsmaster/codenvy-hosted-api-node/src/main/java/com/codenvy/api/node/server/filters/NodeServicePermissionFilter.java
- wsmaster/codenvy-hosted-api-node/src/test/java/com/codenvy/api/node/server/filters/NodeServicePermissionFilterTest.java
Add permission filter to restrict node service methods access
https://github.com/codenvy/codenvy/issues/1292
Yes
Unknown
> CODENVY-1292 Add permission filter for Node Service

- dashboard/pom.xml
- dashboard/src/app/account/details/account-config.ts
- dashboard/src/app/account/details/account-delete.controller.ts
- dashboard/src/app/account/details/account-delete.directive.ts
- dashboard/src/app/account/details/account-delete.html
- dashboard/src/app/navbar/codenvy-navbar.html
- dashboard/src/app/navbar/navbar-config.ts
- dashboard/src/app/navbar/navbar.controller.ts
- dashboard/src/app/navbar/navbar.directive.ts
- dashboard/typings.json
Fix delete account exception for Firefox.
#1193
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codenvy/codenvy/1450)
> CODENVY-1193 fix delete account exception for Firefox

- assembly/onpremises-ide-packaging-tomcat-codenvy-allinone/pom.xml
Add dependencies for all-in-one assembly
https://github.com/codenvy/codenvy/issues/1508
> Add missing dependencies

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/CodenvyDockerServerEvaluationStrategy.java
Code cleanup related to PR eclipse/che#3812
> CHE-3686: move method to base class

- dockerfiles/init/manifests/codenvy.env
- dockerfiles/init/manifests/codenvy.pp
fixes https://github.com/codenvy/codenvy/issues/1592
> increase default ws agent inactive timeout

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedMachineProviderImpl.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/HostedMachineProviderImplTest.java
Adds limits on CPU consumption by build docker image task.
Adds a few tests.
#1393 
Yes
> CODENVY-1393: Limit CPU consumption by build docker image tasks

- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
- plugins/plugin-hosted/codenvy-machine-hosted/pom.xml
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/agent/CodenvyAgentModule.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/agent/ExternalRsyncAgent.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/agent/MachineInnerRsyncAgent.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/agent/launcher/WsAgentWithAuthLauncherImpl.java
Decouple different agents on different maven modules
https://github.com/eclipse/che/issues/3720
> CHE-3720: Decouple different agents on different maven modules

- dockerfiles/cli/version/5.2.0/images
- dockerfiles/cli/version/latest/images
- dockerfiles/cli/version/nightly/images
needed for: https://github.com/codenvy/codenvy/issues/1517
fixes: https://github.com/eclipse/che/issues/2962
> upgrade swarm to 1.2.6

- dockerfiles/init/modules/codenvy/templates/rsyncbackup.sh.erb
- dockerfiles/init/modules/codenvy/templates/rsyncrestore.sh.erb
Fix restore and backup scripts to add ability start workspaces from docker images without sudo.
https://github.com/codenvy/codenvy/issues/1602
1.  API changes (No)
2.  User docs changes(No)  
@garagatyi @riuvshin @tolusha  review please.
> CODENVY-1602: Fix restore and backup scripts to add ability start workspaces from docker images without sudo.

- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedDockerInstance.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedMachineProviderImpl.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/HostedDockerInstanceTest.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/HostedMachineProviderImplTest.java
- wsmaster/codenvy-hosted-system-ram/src/main/java/com/codenvy/service/systemram/DockerBasedSystemRamInfoProvider.java
- wsmaster/codenvy-hosted-system-ram/src/test/java/com/codenvy/service/systemram/DockerBasedSystemRamInfoProviderTest.java
After Che PR https://github.com/eclipse/che/pull/3798 code has been broken
https://github.com/eclipse/che/pull/3798 
should compile again
maybe it needs update for swarm for this part
https://github.com/eclipse/che/blob/1ec641a7e823eb7ff1092d26654d720fc7c949d7/plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/local/LocalDockerModule.java#L69-L71
tests updated
no
> Update code based on CHE #3798 updates

- dockerfiles/cli/scripts/cli.sh
- dockerfiles/init/modules/codenvy/templates/general.properties.erb
needed for https://github.com/codenvy/customer-saas/issues/126
those changes allows addon.pp have module which allow not only set variables but create new files if needed
> improve addon to have own modules

- .github/PULL_REQUEST_TEMPLATE.md
Updates PR template with new policy items: https://github.com/codenvy/planning/wiki/Development-Workflow#pull-requests
> Added new PR policy items

- assembly/onpremises-ide-packaging-war-platform-api/pom.xml
- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
- assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiServletModule.java
- pom.xml
- wsmaster/codenvy-hosted-platform-api-impl/pom.xml
- wsmaster/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManager.java
- wsmaster/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManagerTest.java
- wsmaster/codenvy-hosted-system/pom.xml
- wsmaster/codenvy-hosted-system/src/main/java/com/codenvy/service/system/DockerBasedSystemRamInfoProvider.java
- wsmaster/codenvy-hosted-system/src/main/java/com/codenvy/service/system/HostedSystemService.java
- wsmaster/codenvy-hosted-system/src/main/java/com/codenvy/service/system/SystemRamInfo.java
- wsmaster/codenvy-hosted-system/src/main/java/com/codenvy/service/system/SystemRamInfoProvider.java
- wsmaster/codenvy-hosted-system/src/main/java/com/codenvy/service/system/SystemRamLimitMessageSender.java
- wsmaster/codenvy-hosted-system/src/main/java/com/codenvy/service/system/SystemServicePermissionsFilter.java
- wsmaster/codenvy-hosted-system/src/main/java/com/codenvy/service/system/dto/SystemRamLimitDto.java
- wsmaster/codenvy-hosted-system/src/test/java/com/codenvy/service/system/DockerBasedSystemRamInfoProviderTest.java
- wsmaster/codenvy-hosted-system/src/test/java/com/codenvy/service/system/SystemRamLimitMessageSenderTest.java
- wsmaster/codenvy-hosted-system/src/test/java/com/codenvy/service/system/SystemServicePermissionsFilterTest.java
- wsmaster/codenvy-hosted-system/src/test/resources/logback-test.xml
- wsmaster/pom.xml
Allows to get state and stop system for those users who
have manage_codenvy permission.
Adapts code to changes made by eclipse/che#3917
> Adds permissions filter for system service

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/RemoteDockerNode.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/RemoteDockerNodeTest.java
Fixes #1663.
If _unbindWorkspace_ is called before _bindWorkspace_ completed or called,
then warning is logged and unbind(backup) is not performed. So basically
if workspace start is failed or interrupted no one overrides old binaries.
Ensures workspaces are properly backed up even if a subsequent workspace start fails.
N/A for bugs
N/A for bugs
> Don't backup workspace if restore is failed

- .mvn/jvm.config
- plugins/plugin-hosted/codenvy-machine-hosted/pom.xml
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/agent/CodenvyAgentModule.java
Fix ssh exec agent binding
Changelog: Fix ssh exec agent binding
> Fix ssh exec agent binding

- wsmaster/codenvy-hosted-mail-server/pom.xml
- wsmaster/codenvy-hosted-mail-server/src/main/java/com/codenvy/mail/deploy/CloudIdeMailModule.java
Fixes JSON parsing in email sender service.
Fixes #1689 
Fix signup with email and password recovery features.
N/A
N/A
> CODENVY-1689: fix JSON parsing in email sender

- assembly/assembly-main/pom.xml
- dockerfiles/cli/scripts/pre_init.sh
- dockerfiles/codenvy/Dockerfile
Fixes assembly-main artifact names.
INFRA-68
> INFRA-68; fix artifact names

- dockerfiles/codenvy/Dockerfile
- dockerfiles/init/modules/codenvy/templates/codenvy.env.erb
> Revert "OpenJDK instead of Oracle JDK"

- dockerfiles/cli/scripts/cmd_config.sh
add checks to not append compose file on windows
add checks to not append compose file on windows
> add checks to not append compose file on windows

- assembly/assembly-wsagent-war/src/main/java/com/codenvy/ext/java/server/MachineModule.java
Caused by changes in https://github.com/eclipse/che/pull/3627
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codenvy/codenvy/1486)
> Assembly fix for Json RPC

- dashboard/src/assets/branding/product.json
Changes the error message you get when OAuth is not configured.
N/A
N/A
N/A
N/A
> oauthDocs Typo

- dockerfiles/agents/build.sh
- dockerfiles/build.include
allows to skip maven update during build agents image
allow to skip maven update during build agents image
> allow skip maven update for build agents image

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/backup/DockerEnvironmentBackupManager.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/backup/DockerEnvironmentBackupManagerTest.java
Cleanup backup resources even when container is missing.
Fixes #1403 
Fixed workspace restart in case swarm node was forcefully stopped.
> CODENVY-1403: cleanup backup resources even when container is missing

- dashboard/src/app/factories/factory-details/information-tab/factory-information/factory-information.html
- dashboard/src/app/factories/list-factories/list-factories.html
- site/app/site/email-templates/user_created_with_password.html
- site/app/site/email-templates/user_created_without_password.html
Related to https://github.com/codenvy/codenvy/issues/1785
This refers to external documentation at https://codenvy.com/docs/. We can enhance this PR with internal documentation which I do not know how to reference(relative/full path unknown) or we can merge this and enhance later.
> Remove readmeio

- pom.xml
remove selenium dependencies
clean up selenium dependencies
> clean up selenium dependencies

- dashboard/src/assets/branding/branding.css
- dashboard/src/index.html
Add ability to easily override  dashboard styles
https://github.com/codenvy/enterprise/issues/39
Allows dashboard styles to be overridden by modifying a single CSS file.
No required
No required
> ENT-39: Add ability to override easily dashboard styles

- CHANGELOG.md
> Update CHANGELOG.md 5.3.1

- wsmaster/codenvy-hosted-api-organization-shared/src/main/java/com/codenvy/organization/shared/dto/OrganizationDto.java
- wsmaster/codenvy-hosted-api-organization-shared/src/main/java/com/codenvy/organization/shared/model/Organization.java
- wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/DtoConverter.java
- wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/OrganizationManager.java
- wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/OrganizationService.java
- wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/spi/OrganizationDao.java
- wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/spi/impl/OrganizationImpl.java
- wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/spi/jpa/JpaOrganizationDao.java
- wsmaster/codenvy-hosted-api-organization/src/test/java/com/codenvy/organization/api/OrganizationManagerTest.java
- wsmaster/codenvy-hosted-api-organization/src/test/java/com/codenvy/organization/api/OrganizationServiceTest.java
- wsmaster/codenvy-hosted-api-organization/src/test/java/com/codenvy/organization/spi/tck/OrganizationDaoTest.java
Add qualified name to make suborganizations' names unique per parent organization
https://github.com/codenvy/codenvy/issues/1674
- Add qualified name to make suborganizations' names unique per parent organization
N/A part of teams
N/A part of teams
> Add qualified name to make suborganizations' names unique per parent

- dockerfiles/cli/scripts/cmd_config.sh
Fix CLI errors during config stage in non-dev mode.
Follow up to https://github.com/codenvy/codenvy/pull/1835
fixes CLI error in non dev mode
> Fix non-dev mode Codenvy running in CLI

- site/app/site/email-templates/team_deleted.html
- site/app/site/email-templates/team_renamed.html
- site/app/site/email-templates/user_removed_from_team.html
Email notification improves
Team email notification fixes 
- N/A for bugs
- N/A
> Team email notification fixes 

- wsmaster/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManager.java
Fix error messages when account doesn't have enough resources to perform operation
TODO
Fix error messages when account doesn't have enough resources to perform operation
N/A
N/A
> Fix error messages when account doesn't have enough resources

- wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/resource/SuborganizationResourcesProvider.java
- wsmaster/codenvy-hosted-api-organization/src/test/java/com/codenvy/organization/api/resource/SuborganizationResourcesProviderTest.java
- wsmaster/codenvy-hosted-api-resource/src/main/java/com/codenvy/resource/api/usage/ResourceUsageManager.java
Fix providing resources for suborganizations
https://github.com/codenvy/codenvy/issues/1875
Fixed providing resources for suborganizations
N/A
N/A
> CODENVY-1875 Fix providing resources for suborganizations

- dashboard/src/app/dashboard/main-dashboard-config.ts
- dashboard/src/app/dashboard/main-dashboard.controller.ts
- dashboard/src/app/dashboard/main-dashboard.html
- dashboard/src/app/dashboard/main-dashboard.styl
- dashboard/src/app/index.module.ts
- dashboard/src/app/workspace/timeout/timeout-info.controller.ts
- dashboard/src/app/workspace/timeout/timeout-info.html
- dashboard/src/components/api/codenvy-team.factory.ts
Fixes critical bugs for release 5.4.1:
Display Get more RAM widget on dashboard page.
Get more RAM button will show the value of idle timeout.
https://github.com/codenvy/saas/issues/174
https://github.com/codenvy/saas/issues/176
Added "Get More RAM" widget on dashboard page, display idle timeout value on button's caption.
https://github.com/codenvy/docs/pull/93
> Dashboard 5.4.1 fixes

- dashboard/src/app/teams/team-details/team-details.controller.ts
- dashboard/src/app/teams/team-details/team-details.html
- dashboard/src/app/teams/team-details/team-details.service.ts
- dashboard/src/app/teams/team-details/team-members/list-team-members.controller.ts
- dashboard/src/app/teams/team-details/team-members/list-team-members.directive.ts
- dashboard/src/app/teams/team-details/team-owners/list-team-owners.controller.ts
- dashboard/src/app/teams/team-details/team-owners/list-team-owners.directive.ts
- dashboard/src/app/teams/team-details/team-workspaces/list-team-workspaces.controller.ts
- dashboard/src/app/teams/team-details/team-workspaces/list-team-workspaces.directive.ts
- dashboard/src/app/teams/teams-config.ts
- dashboard/src/components/api/codenvy-team.factory.ts
- dashboard/src/components/api/codenvy-user.factory.ts
Fix flickering in team's details.
https://github.com/codenvy/codenvy/issues/1756
Fixed flickering when changing tabs in team's details
Fixed flickering when changing tabs in team's details
N/A
> fix flickering in team's details

- dockerfiles/init/manifests/codenvy.env
- dockerfiles/init/manifests/codenvy.pp
- dockerfiles/init/modules/codenvy/templates/general.properties.erb
add property to enable/disable ws autostart
needed for https://github.com/eclipse/che/pull/4287
add property to enable/disable ws autostart
> add property to enable/disable ws autostart

- dashboard/bower.json
Fixes build failure due to updating of transitive dependency.
The dependency has CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10670
Add version for angular-aria dependency in dashboard.
N/A
N/A
> Add angular-aria version

- dockerfiles/agents/pom.xml
- dockerfiles/agents/src/assembly/assembly.xml
- plugins/plugin-hosted/codenvy-machine-hosted/pom.xml
- pom.xml
Make changes according to changes in Che
Related to eclipse/che#4097
> CHE-4097: Make changes according to changes in Che

- dashboard/src/app/billing/billing.controller.ts
- dashboard/src/app/billing/billing.html
- dashboard/src/app/billing/billing.styl
- dashboard/src/app/billing/card-info/card-info.directive.ts
- dashboard/src/app/billing/card-info/card-info.html
- dashboard/src/app/billing/ram-info/more-ram-dialog.html
Fix tabs flickering on billing page.
#1756 
Fixed tabs flickering on billing page in dashboard
Fixed tabs flickering on billing page in dashboard
N/A - bugfix
> CODENVY-1756: fix tabs flickering on billing page

- dashboard/src/app/teams/list/list-teams.html
- dashboard/src/app/teams/list/team-item/team-item.html
- dashboard/src/app/teams/team-details/team-details.controller.ts
- dashboard/src/app/teams/team-details/team-details.html
- dashboard/src/app/teams/team-details/team-members/list-team-members.controller.ts
- dashboard/src/components/api/codenvy-team.factory.ts
The PR fixes:
- process non existing team or when user doesn't have access to the team
- ability to set zero resource CAPs or remove CAPs
https://github.com/codenvy/codenvy/issues/1693
https://github.com/codenvy/codenvy/issues/1710
Fix team details when user is requesting non-existing team or team with no access.
Fix ability to set zero resource CAPs or remove them
N/A
N/A
> Team details fixups

- dockerfiles/init/manifests/codenvy.env
- dockerfiles/init/manifests/codenvy.pp
- dockerfiles/init/modules/codenvy/templates/machine.properties.erb
add possibility to configure docker namespace for pushing snapshots
add possibility to configure docker namespace for pushing snapshots
> add possibility to configure docker namespace for snapshots

- wsmaster/codenvy-hosted-api-permission/pom.xml
- wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/PermissionsManager.java
- wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/filter/RemovePermissionsFilter.java
- wsmaster/codenvy-hosted-api-permission/src/test/java/com/codenvy/api/permission/server/PermissionsManagerTest.java
- wsmaster/codenvy-hosted-api-permission/src/test/java/com/codenvy/api/permission/server/filter/RemovePermissionsFilterTest.java
Adds ability for users to remove their own permissions.
Also this PR contains changes for locking by instance on updating permissions for it. It is needed to avoid cases like https://github.com/codenvy/codenvy/issues/1688#issuecomment-277239223
https://github.com/codenvy/saas/issues/168
Added ability for users to remove their own permissions.
Added ability for users to remove their own permissions.
N/A
> Add ability for users to remove own permissions

- plugins/plugin-hosted/codenvy-hosted-ext-factory/src/main/java/com/codenvy/ide/factory/client/utils/FactoryProjectImporter.java
> Fix FactoryProjectImporter according to che#4447

- dashboard/src/app/dashboard/main-dashboard.controller.ts
- dashboard/src/app/dashboard/main-dashboard.html
- dashboard/src/app/dashboard/main-dashboard.styl
- dashboard/src/app/teams/list/list-teams.directive.ts
- dashboard/src/app/teams/list/list-teams.html
- dashboard/src/app/teams/list/list-teams.styl
- dashboard/src/app/teams/list/team-item/team-item.directive.ts
- dashboard/src/app/teams/list/team-item/team-item.html
- dashboard/src/app/teams/team-details/team-details.controller.ts
- dashboard/src/app/teams/team-details/team-details.html
- dashboard/src/app/teams/teams-config.ts
- dashboard/src/app/workspace/timeout/timeout-info.controller.ts
- dashboard/src/app/workspace/timeout/timeout-info.html
- dashboard/src/app/workspace/workspace-config.ts
**- Adds teams on dashboard view.**
**- Adds ability to leave team from team details page.**
https://github.com/codenvy/saas/issues/175
https://github.com/codenvy/saas/issues/168
[UD] Added Teams list on dashboard page
[UD] Added ability to leave team from team details page. 
Added ability for team member to leave team, by clicking Leave button on team details page. 
https://github.com/codenvy/docs/pull/100
> Team list on dashboard page + leave team ability

- dockerfiles/init/modules/codenvy/templates/codenvy.env.erb
- dockerfiles/init/modules/compose/templates/docker-compose.yml.erb
save java heap dumps when oom happen
fixes: https://github.com/codenvy/codenvy/issues/1981
save java heap dumps when oom happen
> save heapdumps when jvm reach oom

- assembly/assembly-wsmaster-war/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
- dockerfiles/agents/pom.xml
- dockerfiles/agents/src/assembly/assembly.xml
- dockerfiles/init/modules/codenvy/templates/machine.properties.erb
- plugins/plugin-github/codenvy-plugin-github-webhooks/src/test/resources/factory-MKTG-341.json
- plugins/plugin-github/codenvy-plugin-github-webhooks/src/test/resources/factory-codenvy.json
- plugins/plugin-hosted/codenvy-machine-hosted/pom.xml
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/TerminalServerProxyTransformer.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/agent/CodenvyAgentModule.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/agent/CodenvyInContainerInfrastructureProvisionerTest.java
- plugins/plugin-microsoft/codenvy-plugin-microsoft-vsts-webhooks/src/test/resources/factory-codenvy.json
- pom.xml
- wsmaster/codenvy-hosted-machine-authentication/src/main/java/com/codenvy/machine/authentication/server/MachineAuthLinksInjector.java
- wsmaster/codenvy-hosted-machine-authentication/src/main/java/com/codenvy/machine/authentication/server/WorkspaceServiceAuthLinksInjector.java
CHE-4098: change agents usage after changes in Che
Related to eclipse/che#4098
> CHE-4098: change agents usage after changes in Che

- site/app/site/recover-password.html
- site/app/site/scripts/views/forgotpasswordform.js
This PR is fixup for https://github.com/codenvy/codenvy/issues/1850
> Hide support link if it is not configured in product.json

- assembly/assembly-wsmaster-war/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
Add missing filter bindings from #1977
Related to #1977
Add missing filter bindings
> CHE-4098: add missing filter bindings

- dashboard/src/app/workspace/share-workspace/add-developers/add-developers.controller.ts
- dashboard/src/app/workspace/share-workspace/add-developers/add-developers.html
- dashboard/src/app/workspace/share-workspace/add-developers/add-developers.styl
- dashboard/src/app/workspace/share-workspace/add-members/add-members.controller.ts
- dashboard/src/app/workspace/share-workspace/add-members/add-members.html
- dashboard/src/app/workspace/share-workspace/add-members/add-members.styl
- dashboard/src/app/workspace/share-workspace/share-workspace.controller.ts
- dashboard/src/app/workspace/share-workspace/share-workspace.html
- dashboard/src/app/workspace/workspace-config.ts
- dashboard/src/components/api/builder/codenvy-api-builder.factory.ts
- dashboard/src/components/api/builder/codenvy-team-builder.ts
- dashboard/src/components/api/codenvy-permissions.factory.ts
- dashboard/src/components/api/codenvy-team.factory.spec.ts
- dashboard/src/components/api/codenvy-team.factory.ts
- dashboard/src/components/api/test/codenvy-http-backend.ts
This PR restores ability to share personal workspace to any registered user.
**sharing personal workspace by owner**
**sharing personal workspace by non-owner**
#1963
Restored the ability to share personal workspaces with users registered in the Codenvy system.
N/A - bugfix
N/A - bugfix
> CODENVY-1963: allow user to share personal workspace

- site/app/site/scripts/views/resetpasswordform.js
fixup for site reset-password page
> fix reset password

- site/app/_layouts/email-template.html
make it possible to configure custom email banners
> apply branding to top/bottom banners

- dashboard/src/app/admin/user-management/add-user/add-user.controller.ts
- dashboard/src/components/api/codenvy-team.factory.ts
Remove unused code. It will fix undefined error in console during add a new user. 
https://github.com/codenvy/codenvy/issues/2040
N/A
N/A
> CODENVY-2040 remove unused code

- site/app/site/scripts/models/account.js
Fix situation when redirect_after_login contains hash
#2061 
None
None
None
> CODENVY-2061; fix situation when redirect_after_login contains hash

- dashboard/src/app/navbar/codenvy-navbar.html
- dashboard/src/app/navbar/navbar.controller.ts
Remove unused code in addition to  https://github.com/eclipse/che/commit/3d850d8b03d271d37967a1232ff10e495d796ba2
https://github.com/codenvy/codenvy/issues/2067
- removed unused code regarding plugin service
N/A
N/A
> CODENVY-2067 remove unused code

- assembly/assembly-wsagent-war/pom.xml
- assembly/compiling-ide-war/pom.xml
Remove not needed depndencies
Remove not needed depndencies
N/A
> Remove not needed depndencies

- assembly/assembly-dashboard-war/pom.xml
- assembly/assembly-dashboard-war/src/main/java/com/codenvy/onpremises/FactoryRedirectServlet.java
- assembly/assembly-dashboard-war/src/main/java/com/codenvy/onpremises/deploy/DashboardServletModule.java
- assembly/assembly-ide-war/src/main/webapp/WEB-INF/rewrite.config
- site/app/site/scripts/models/account.js
What does this PR do?
Fix factory rewriting URL and acceptance with login
What issues does this PR fix or reference?
codenvy/codenvy#2071
Changelog
None
Release Notes
None
Docs PR
None
> Fix factory rewriting URL

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedMachineProviderImpl.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/HostedMachineProviderImplTest.java
Fix constructor parameters according changes in Che
eclipse/che#4786
N/A
N/A
> Fix constructor parameters according changes in Che

- site/app/_layouts/error-page.html
- site/app/_layouts/new-simple.html
- site/app/_layouts/thank-you.html
- site/app/site/branding/google-analytics.js
fixes https://github.com/codenvy/enterprise/issues/69
> Enterprise 69 separate Google analytics script

- dockerfiles/init/manifests/codenvy.env
- dockerfiles/init/manifests/codenvy.pp
- dockerfiles/init/modules/compose/templates/docker-compose.yml.erb
- dockerfiles/init/modules/swarm/manifests/init.pp
- dockerfiles/init/modules/swarm/templates/swarm_entrypoint.sh.erb
- dockerfiles/swarm/Dockerfile
allows to configure swarm log level
https://github.com/codenvy/codenvy/issues/2108
allow to confugure swarm log level from codenvy.env
> allow to confugure swarm log level from codenvy.env

- dashboard/src/app/index.module.ts
- dashboard/src/components/api/test/codenvy-http-backend.ts
Fixes the requests to ws-agent API by setting Authorization header with machine token.
https://github.com/codenvy/codenvy/issues/2102
Partly https://github.com/codenvy/codenvy/issues/2031
- [UD] Fixed the wsagents API requests by providing machine API token.
N/A
N/A
> Fix setting machine authorization token for wsagent requests

- wsagent/codenvy-wsagent-core/pom.xml
- wsagent/codenvy-wsagent-core/src/main/java/com/codenvy/wsagent/server/WsAgentServletModule.java
Used cors binding from general che binding
fixes https://github.com/codenvy/codenvy/issues/2114
Related to https://github.com/eclipse/che/pull/4873
N/A
N/A
N/A
> Reused basic servlet binding from che, exclude che specific binding

- assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/codenvy-api-configuration.properties
- dockerfiles/init/manifests/codenvy.env
- dockerfiles/init/manifests/codenvy.pp
- dockerfiles/init/modules/codenvy/templates/email.properties.erb
- wsmaster/codenvy-hosted-events/src/main/java/com/codenvy/user/CreationNotificationSender.java
- wsmaster/codenvy-hosted-events/src/test/java/com/codenvy/user/CreationNotificationSenderTest.java
- wsmaster/codenvy-hosted-mail-sender/src/main/java/com/codenvy/mail/MailSender.java
- wsmaster/codenvy-hosted-recoverpassword/src/main/java/com/codenvy/service/password/PasswordService.java
- wsmaster/codenvy-hosted-sso-auth-bearer/src/main/java/com/codenvy/auth/sso/server/BearerTokenAuthenticationService.java
- wsmaster/codenvy-hosted-sso-auth-bearer/src/test/java/com/codenvy/auth/sso/server/BearerTokenAuthenticationServiceTest.java
Adds properties to be able to configure email subjects
Added ability to customize email subjects.
n/a
N/A
> ENTERPRISE-67: Make it possible to customize email subject

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/backup/DockerEnvironmentBackupManager.java
Prevent passing of illegal arguments obtained from docker to backup/restore scripts.
Speed up workspaces backup/restore by caching static data from docker.
https://github.com/codenvy/codenvy/issues/1988
Fixed passing illegal arguments to backup/restore workspace scripts.
Added caching for user info from workspace containers.
N/A
N/A
> CODENVY-1988: Prevent passing of illegal arguments to rsync script

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedMachineProviderImpl.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/HostedMachineProviderImplTest.java
Changes code in accordance with changes in Che.
Workarounds issues with Swarm when container or image could not be found by Swarm right after creation.
Related to eclipse/che#4310
Works around Swarm issue when container or image can't be found upon creation.
N/A
N/A
> Nocmdimage

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/swarm/client/SwarmDockerConnector.java
Adds more tracing to investigate swarm issue with missing execs 
Related to #1734 
Add more tracing to investigate swarm issue
> CODENVY-1734: add more tracing to investigate swarm issue

- dashboard/src/app/workspace/timeout/timeout-info.controller.ts
- dashboard/src/app/workspace/timeout/timeout-info.html
- dashboard/src/components/api/codenvy-team.factory.ts
Make it possible to create workspace for user before have been added to any organization, allow user to see the available timeout provided to user.
https://github.com/codenvy/codenvy/issues/2141
[dashboard] Allowed to create workspace for user before have been added to any organization, allowed user to see the available timeout provided to user.
N/A
N/A
> Make possible to create workspace before added to any organization, show timeout for simple user workspace

- dashboard/src/app/teams/team-details/team-members/list-team-members.controller.ts
- wsmaster/codenvy-hosted-api-invite/src/main/java/com/codenvy/api/invite/InviteManager.java
- wsmaster/codenvy-hosted-api-invite/src/main/java/com/codenvy/api/invite/subscriber/InviteToPermissionsConverter.java
- wsmaster/codenvy-hosted-api-invite/src/main/java/com/codenvy/spi/invite/InviteDao.java
- wsmaster/codenvy-hosted-api-invite/src/main/java/com/codenvy/spi/invite/jpa/JpaInviteDao.java
- wsmaster/codenvy-hosted-api-invite/src/test/java/com/codenvy/api/invite/InviteManagerTest.java
- wsmaster/codenvy-hosted-api-invite/src/test/java/com/codenvy/api/invite/subscriber/InviteToPermissionsConverterTest.java
- wsmaster/codenvy-hosted-api-invite/src/test/java/com/codenvy/spi/invite/tck/InviteDaoTest.java
- wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/resource/SuborganizationResourcesProvider.java
- wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/spi/MemberDao.java
- wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/spi/jpa/JpaMemberDao.java
- wsmaster/codenvy-hosted-api-resource/src/main/java/com/codenvy/resource/api/ResourceAggregator.java
- wsmaster/codenvy-hosted-api-resource/src/test/java/com/codenvy/resource/api/ResourceAggregatorTest.java
Add methods that could be overridden in saas assembly.
Add store permission error handling in dashboard.
needed for [#207](https://github.com/codenvy/saas/issues/207)
Added preparation functionalities needed for seats resources
n/a
n/a
> Provides functionality needed for seats

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/swarm/client/SwarmDockerConnector.java
Logs additional info when creation of docker container fail
https://github.com/codenvy/codenvy/issues/2104
Improved error logging on container creation.
N/A
N/A
> CODENVY-2104: Log additional info on docker container creation fail

- wsmaster/codenvy-sql-schema/src/main/resources/codenvy-schema/5.10.0/0.1__add_license_action_indexes.sql
Add missing index for `license_action` table
https://github.com/codenvy/codenvy/issues/1741
Added missing index for license_action table.
not required
not required
> CODENVY-1741: Add missing index for license_action table

- dashboard/src/app/account/details/account-delete.controller.ts
Signed-off-by: Anna Shumilova <ashumilova@codenvy.com>
Fixes the redirection to the page with account deleted message.
https://github.com/codenvy/codenvy/issues/2159
[UD] Fixed redirection on account deletion
N/A
N/A
> Fix redirection on account deletion page

- dashboard/src/components/api/test/codenvy-http-backend.ts
Fix backend according to https://github.com/eclipse/che/pull/5062
https://github.com/eclipse/che/issues/5059
--  Fix backend according to new branding request.
N/A
> CHE-5059 Fix backend according to new branding request

- assembly/assembly-wsmaster-war/src/main/java/com/codenvy/api/deploy/CodenvyWebSocketEndpoint.java
- assembly/assembly-wsmaster-war/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedMachineProviderImpl.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/HostedMachineProviderImplTest.java
- wsagent/codenvy-wsagent-core/src/main/java/com/codenvy/wsagent/server/CodenvyWebSocketEndpoint.java
Fixed dependency injection bindings and some FQNs to fit https://github.com/eclipse/che/pull/5005
> Unification of JSON RPC codebase

- dockerfiles/init/manifests/codenvy.env
https://github.com/codenvy/codenvy/issues/2189
> Fix codenvy.env snapshotting comments

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/swarm/client/SwarmDockerConnector.java
Adds additional error logging if docker image build fail with out of resources.
This is needed to easily detection of out of resources situation.
https://github.com/codenvy/codenvy/issues/2104
Added additional error logging if docker image build fail with out of resources.
N/A
N/A
> CODENVY-2104: Add additional error logging on docker image build fail

- dashboard/src/index.html
Extend footer branding stuff
https://github.com/eclipse/che/pull/5123
Extended footer branding stuff
We have extended the capabilities for customizing the footer used in the dashboard. It is now allowing to add two new buttons, for example to contact support or redirect to specific links.
N/A
> Extended footer's branding capabilities

- plugins/plugin-hosted/codenvy-hosted-ext-hosted/src/main/resources/com/codenvy/ide/hosted/client/HostedLocalizationConstant.properties
Fix documentation URL in Help menu
#2124 
Fix documentation URL in Help menu
N/A
> Fix documentation URL in Help menu

- dashboard/src/app/admin/user-management/user-management.controller.ts
- dashboard/src/app/admin/user-management/user-management.html
- dashboard/src/app/organizations/list-organizations/list-organizations.controller.ts
- dashboard/src/app/organizations/list-organizations/list-organizations.html
- dashboard/src/app/organizations/organization-details/organization-members/list-organization-members.controller.ts
- dashboard/src/app/organizations/organization-details/organization-members/list-organization-members.html
- dashboard/src/app/teams/team-details/team-members/list-team-members.controller.ts
- dashboard/src/app/teams/team-details/team-members/list-team-members.html
- dashboard/src/app/teams/team-details/team-members/member-item/member-item.html
- dashboard/src/app/teams/team-details/team-workspaces/list-team-workspaces.controller.ts
- dashboard/src/app/teams/team-details/team-workspaces/list-team-workspaces.html
- dashboard/src/app/workspace/share-workspace/share-workspace.controller.ts
- dashboard/src/app/workspace/share-workspace/share-workspace.html
- dashboard/src/app/workspace/share-workspace/user-item/user-item.html
- dashboard/src/components/typings/codenvy.d.ts
There were fixed all lists where items can be simultaneously selected and filtered.
https://github.com/eclipse/che/issues/4803
[UD] Fixed bug when bulk operations work wrong after items are filtered.
N/A - bugfix
N/A - bugfix
> CHE-4803: fix items bulk selection and filtration.

- dockerfiles/cli/scripts/cmd_start.sh
Add check on postgresql port in case of debug mode
#2112 
[cli] Add check on postgresql port in case of debug mode
N/A (bug)
N/A (bug)
> [cli] Add check on postgresql port in case of debug mode

- dashboard/src/app/onprem/license-messages/license-messages.service.ts
- dashboard/src/app/organizations/list-organizations/list-organizations.controller.ts
- dashboard/src/app/organizations/list-organizations/organizations-item/organizations-item.html
- dashboard/src/components/api/codenvy-permissions.factory.ts
Signed-off-by: Anna Shumilova <ashumilova@codenvy.com>
Tracks permission request status 403 and 404 (for system) to avoid loop with refetching, display delete sub-organization button for organization admin.
https://github.com/codenvy/codenvy/issues/2184
[UD] Display delete sub-organization button for organization admin.
N/A
N/A
> Track permissions error to avoid refetch

- pom.xml
- site/app/site/branding/product.json
- site/app/site/scripts/views/form.js
- site/app/site/scripts/views/login.js
resolves https://github.com/codenvy/codenvy/issues/2221
> show oauth buttons in defined order

- dashboard/src/app/index.module.ts
- dashboard/src/components/api/test/codenvy-http-backend.ts
If there is modification request and no CSRF token cached yet (may occur in tests or when GET requests loading time is rather long), then request token and use the result for this very modification request.
https://github.com/codenvy/codenvy/issues/2231
[dashboard] Added requesting CSRF token on modification request if is not cached yet.
N/A
N/A
> Request csrf token on modification request if not requested before

- site/app/site/scripts/models/account.js
- site/app/site/scripts/views/login.js
fixes https://github.com/codenvy/codenvy/issues/2235
> codenvy-2235 remove unused functionality

- wsmaster/codenvy-hosted-integration-tests/codenvy-integration-cascade-jpa/src/test/java/com/codenvy/integration/jpa/cascaderemoval/TestObjectsFactory.java
Fix build in accordance to changes from https://github.com/eclipse/che/pull/5203
> Fix build accordingly to changes from CHE-5060

- dashboard/src/app/admin/user-management/user-details/user-details.controller.ts
- dashboard/src/app/admin/user-management/user-management.controller.ts
- dashboard/src/app/organizations/list-organizations/list-organizations.controller.ts
Fix user details page for admin.
N/A
-- fix user details page for admin
N/A
> Fix user details page for admin

- dockerfiles/init/manifests/codenvy.pp
- dockerfiles/init/modules/codenvy/templates/general.properties.erb
allow to configure path to email blacklist file
https://github.com/codenvy/codenvy/issues/2247
allow to configure path to email blacklist file
> allow to configure path to email blacklist file

- dashboard/src/app/workspace/share-workspace/share-workspace.controller.ts
This PR adds ability to share personal workspaces for onprem.
https://github.com/codenvy/silexica/issues/51
[UD] added ability to share personal workspaces for onprem.
N/A - bugfix
N/A - bugfix
> SLX-51: allow to share personal workspaces for onprem

- dashboard/src/app/organizations/organization-details/organization-details.controller.ts
- dashboard/src/app/teams/list/team-item/team-item.controller.ts
- dashboard/src/app/teams/list/team-item/team-item.html
- dashboard/src/app/teams/team-details/team-details.controller.ts
- dashboard/src/app/teams/team-details/team-details.html
- dashboard/src/app/teams/teams-config.ts
- dashboard/src/components/api/codenvy-organizations.factory.ts
- dashboard/src/components/api/codenvy-team.factory.ts
Improve preselect tab condition for team details,  update team flow for UD.
https://github.com/codenvy/codenvy/issues/2207
https://github.com/codenvy/codenvy/issues/2079
- Improve preselect tab condition for team details for UD.
- Improve update team flow for UD.
N/A
N/A
> Improve  update team details for UD

- wsmaster/codenvy-hosted-mail-sender/src/main/java/com/codenvy/mail/MailSender.java
Adds date header to emails which are sent by dockerized Codenvy system. This sometimes prevents emails from getting into spam.
https://github.com/codenvy/codenvy/issues/1511
Added date header to emails
N/A
N/A
> CODENVY-1511: Add date header for emails

- dashboard/src/app/teams/team-details/team-details.html
Signed-off-by: Oleksii Orel <oorel@redhat.com>
Remove required attributes from 'RAM cap' inputs.
https://github.com/codenvy/codenvy/issues/2277
-- remove required attributes from 'RAM cap' inputs for UD.
N/A
N/A
> CODENVY-2277: remove required attributes from 'RAM cap' inputs

- dockerfiles/codenvy/Dockerfile
- dockerfiles/codenvy/open-jdk-source-file-location
Add notification file for openJDK.
https://github.com/codenvy/planning/issues/129
Add notification file for openJDK.
> add notification file for openJDK

- dashboard/src/app/teams/create-team/create-team.html
- dashboard/src/app/teams/team-details/team-owners/list-team-owners.html
Fix readonly attribute for input boxes.
-- fix readonly attribute for input boxes.
N/A
N/A
> fix readonly attribute for input boxes

- dashboard/src/app/teams/team-details/team-details.controller.ts
Signed-off-by: Anna Shumilova <ashumilo@redhat.com>
When user has no allowed actions - show message that he has no permissions to access team. 
https://github.com/codenvy/codenvy/issues/2289
Fixed validation for user's permissions to access team.
N/A
N/A
> codenvy-2289: fix team permission denied validation

- dashboard/bower.json
- dashboard/src/app/admin/user-management/user-management.html
- dashboard/src/app/billing/invoices/list-invoices.html
- dashboard/src/app/organizations/list-organizations/organizations-item/organizations-item.html
- dashboard/src/app/organizations/organization-details/organization-members/list-organization-members.html
- dashboard/src/app/teams/list/team-item/team-item.html
- dashboard/src/app/teams/team-details/team-members/member-item/member-item.html
- dashboard/src/app/workspace/share-workspace/user-item/user-item.html
Change angular-bootstrap version to 1.1.2
It needs for  https://github.com/eclipse/che/pull/5447
> change angular-bootstrap version to 1.1.2

- dashboard/src/app/billing/billing.controller.ts
- dashboard/src/app/billing/ram-info/more-ram-dialog.html
- dashboard/src/app/billing/ram-info/more-ram.controller.ts
Fix filter name in HTML file for UD.
> Fix round filter

- CHANGELOG.md
regenerate changelog
https://github.com/eclipse/che/issues/5595
regenerate changelog
> regenerate changelog

- CHANGELOG.md
Changelog for 5.15.0
https://github.com/codenvy/codenvy/issues/2327
Changelog for 5.15.0
> RELEASE: Update CHANGELOG

- pom.xml
> set actual parent version

- dockerfiles/swarm/Dockerfile
update swarm to 1.2.8
https://github.com/codenvy/codenvy/issues/2324
update swarm to 1.2.8
> update swarm to 1.2.8

- assembly/assembly-wsmaster-war/src/main/java/com/codenvy/api/deploy/CodenvyWebSocketEndpoint.java
- wsagent/codenvy-wsagent-core/src/main/java/com/codenvy/wsagent/server/CodenvyWebSocketEndpoint.java
Required for https://github.com/eclipse/che/pull/5775
> Implement mechanism for providing unique ids for JSON-RPC clients

- dashboard/bower.json
fixes broken codenvy build after https://github.com/eclipse/che/commit/8fcd5dcb37adafc819379d04cdc8e31a8599215a
> adapt to changes in che-dashboard

- assembly/assembly-wsmaster-war/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiServletModule.java
Fix up! Remove license filters.
not required
not required
not required
> Remove license filters

- plugins/plugin-hosted/codenvy-hosted-ext-hosted/src/main/java/com/codenvy/ide/hosted/client/action/OpenDocsAction.java
- plugins/plugin-hosted/codenvy-hosted-ext-profile/pom.xml
- plugins/plugin-hosted/codenvy-hosted-ext-profile/src/main/java/com/codenvy/ide/profile/client/action/RedirectToDashboardAccountAction.java
- plugins/plugin-hosted/codenvy-hosted-ext-support-help/src/main/java/com/codenvy/ide/support/help/client/action/RedirectToEngineerChatChannelAction.java
Signed-off-by: Vitalii Parfonov <vparfonov@redhat.com>
Replace Window.open() with JS native call
#2319
> Replace Window.open() with JS native call

- wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/permissions/OrganizationResourceDistributionServicePermissionsFilter.java
- wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/filters/WorkspacePermissionsFilter.java
- wsmaster/codenvy-hosted-recoverpassword/src/main/java/com/codenvy/service/password/RecoveryStorage.java
Fix some error prone cases
https://github.com/eclipse/che/issues/5829
Fix some error prone cases
Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>
> Fix some error prone cases

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedMachineProviderImpl.java
Adds additional logs if snapshot of workspace is not found on its start. It is needed to better understanding is this happens due to legal snapshot removing after specified in the docs period or it was an infrastructure or other problem.
https://github.com/codenvy/codenvy/issues/2284
> CODENVY-2284: Add additional logs

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedMachineProviderImpl.java
Hot fix: correct code formatting.
> CODENVY-2284 fix code formatting

- selenium/codenvy-selenium-test/src/test/resources/suites/CodenvyOnpremSuite.xml
Rename the name of test in the suite after renaming class
@tolusha @dmytro-ndp
> Change name of test class in the suite after renaming

- selenium/codenvy-selenium-test/src/test/resources/org/eclipse/che/selenium/assistant/key-bindings.txt
Adapts selenium test according to new changes in CHE
https://github.com/eclipse/che/issues/5925
> CHE-5925: Fix key binding test case

- plugins/plugin-bitbucket/codenvy-plugin-bitbucket-ext-bitbucket-client/src/main/java/org/eclipse/che/ide/ext/bitbucket/client/BitbucketSshKeyProvider.java
- plugins/plugin-bitbucket/codenvy-plugin-bitbucket-pullrequest/src/main/java/com/codenvy/plugin/pullrequest/client/BitbucketHostingService.java
- plugins/plugin-bitbucket/codenvy-plugin-bitbucket-pullrequest/src/test/java/com/codenvy/plugin/pullrequest/client/BitbucketHostingServiceTest.java
- plugins/plugin-microsoft/codenvy-plugin-microsoft-vsts-pullrequest/src/main/java/com/codenvy/plugin/pullrequest/client/MicrosoftHostingService.java
Adapt to https://github.com/eclipse/che/pull/6326
> Adapt to che/oauthkeycloak2

- selenium/codenvy-selenium-test/src/test/java/com/codenvy/selenium/assistant/CheckFindActionInCodenvyFeatureTest.java
Adds hotkeys into Find Action test expected list
https://github.com/eclipse/che/issues/5925
> Fix find action selenium test

- wsmaster/codenvy-hosted-api-node/pom.xml
remove redundant version declaration
remove redundant version declaration
> remove redundant version declaration

- dockerfiles/build.include
interupt build scripts for docker files if failure occurs
interupt build scripts for docker files if failure occurs
> interrupt build scripts for docker files if failure occurs

- dockerfiles/build.include
> fix docker images build

- selenium/codenvy-selenium-test/selenium-tests.sh
This request is about clearing target directory of selenium tests at start of test execution. It prevents us from having outdated result on CI.
https://github.com/eclipse/che/issues/6378
> Clean up target directory at start of selenium tests

- dockerfiles/init/modules/codenvy/templates/machine.properties.erb
Adds property from [this](https://github.com/eclipse/che/pull/6415) PR.
Added property from the upstream Che.
> Add property from the upstream Che

- selenium/codenvy-selenium-test/pom.xml
- selenium/codenvy-selenium-test/src/main/java/com/codenvy/selenium/core/OnpremSeleniumSuiteModule.java
- selenium/codenvy-selenium-test/src/test/java/com/codenvy/selenium/factory/AuthenticateAndAcceptFactoryThroughGitHubOAuthTest.java
Implements changes in **che-selenium-core** library which allows to obtain instances of _TestWorkspaceServiceClient_, _TestHttpJsonRequestFactory_ and _TestUser_ classes by using assisted injection.
https://github.com/eclipse/che/issues/6298
> Use Guice container to instantiate TestWorkspaceServiceClient class

- selenium/codenvy-selenium-test/src/test/resources/com/codenvy/selenium/preferences/editor
This request fixes selenium test **EditorSettingsTest**.
https://github.com/eclipse/che/issues/6346
> Fix editor settings test

- selenium/codenvy-selenium-test/src/test/resources/suites/CodenvyOnpremSuite.xml
The test has been renamed in CHE. We should also rename this one in codenvy suite for correct launching.
@tolusha, @dmytro-ndp, @skabashnyuk
> Rename the test in the testsuite

- selenium/codenvy-selenium-test/src/test/resources/suites/CodenvyOnpremSuite.xml
This tests have been removed from CHE we need to apply the same to Codenvy
> Remove unnecessary tests

- selenium/codenvy-selenium-test/src/test/resources/suites/CodenvyOnpremSuite.xml
- wsmaster/codenvy-hosted-api-admin/pom.xml
- wsmaster/codenvy-hosted-api-invite/pom.xml
- wsmaster/codenvy-hosted-api-organization/pom.xml
- wsmaster/codenvy-ldap/pom.xml
Rebase master branch on top of che-multiuser branch + fixes for eclipselink
note: I had to move some sql schema to "test" scope else it's reported as unused dependency
> Merge master branch into Che multiuser branch

- wsmaster/codenvy-hosted-integration-tests/codenvy-integration-tck-jpa/pom.xml
- wsmaster/codenvy-hosted-platform-api-impl/pom.xml
Fix integration tests following the merge of EclipseLink 2.7.0
> Fix integration tests with EclipseLink 2.7.0

- selenium/codenvy-selenium-test/src/main/java/com/codenvy/selenium/pageobject/site/LoginVSTS.java
- selenium/codenvy-selenium-test/src/test/java/com/codenvy/selenium/vsts/CheckWorkWithVSTSProviderTest.java
* Fix locator that has been changed on Microsoft page
* replace deprecated method
https://github.com/eclipse/che/issues/6455
> Fix tests  dependent on VSTS git provider

- selenium/codenvy-selenium-test/src/main/java/com/codenvy/selenium/pageobject/site/LoginVSTS.java
- selenium/codenvy-selenium-test/src/test/java/com/codenvy/selenium/vsts/CheckWorkWithVSTSProviderTest.java
Add new JavaTestPluginJunit4CheckRunSuitesAndScopesTest to the testsuite
> Add new test to codenvy testsuite

- dashboard/src/app/account/details/account.controller.ts
- dashboard/src/app/account/details/account.html
Signed-off-by: Oleksii Orel <oorel@redhat.com>
Fix saving profile flow.
https://github.com/codenvy/codenvy/issues/2445
--  Fix saving profile flow.
N/A
> CODENVY-2445 fix account profile form

- selenium/codenvy-selenium-test/src/main/java/com/codenvy/selenium/core/OnpremSeleniumSuiteModule.java
- selenium/codenvy-selenium-test/src/main/java/com/codenvy/selenium/core/entrance/OnpremEntranceImpl.java
- selenium/codenvy-selenium-test/src/main/java/com/codenvy/selenium/core/user/OnpremTestUserImpl.java
- selenium/codenvy-selenium-test/src/test/resources/suites/CodenvyOnpremSuite.xml
Fix bug with run selenium tests in the suite
> Che multiuser fix

- selenium/codenvy-selenium-test/src/main/java/com/codenvy/selenium/core/entrance/OnpremEntranceImpl.java
- selenium/codenvy-selenium-test/src/main/java/com/codenvy/selenium/pageobject/site/LoginAndCreateOnpremAccountPage.java
It adds verification of is login page opened when we go to the IDE/Dashboard from selenium tests in the same way, as it was done on [LoginPageEntrance](https://github.com/eclipse/che/blob/master/selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/entrance/LoginPageEntrance.java#L39).
#2476
> Check if there is a login page before login to Codenvy from selenium tests

- selenium/codenvy-selenium-test/src/test/java/com/codenvy/selenium/ssh/LoginBySshKeyTest.java
Resolve problem with test after merge che-multiuser to the master
Issue https://github.com/codenvy/codenvy/issues/2475
> Rework LoginBySshKeyTest 

- plugins/plugin-hosted/codenvy-machine-hosted/pom.xml
- wsmaster/codenvy-ldap/pom.xml
Apply fixes on source code due to maven plugins update
- maven dependency plugin: new missing dependencies
https://github.com/eclipse/che-parent/pull/31
N/A
N/A
> Apply fixes required when updating maven plugins

- selenium/codenvy-selenium-test/src/main/java/com/codenvy/selenium/pageobject/site/LoginAndCreateOnpremAccountPage.java
Fix problem with redirecting to the factory page after login, when webdriver.get() method used very fast several times one by one, this method does not work as we expected.
Issue https://github.com/codenvy/codenvy/issues/2477
> Fix problem with redirecting to the factory page after login

- selenium/codenvy-selenium-test/src/test/resources/suites/CodenvyOnpremSuite.xml
- **WorkspaceDetailsTest** added to **CodenyOnpremSuite.xml**
- **CheckRestoringOfSplitEditor** renamed to **CheckRestoringSplitEditorTest** in **CodenyOnpremSuite.xml**
> Changes in CodenyOnpremSuite test suite

- selenium/codenvy-selenium-test/pom.xml
Signed-off-by: Vitalii Parfonov <vparfonov@redhat.com>
Fix filed build: add missing dependency
> Add missing dependency

- selenium/codenvy-selenium-test/src/test/java/com/codenvy/selenium/factory/AuthenticateAndAcceptFactoryThroughGitHubOAuthTest.java
Rework cleanup after test .
Issue https://github.com/codenvy/codenvy/issues/2471
> Rework AuthenticateAndAcceptFactoryThroughGitHubOAuthTest 

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedMachineProviderImpl.java
- plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/HostedMachineProviderImplTest.java
Update for che changes on PR https://github.com/eclipse/che/pull/6856
https://github.com/eclipse/che/pull/6856
N/A
N/A
Change-Id: I98cc6da238fe7a099a86e4389648cdf3eb728f15
> Update for Eclipse Che changes on PR https://github.com/eclipse/che/pull/6856

- assembly/assembly-dashboard-war/pom.xml
- assembly/assembly-ide-war/pom.xml
- assembly/assembly-website-war/pom.xml
- assembly/assembly-wsagent-war/pom.xml
- assembly/assembly-wsmaster-war/pom.xml
Add versions for dynamodule maven plugin
> Add version to dynamodule plugin

- selenium/codenvy-selenium-test/src/test/java/com/codenvy/selenium/ssh/LoginBySshKeyTest.java
It fixes **LoginBySshKeyTest** selenium test to comply changes in Che.
https://github.com/eclipse/che/issues/7018
> Fix LoginBySshKeyTest to comply changes in Che

- selenium/codenvy-selenium-test/src/test/java/com/codenvy/selenium/dashboard/CodenvyWorkspaceDetailsTest.java
- selenium/codenvy-selenium-test/src/test/resources/suites/CodenvyOnpremSuite.xml
We need create **CodenvyWorkspaceDetailsTest** selenium test for testing the **workspace details** feature on Codenvy.
This test is almost copy the **WorkspaceDetailsTest** selenium test from **CHE** except that there is not checking the **Yaml language server** on the **Agents** tab.
> Add a selenium test for testing the workspace details feature on Codenvy

- dockerfiles/init/modules/codenvy/templates/machine.properties.erb
fixes: https://github.com/codenvy/codenvy/issues/2563
> Add missing property

- selenium/codenvy-selenium-test/src/test/java/com/codenvy/selenium/dashboard/CodenvyWorkspaceDetailsTest.java
- selenium/codenvy-selenium-test/src/test/java/com/codenvy/selenium/factory/AuthenticateAndAcceptFactoryThroughGitHubOAuthTest.java
This PR reworks **CodenvyWorkspaceDetailsTest** and **AuthenticateAndAcceptFactoryThroughGitHubOAuthTest** selenium tests according to changes in dashboard page objects
https://github.com/eclipse/che/issues/6686
This PR will be merged after merging https://github.com/eclipse/che/pull/7757.
> Selenium: Rework selenium tests according to changes in dashboard page objects

- dashboard/src/app/navbar/codenvy-navbar.html
This PR add locators to **Codenvy** navbar web page(codenvy-havbar.html).
> Selenium: add locators to Codenvy navbar

- selenium/codenvy-selenium-test/src/test/java/com/codenvy/selenium/assistant/CheckFindActionInCodenvyFeatureTest.java
This PR changes expected output of the Find Action feature which tests by CheckFindActionInCodenvyFeatureTest selenium test like in che6 branch.
https://github.com/eclipse/che/issues/7504
> Selenium: apply changes to CheckFindActionInCodenvyFeatureTest selenium test from che6 branch

- dashboard/bower.json
- pom.xml
switch to che legacy tag
needed for: https://github.com/codenvy/codenvy/issues/2583
> switch to che legacy tag

- plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/agent/launcher/MachineInnerRsyncAgentLauncherImpl.java
Logs ram limit when machine is deployed
> Log ram limit when machine is deployed

- wsmaster/codenvy-hosted-sso-auth-bearer/pom.xml
- wsmaster/codenvy-hosted-sso-auth-bearer/src/main/java/com/codenvy/auth/sso/server/EmailValidator.java
Re-reading blacklist file on account creating (as long as blacklist file has been modified), instead of doing scheduled re-read
https://github.com/codenvy/codenvy/issues/2617
> Re-read user blacklist before every account creation
