cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECSingleServerHelper.java
@tolusha: please, review my request. on-prem
This fix will allow to avoid situation when, after installing Codenvy, there will be next content of /etc/hosts initially without EOF at the end:
> 127.0.0.1 localhost127.0.0.1 puppet
=> Add hosts into the /etc/hosts of Codenvy on-prem from the new line

core/codenvy-hosted-workspace-activity/src/main/java/com/codenvy/activity/server/WorkspaceActivityManager.java
Perform update, and then stop workspace.
Stopping will asynchronously update workspace, so make sure there will be our attribute.
=> Fix workspace updating on stop by timeout

core/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/ErrorCodes.java, core/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/workspace/LimitExceededException.java, core/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManager.java
Server response example:
```json
{
"attributes":{
"workspaces_count":"1",
"used_ram":"1",
"used_ram_unit":"gb",
"free_ram":"0",
"free_ram_unit":"gb"
},
"errorCode":10000,
"message":"There are 1 running workspaces consuming 1GB RAM. Your current RAM limit is 0GB. You can stop other workspaces to free resources."
}
{  
"attributes":{  
"environment_max_ram":"16384",
"environment_max_ram_unit":"mb",
"environment_ram":"32000",
"environment_ram_unit":"mb"
},
"errorCode":10000,
"message":"The maximum RAM per workspace is set to '16384mb' and you requested '32000mb'. This value is set by your admin with the 'limits.workspace.env.ram' property"
}
```
=> CODENVY-1938: Add error code & attributes for limit exception

assembly/onpremises-ide-packaging-tomcat-ext-server/src/assembly/assembly.xml, assembly/onpremises-ide-packaging-war-ext-server/src/main/java/com/codenvy/ext/java/server/MachineServletModule.java, assembly/onpremises-ide-packaging-war-ide-resources/src/main/webapp/initializer/init.js
Changed workspace agent war name from "api.war" to "wsagent.war"
@eivantsov We might need to update docs for Codenvy.
=> CODENVY-349 Rename workspace agent packaged war name

analytics/analytics-application/src/main/webapp/WEB-INF/web.xml, analytics/analytics-tomcat-local-pkg/src/main/resources/analytics-application-basic-auth.web.xml, assembly/onpremises-ide-packaging-war-ext-server/src/main/webapp/WEB-INF/web.xml, assembly/onpremises-ide-packaging-war-ide-resources/src/main/webapp/WEB-INF/web.xml, assembly/onpremises-ide-packaging-war-ide/src/main/webapp/WEB-INF/web.xml, assembly/onpremises-ide-packaging-war-platform-api/src/main/webapp/WEB-INF/web.xml, core/codenvy-hosted-mail-server/src/main/webapp/WEB-INF/web.xml
1. CodenvyBootstrap
2. ExpirableCache
3. Deprecated methods in org.eclipse.che.commons.lang.IoUtil# modified: analytics/analytics-application/src/main/webapp/WEB-INF/web.xml
4. NamedThreadFactory
5. org.eclipse.che.commons.lang.cache.*
=> CHE-1061 Remove deprecations

core/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/dao/mongo/MongoDBFactoryStore.java
Sometimes query attribute values can contain dots ("creator.userId" : "admin@codenvy.onprem").
It must be escaped, as it is stored in DB.
=> CODENVY-292 Escape factory DB query attributes

cdec/installation-manager-cli-bundle/src/main/java/com/codenvy/im/cli/command/AbstractIMCommand.java, cdec/installation-manager-cli-bundle/src/main/java/com/codenvy/im/cli/command/DownloadCommand.java, cdec/installation-manager-cli-bundle/src/main/java/com/codenvy/im/cli/command/VersionCommand.java, cdec/installation-manager-cli-bundle/src/test/java/com/codenvy/im/cli/command/TestDownloadCommand.java, cdec/installation-manager-cli-bundle/src/test/java/com/codenvy/im/cli/command/TestVersionCommand.java, cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/AbstractArtifact.java, cdec/installation-manager-core/src/main/java/com/codenvy/im/facade/IMArtifactLabeledFacade.java, cdec/installation-manager-core/src/main/java/com/codenvy/im/facade/IMCliFilteredFacade.java, cdec/installation-manager-core/src/main/java/com/codenvy/im/facade/InstallationManagerFacade.java, cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/ConfigManager.java, cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/DownloadManager.java, cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestAbstractArtifact.java, cdec/installation-manager-core/src/test/java/com/codenvy/im/facade/IMArtifactLabeledFacadeTest.java, cdec/installation-manager-core/src/test/java/com/codenvy/im/facade/TestInstallationManagerFacade.java, cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/DownloadManagerTest.java, cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/TestConfigManager.java, cdec/installation-manager-server-war/src/main/java/com/codenvy/im/service/InstallationManagerService.java, cdec/installation-manager-server-war/src/test/java/com/codenvy/im/service/InstallationManagerServiceTest.java, cdec/installation-manager-tests/src/main/resources/bin/im-download/test-download-all-updates.sh
Issues:
1) add '--list-remote' option of 'im-download' command to display all available versions in reverse order
2) fix setting proxy settings in codenvy properties when there is no http(s)_proxy environment variables.
=> Codenvy 473: fix IM according to TIAA CREF requests

cdec/installation-manager-core/src/main/java/com/codenvy/im/commands/CommandLibrary.java, cdec/installation-manager-core/src/test/java/com/codenvy/im/commands/TestCommandLibrary.java, cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-update-single-node-from-binary-with-codenvy4.sh
=> CODENVY-543: replace '&' on '\&' in right part of sed command

assembly/onpremises-ide-packaging-war-ext-server/pom.xml, pom.xml, wsagent/pom.xml, wsagent/wsagent-codenvy/pom.xml
During assembly wsagent artifact, warnings occurs, to avoid that we shoud use correct group id for ws agent parent and wsagent codenvy artifacts.
@skabashnyuk
=> Fix maven groupid for wsagent artifact

cdec/installation-manager-core/pom.xml, cdec/installation-manager-tests/src/main/resources/bin/config.sh, cdec/upload-installation-manager.sh
Replace codenvy-dev.com SaaS server on a1.codenvy-dev.com in integration tests.
=> Replace codenvy-dev.com SaaS server on a1.codenvy-dev.com

assembly/onpremises-ide-packaging-war-factory/src/main/java/com/codenvy/onpremises/factory/deploy/FactoryServletModule.java, assembly/onpremises-ide-packaging-war-factory/src/main/java/com/codenvy/onpremises/factory/filter/RemoveIllegalCharactersFactoryURLFilter.java, assembly/onpremises-ide-packaging-war-factory/src/test/java/com/codenvy/onpremises/factory/filter/FactoryUrlFormatterFilterTest.java
After migration of user names all the factory URLs that contains the old names e.g("user@mail.com") became invalid, this pr should fix this problem.
@skabashnyuk, @garagatyi
=> CODENVY-666: Fix accepting of the factories by the existing URLs

cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
CODENVY-706: check if there is subscription-manager command in RHEL OS when checking subscription in Codenvy bootstrap script.
=> CODENVY-706: check if there is subscription-manager command in RHEL OS

.gitignore, assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java, plugins/plugin-hosted/codenvy-machine-hosted/pom.xml, plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedDockerInstanceProvider.java, plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/MaintenanceConstraintProvider.java, plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/HostedDockerInstanceProviderTest.java
This and [this](https://github.com/eclipse/che/pull/1705) PRs add ability to mark node for maintenance (it means that new containers won't start on this node).
To mark node for maintenance just add com.codenvy.node-state=maintenance label to docker on the node.
To return node to normal state just remove the label.
To add label to docker:
1. edit docker config file, add label
2. reload (without restart!) docker config (use SIGHUP signal)
Note, that it can take about a minute or so while swarm "see" the label.
To remove label just erase it from config and reload it again.
=> CODENVY-413: Make it possible to mark MachineNode as 'sheduled for maintenace'

core/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/dao/mongo/SnapshotImplCodec.java, core/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/dao/mongo/WorkspaceDaoImpl.java, core/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/dao/mongo/WorkspaceImplCodec.java, core/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/dao/mongo/stack/StackDaoImpl.java, core/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/dao/mongo/SnapshotDaoImplTest.java, core/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/dao/mongo/StackDaoImplTest.java, core/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/dao/mongo/WorkspaceDaoImplTest.java
change MachineConfigImpl field 'isDev' to 'dev', as it is done in MachineConfigDto.
It should fix consitensy problems.
Also it needs to make migrations of existing workspaces.
=> CODENVY-651 Use 'dev' instead 'isDev' for machine configs in Mongo

assembly/onpremises-ide-packaging-war-ext-server/src/main/webapp/WEB-INF/classes/codenvy/che-machine-configuration.properties
Fixes cloning projects from VSTS
Now VSTS URL's may or may not contains the collection name, e.g.:
with collection:
https://che-1.visualstudio.com/DefaultCollection/test/_git/che-core
without collection:
https://iedexmain1.visualstudio.com/_git/MyFirstProject
#449 
No
None
=> CODENVY-449; fix VSTS project URL matching regexp

plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/swarm/client/SwarmDockerConnector.java
Fix NPE in `SwarmDockerConnector`, which broke catch chain on create machine error
[Fix](https://github.com/codenvy/codenvy/issues/411) wrong "Machine with name _machine-name_ already exists" error message and fix the cause of next fails of this workspace to start
Sometimes shows useless error message  if creation of a machine fails and breaks next workspace starts
Displays actual error message instead of "Machine with name _machine-name_ already exists"
No
=> CODENVY-411: Fix bug machine with name ws-machine already exists

plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/backup/WorkspaceFsBackupScheduler.java, plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/backup/WorkspaceFsBackupSchedulerTest.java
Handle machine not found exception in backup scheduler
#454
Logged error about attempt to backup stooped machine 
Just skip backup in such case, because it is normal behaviour
Yes
=> CODENVY-454: Remove error log when machine was stopped while its backup task was in executor queue

core/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/dao/ldap/ProfileAttributesMapper.java
This pull request fix clean up 'lastName' profile attribute in case partial update by json which does not contains attribute 'lastName'
https://github.com/codenvy/codenvy/issues/451
If map with changes contains `lastName` attribute with empty value or null, we replace it to `<none>`. But if map does not contains `lastName` attribute we replace 'lastName' value to `<none>` too.
We set `<none>` for lastName only if json with changes contains `lastName` attribute and it has null or empty value.
No
1.  API changes: without changes.
@sleshchenko @evoevodin review please.
=> codenvy-451: Fix clean up 'lastName' profile attribute.

plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/steps/PushBranchOnOriginStep.java
Fixes creation of pull requets into the own repo (when no forking performed)
#483
PR creation fails
PR creation OK
No
Nope
=> CODENVY-483; fix PR creation from own repo by sending name of origin

cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh, cdec/installation-manager-tests/src/main/resources/bin/install/test-install-im-cli.sh, cdec/installation-manager-tests/src/main/resources/bin/lib.sh
@TylerJewell, @riuvshin: please. review this request.
Please, take into account that warning message in output was slightly changed to handle parameters with value, flags and typos, for example:
> [vagrant@dev ~]$ ./install-codenvy.sh --http-proxy=http://test --unknown typo
=> (#404) validate options of Codenvy bootstrap script

dashboard/src/app/account/details/account-delete.controller.js
Does the redirection to account deleted page
Part of issue - https://github.com/codenvy/codenvy/issues/389
After account was deleted - we were redirecting user to account creation page
After account was deleted - the user is redirected to account deletion page
=> Add redirect to account deleted page

plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/vcs/hosting/NoVcsHostingServiceImplementationException.java
the constructor’s javadoc must have been copypasted (or whatever).
=> corrected javadoc

core/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/filters/WorkspacePermissionsFilter.java, core/codenvy-hosted-api-workspace/src/test/java/com/codenvy/api/workspace/server/filters/WorkspacePermissionsFilterTest.java, core/codenvy-hosted-machine-authentication/src/test/java/com/codenvy/machine/authentication/server/interceptor/MachineTokenInterceptorTest.java, core/codenvy-hosted-platform-api-impl/pom.xml, core/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManager.java, core/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManagerTest.java
- Adapt source code to changes of [Account API](https://github.com/eclipse/che/pull/1990)
- Rework permissions checking in according to new namespace concept
https://github.com/eclipse/che/issues/1989
Earlier filter checked permissions only by subject to wit by link workspace and user with worker.
User will be able to do anythink with workspace if it has namespace that equals to user's name
Yes
=> CHE-1989 Fix permissions checking in according to new namespace concept

dashboard/src/app/factories/create-factory/create-factory.html, dashboard/src/app/workspace/share-workspace/share-workspace.controller.js, dashboard/src/app/workspace/share-workspace/share-workspace.html, dashboard/src/app/workspace/share-workspace/share-workspace.styl
Adds message "User with email [email] not found. Workspaces can be shared with registered users only." when unregistered email is passed.
Issue - https://github.com/codenvy/codenvy/issues/509
No message was shown
A message show show up - User with email noname@codenvy.com not found. Workspaces can be shared with registered users only.
=> CODENVY-509: add user not found message in share workspace widget

cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh, cdec/installation-manager-tests/src/main/resources/vagrant/single-codenvy4-with-additional-nodes/RHEL7/Vagrantfile, cdec/installation-manager-tests/src/main/resources/vagrant/single/RHEL7/Vagrantfile
It replaces 'netstat' command by 'ss' so as first one is deprecated and not available on some CentOS 7.
=> (#560) replace deprecated 'netstat' command by 'ss'

plugins/plugin-hosted/codenvy-hosted-ext-factory/src/main/java/com/codenvy/ide/factory/client/welcome/GreetingPartPresenter.java
GreetingPartPresenter should not implement org.eclipse.che.ide.api.parts.HasView since it has been removed in CHE IDE.
@vparfonov or @skabashnyuk I need your OK
=> Update according to the IDE API changes

cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh, cdec/installation-manager-tests/src/main/resources/bin/lib.sh
Request contains:
1) fixup of integration tests which produces error 'ss: command not found';
2) turning off post-flight codenvy installation check because of an issue https://github.com/eclipse/che/issues/2284 which causes an error:
=> Installation manager minor fixup

cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
Turn on post-flight installation check after the issue https://github.com/eclipse/che/issues/2284 was done.
=> Turn on post-flight installation check

assembly/onpremises-ide-packaging-war-ext-server/src/main/java/com/codenvy/ext/java/server/MachineModule.java
Removed ApiEndpointProvider to avoid duplication with environment binding
https://github.com/eclipse/che/pull/2175#issuecomment-241783644
=> Removed ApiEndpointProvider to avoid duplication

dashboard/src/app/navbar/codenvy-navbar.html, dashboard/src/app/navbar/navbar.controller.js, dashboard/src/index.html
Adds stacks navbar menu item. Fixes codemirror used dependencies.
https://github.com/eclipse/che/issues/2206
=> CHE-2206: add stacks item to navbar menu and add codemirror plugins

plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/ContributionExtension.java, plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/ContributionMixinProvider.java, plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/inject/PullRequestGinModule.java
Instruct contribution extension to setup mixin before resource registration (in our case project resource).
Previous version of code base registered resource on selection change and in some case it failed due to project type resolving after import phase.
Related issue: https://github.com/codenvy/codenvy/issues/707
@vparfonov review it, plz.
=> Provide contribution mixin before resource has been loaded

assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiServletModule.java, pom.xml, wsmaster/codenvy-ldap/pom.xml, wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/LdapSynchronizerPermissionsFilter.java, wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/sync/LdapSynchronizerServiceTest.java
Allows/rejects synchronization based on `MANAGE_CODENVY_ACTION` existence.
@skabashnyuk, @sleshchenko please review
=> Add permissions filter for LdapSynchronizerService

wsmaster/codenvy-ldap/README.md, wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/LdapSynchronizer.java, wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/sync/LdapSynchronizerTest.java
Removes all the characters from the ldap user identifier except of those which are in `a-zA-Z0-9-_` set
=> Normalize ldap user identifier

cdec/installation-manager-core/src/main/java/com/codenvy/im/commands/CommandLibrary.java, cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/NodeManager.java, cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/helper/NodeManagerHelper.java, cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/helper/NodeManagerHelperCodenvy4Impl.java, cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/TestNodeManager.java, cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/helper/TestNodeManagerHelperCodenvy4Impl.java, cdec/installation-manager-tests/src/main/resources/bin/codenvy/install/test-install-single-node-behind-the-proxy.sh, cdec/installation-manager-tests/src/main/resources/bin/codenvy/node/test-add-remove-codenvy-nodes.sh, cdec/installation-manager-tests/src/main/resources/vagrant/single-with-additional-nodes/CentOS7/Vagrantfile
List of points:
1) fix absolute value of **certname** property in _/etc/puppet/puppet.conf_ on machine node;
2) update _/etc/puppet/autosign.conf_ with new machine node hostnames on master;
3) update *$swarm_node* variable in _/etc/puppet/manifests/nodes/codenvy/codenvy.pp_ on master  with new machine node hostnames;
4) check if existed nodes with new hostname are available before changing hostname.
=> (#456) fix update of hostname of Codenvy on-prem with machine nodes

platform-api-client-java/api/src/main/java/com/codenvy/client/model/User.java, platform-api-client-java/core/src/main/java/com/codenvy/client/core/model/DefaultUser.java, platform-api-client-java/core/src/test/java/com/codenvy/client/core/UserClientIT.java
Removes password field from DefaultUser and thereby corrects the error during user login
#826 
@dmytro-ndp, @skabashnyuk please take a look.
=> CODENVY-826: Fix login to Codenvy through IM CLI

cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECSingleServerHelper.java, cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifact.java, cdec/installation-manager-tests/src/main/resources/bin/codenvy/backup/test-backup-restore-single-node.sh, cdec/installation-manager-tests/src/main/resources/bin/codenvy/install/test-install-single-node-behind-the-proxy.sh, cdec/installation-manager-tests/src/main/resources/bin/codenvy/update/test-update-single-node-from-binary.sh, cdec/installation-manager-tests/src/main/resources/bin/codenvy/update/test-update-single-node.sh, cdec/installation-manager-tests/src/test/resources/MainSuite.xml
1. Switch off integration testing of Codenvy on-prem 3.x
2. Take into account replacement 'YOUR_DNS_NAME' on 'codenvy.onprem' in default manifest.
=> Installation manager fixup.

cdec/installation-manager-core/src/test/java/com/codenvy/im/commands/decorators/BaseTestPuppetErrorInterrupter.java, cdec/installation-manager-core/src/test/java/com/codenvy/im/testhelper/ssh/SshServerFactory.java, cdec/installation-manager-core/src/test/java/com/codenvy/im/utils/TestHttpTransport.java, cdec/installation-manager-core/src/test/resources/logback-test.xml
Tests of **installation-manager-core** project which are fixed by this request:
```
Tests run: 778, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 99.598 sec <<< FAILURE! - in TestSuite
testInterruptWhenAddErrorOnNode(com.codenvy.im.commands.decorators.TestPuppetErrorInterrupterOnNode)  Time elapsed: 3.399 sec  <<< FAILURE!
java.lang.AssertionError: mockCommand should be interrupted by spyInterrupter, but wasn't
at org.testng.Assert.fail(Assert.java:94)
at com.codenvy.im.commands.decorators.TestPuppetErrorInterrupterOnNode.testInterruptWhenAddErrorOnNode(TestPuppetErrorInterrupterOnNode.java:164)
Results :
Failed tests: 
TestPuppetErrorInterrupterOnNode.testInterruptWhenAddErrorOnNode:164 mockCommand should be interrupted by spyInterrupter, but wasn't
Tests run: 778, Failures: 1, …
```
=> Fix unit tests of IM CLI

cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
This request fixes error: 
> 'Call on rest url /api/workspace?account= returned invalid response code (401) with error:User not authorized to call this method.'
=> Fix bootstrap script to work around new admin name/password properties

lib/websocket-terminal/pom.xml
no need to have glibc installed for example (some "small in size" linux distributions don't have it by default like Alpine)
it's a backport of che change https://github.com/eclipse/che-lib/pull/14
run terminal go in alpine where glibc is not installed by default
error if glibc is not installed
it works
No
Change-Id: Iae715a460c1f09d11a16865d4f113d205fc7170c
=> Use go flags to compile binaries in static mode

cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECSingleServerHelper.java, cdec/installation-manager-core/src/main/java/com/codenvy/im/commands/CommandLibrary.java, cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/BackupConfig.java, cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/BackupManager.java, cdec/installation-manager-core/src/main/java/com/codenvy/im/utils/TarUtils.java, cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifact.java, cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/TestBackupConfig.java, cdec/installation-manager-core/src/test/java/com/codenvy/im/managers/TestBackupManager.java
Fix bug when Codenvy Installation manager backup fails on long file path in workspace
@tolusha: please, review this pull request.
=> Fix backup command of IM CLI to work with long file names in workspaces

wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/MembershipSelector.java
Adds range based search by group during sync when it's needed, e.g. ```member;range=1000-1500```
CODENVY-924
=> CODENVY-924; add range based search by group during sync

plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/ContributionExtension.java
Fix the npe while stopping the workspace without projects.
this side effect was the result of https://github.com/codenvy/codenvy/pull/768
@skabashnyuk, @evoevodin, @vitaliy-guliy please take a look.
=> Add check for makes sure that last selected project not null

plugins/plugin-github/codenvy-plugin-github-pullrequest/src/main/java/com/codenvy/plugin/pullrequest/client/GithubStagesProvider.java
Fix missing flag in Pull request status panel when pull request is successfully updated. 
https://github.com/codenvy/codenvy/issues/518
@vparfonov Please review
=> CODENVY-518: Fix wrong pull request update status

wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/OrganizationJpaModule.java, wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/spi/impl/OrganizationImpl.java, wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/spi/jpa/JpaOrganizationDao.java, wsmaster/codenvy-hosted-api-organization/src/test/java/com/codenvy/organization/spi/jpa/RemoveSuborganizationsBeforeParentOrganizationRemovedEventSubscriberTest.java, wsmaster/codenvy-hosted-api-organization/src/test/java/com/codenvy/organization/spi/tck/OrganizationDaoTest.java, wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/spi/jpa/JpaWorkerDao.java, wsmaster/codenvy-hosted-integration-tests/codenvy-integration-cascade-jpa/src/test/java/com/codenvy/integration/jpa/cascaderemoval/JpaEntitiesCascadeRemovalTest.java
Reworks automatically removing of suborganizations by using preRemove event instead of cascade removing. It is needed because cascade remove doesn't throw pre remove event for suborganization in this case. As result we can't remove root organization because members of suborganization will not be removed.
Yes
=> Use preRemove event instead of cascade remove for automatically removing of suborganizations

lib/websocket-terminal/src/main/go/server.go
https://github.com/eclipse/che/issues/1518
After click close button user will see in the list of processes terminal (/bin/bash) zombie process 
No
1.  API changes  : without changes
2.  User docs changes  : without changes
=> che-1518: Fix creation zombie prosess when user closes terminal.

cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
It fixes error of storing _docker_cluster_advertise_ property in **codenvy.properties** after entering it by user in time of executing of bootstrap script (issue #922).
=> Fix bootstrap script error of storing docker_cluster_advertise property

dashboard/src/app/onprem/license-nag-message-management/nag-message.controller.ts, dashboard/src/components/ims/ims-license.factory.ts
Fix license legality check.
https://github.com/codenvy/codenvy/issues/1009
=> CODENVY-1009: fix license legality check

wsmaster/codenvy-hosted-sso-client/src/main/java/com/codenvy/auth/sso/client/MachineSessionInvalidator.java, wsmaster/codenvy-hosted-sso-client/src/test/java/com/codenvy/auth/sso/client/MachineSessionInvalidatorTest.java
Fix possible NPE in MachineSessionInvalidator, when on workspace stop it removes tokens, and invalidate related sessions.
https://github.com/codenvy/codenvy/issues/602
Check session for being a null before attempting to invalidate it.
Yes
=> CODENVY-602 Avoid NPE when ending sessions of stopped workspaces

wsmaster/codenvy-ldap/README.md, wsmaster/codenvy-ldap/pom.xml, wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/LdapModule.java, wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/DBHelper.java, wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/DBUserFinder.java, wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/DBUserFinderProvider.java, wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/LdapSynchronizer.java, wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/sync/LdapSynchronizationFlowTest.java, wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/sync/LdapSynchronizerTest.java, wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/sync/UserFinderTest.java
Adds more configuration options to the `LdapSyncrhonizer`.
The options are:
- new attribute for linking users, it can be _id_ or _email_
- new attribute for disabling users update when such users already exist
- new attribute for disabling users removal when users exist in db while missing from ldap storage
Also there are 3 new fileds in synchronization result:
-  up-to-date - users who don't need to be synchronized as they are the same in ldap and db
-  skipped - users who were fetched from ldap storage and were skipped by synchronizer due to configuration options
- processed - the count of the processed users(fetched from ldap).
Moreover now we count not valid users as failed to synchronize.
@skabashnyuk, @sleshchenko, @akorneta please review
=> Exdent LdapSynchronizer functionality

assembly/onpremises-ide-packaging-war-platform-api/src/main/webapp/WEB-INF/web.xml, dashboard/src/app/factories/load-factory/load-factory.controller.ts, dashboard/src/components/api/codenvy-system.factory.ts
Removes workspace id from websocket connection path to master.
https://github.com/eclipse/che/issues/1787
Separate web-socket connection was created for each workspase.
All workspaces are using one web-socket connection.
@vparfonov @akurinnoy @ashumilova Please review
=> CHE-1787: Remove workspace id from websocket connection path to master

cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh, cdec/installation-manager-tests/src/main/resources/bin/codenvy/install/test-install-single-node-behind-the-proxy.sh, cdec/installation-manager-tests/src/main/resources/bin/config.sh, cli/assembly/src/main/resources/bin/unix/codenvy
For issue #886:
- fix regexp to parse proxy url with trailing slash
- remove trailing slash from the docker registry mirror
- update integration tests
=> Work around trailing slash in proxy url and dosker registry mirror url

cdec/installation-manager-tests/src/main/resources/bin/codenvy/node/test-add-remove-codenvy-nodes.sh, dashboard/src/app/admin/onprem-administration/yourlicense/yourlicense.html, dashboard/src/app/onprem/license-nag-message-management/nag-message.html, dashboard/src/components/ims/ims-license.factory.ts, wsmaster/codenvy-hosted-license-shared/src/main/java/com/codenvy/api/license/CodenvyLicense.java, wsmaster/codenvy-hosted-license-shared/src/test/java/com/codenvy/api/license/CodenvyLicenseTest.java
For issue https://github.com/codenvy/enterprise/issues/13:
1) Allow adding new machine node when there is no default Codenvy license, and after evaluation license expires.
2) Set maximum number of free users to 3.
3) Ensure reference to Fair Source 3 in product links to this page: https://codenvy.com/legal/fair-source/
@tolusha, @ashumilova: please, review this request.
=> Change limitations of Codenvy on-prem license

cdec/installation-manager-core/src/main/java/com/codenvy/im/artifacts/helper/CDECSingleServerHelper.java, cdec/installation-manager-core/src/test/java/com/codenvy/im/artifacts/TestCDECArtifact.java, cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh
- Fix error of removing trailing slash from docker-registry-mirror option (#886).
- Fix add node command to not hang up on reading _api.endpoint_ property in **general.properties** file.
=> Minor fixes of Installation Manager CLI and bootstrap script.

cdec/installation-manager-cli-bundle/src/test/java/com/codenvy/im/cli/command/TestInstallCommand.java, cdec/installation-manager-resources/src/main/resources/im-scripts/install-codenvy.sh, cdec/installation-manager-tests/src/main/resources/bin/codenvy/install/test-install-single-node-and-update-codenvy-config.sh
- Fix bootstrap script to reflect movement _che-test_ and _che-ip_ images from **codenvy** to **eclipse** namespace.
- Check **api.endpoint** property of IM Server instead if non-exists **che.api** in integration tests.
- Fix unit test com.codenvy.im.cli.command.TestInstallCommand.
=> Minor changes of installation manager

dockerfiles/cli/cli.sh, modules/compose/templates/docker-compose.yml.erb
needed for: https://github.com/codenvy/codenvy/issues/1156
- compose now used images with versions from `images` manifest file.
- improved dev mode, now it prints really needed puppet output to console.
- remove unnecessary sed commands
@TylerJewell @garagatyi Please take a look.
=> use images names and versions from manifest file for particular version

wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/PermissionsManager.java, wsmaster/codenvy-hosted-api-permission/src/test/java/com/codenvy/api/permission/server/PermissionsManagerTest.java
Fix checking of existence last 'setPermissions' action before permissions changing
Yes
=> Fix checking of existence last 'setPermissions' action before permissions changing

wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/filters/WorkspacePermissionsFilter.java, wsmaster/codenvy-hosted-api-workspace/src/test/java/com/codenvy/api/workspace/server/filters/WorkspacePermissionsFilterTest.java
makes users with "manageCodenvy" permissions to stop and get by key workspace of any user
https://github.com/codenvy/codenvy/issues/921
Yes
=> Allow users with manageCodenvy permission to stop/get info of any workspace

assembly/onpremises-ide-packaging-war-platform-api/pom.xml, assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java, pom.xml, wsmaster/codenvy-hosted-api-resource/pom.xml, wsmaster/codenvy-hosted-api-resource/src/test/java/com/codenvy/resource/api/ram/WorkspaceRamConsumerTest.java, wsmaster/codenvy-hosted-platform-api-impl/pom.xml, wsmaster/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManagerTest.java, wsmaster/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/workspace/TestObjects.java
Add deserializer for 'command' field ComposeServiceImpl. Create separated docker compose module.
https://github.com/eclipse/che/issues/2365
=> CHE-2365: Add deserializer for 'command' field ComposeServiceImpl.

codenvy.env, dockerfiles/cli/cli.sh, docs/README.md, manifests/codenvy.pp, modules/codenvy/templates/codenvy.env.erb
needed for: https://github.com/codenvy/codenvy/issues/1151
added possiblity to enable jpda suspend mode and change debug port
@garagatyi @TylerJewell please review
=> add possibility to set JPDA_SUSPEND via ENV var

dockerfiles/cli/cli.sh, dockerfiles/cli/codenvy.sh, docs/README.md
Fixes a bug where in certain situations the cli.log was overwritten instead of appended to. Also fixes an issue where we were attempting to stop Codenvy on systems where the directory has not been initialized. Found this situation happening due to error messages in cli.log.
=> Fix CLI to append output instead of overwrite

cdec/installation-manager-core/src/main/resources/codenvy/installation-manager.properties
It fixes error of loading Installation Manager Server https://github.com/codenvy/codenvy/issues/1168
=> (#1168) Add che.api property to the installation manager server config

plugins/plugin-bitbucket/codenvy-plugin-bitbucket-pullrequest/src/test/java/com/codenvy/plugin/pullrequest/client/ContributionMixinProviderTest.java, plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/ContributionExtension.java, plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/ContributionMixinProvider.java, plugins/plugin-pullrequest/codenvy-plugin-pullrequest-ide/src/main/java/com/codenvy/plugin/pullrequest/client/inject/PullRequestGinModule.java
When IDE has been initialized:
* after factory imported (fires `org.eclipse.che.ide.api.factory.FactoryAcceptedEvent` event)
* after normal IDE bootstrap (fires `org.eclipse.che.ide.api.workspace.WorkspaceReadyEvent` event)
contribution extension subscribes to the `org.eclipse.che.ide.api.event.SelectionChangedEvent` event and starts tracking selection changes. And if current root project doesn't have contribution mixin, it will be setting up for the selected project.
Related issue: https://github.com/codenvy/codenvy/issues/707
@ashumilova review it, please.
=> Set up contribution mixins after IDE has been initialized

assembly/onpremises-ide-packaging-war-platform-api/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java, plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedDockerInstance.java, plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/HostedDockerInstanceTest.java
Adds docker instance implementation that limits number of simultaneous container commits on the same node at the same time.
Fixes #1127 
Multiple container commits may be possible on same node.
Commits are one-by-one
None
=> Codenvy-1127  docker instance implementation that that limits number of simultaneous container commits on the same node.

dockerfiles/cli/cli.sh, dockerfiles/cli/codenvy.sh, docs/README.md
1. Adds a '--cli' parameter to `codenvy destroy` which, if `:/cli` is volume mounted, then will destroy the cli.log from the host.  This is not enabled by default so you can monitor the log over time.
2. Adds a 'accept-license' parameter to the 'codenvy init' command which will auto-accept the codenvy license during installation allowing for silent mode.
3. Adds in a structure that allows for parsing multiple parameters on a single command which is generally more flexible than what is currently provided on the command line.
=> CLI Improvements

plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedMachineProviderImpl.java
Do not log `SourceNotFoundException` when starting workspace.
If user will create a worcspace from config with wrong recipe location and then will start it, ERROR will appear in logs. This situation shouldn't be logged because it is normal situation.
No
Related to https://github.com/eclipse/che/pull/3084
@garagatyi please review
=> CODENVY-657: Do not log SourceNotFoundException

wsmaster/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManager.java, wsmaster/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManagerTest.java
Add workspces number limit check, when starting workspace from config.
https://github.com/codenvy/codenvy/issues/1112
It was allowed to create infinite number of workspaces by starting workspaces from config (from swagger or other rest client).
Creating workspace when starting workspace from config is controlled by `limits.user.workspaces.count` property.
Yes
@evoevodin please review
=> CODENVY-1112: Add workspces number limit check, when starting workspace from config

dockerfiles/cli/cmd_start.sh, modules/codenvy/templates/cleanUpWorkspaceStorage.sh.erb, modules/compose/templates/docker-compose-container.yml.erb
1) in dev mode we have to print compose output to console to make devs life easier
2) added missing mount for license file to not loss it after restart
3) sync script with deployment
@garagatyi @TylerJewell @benoitf
=> print compose logs to console in dev mode, add license mount, sync conf

dockerfiles/build.include, dockerfiles/cli/Dockerfile, dockerfiles/cli/build.sh, dockerfiles/cli/cli.sh, dockerfiles/cli/codenvy.sh, dockerfiles/init/build.sh
- allow to use ansi text with printf
- add ansi text formatting constants
- replace "/codenvy" by $CHE_CONTAINER_ROOT
- replace "codenvy" by $CHE_MINI_PRODUCT_NAME
- replace "Codenvy" by $CHE_PRODUCT_NAME
- initialize usage in its own function (for allowing to override constant)
- add sh script to build the cli image 
- use of eclipse/che-base as base image for common scripts for both eclipse/che-cli and codenvy/cli
=> Start to make some common files for codenvy/cli and eclipse/che-cli 

dockerfiles/cli/cmd_config.sh
we should not use `-ti` inside of CLI because it breaks CLI on Jenkins.
@benoitf @TylerJewell @garagatyi
=> remove unnecessary docker opts

dockerfiles/cli/scripts/cmd_init.sh
in dev mode we should take codenvy.env from dev repo not from the image
@benoitf @TylerJewell @garagatyi
=> use codenvy.env from dev repo in dev mode

dockerfiles/cli/scripts/cli.sh
the issue is was with curl doing `-o "${LOGS}"` it did overwrite of whole log.
@TylerJewell @benoitf @garagatyi
=> fix cli.log flushing

cdec/installation-manager-resources/src/main/resources/patches/5.0.0-M8/single_server/patch_before_update.sh
Add migration script to fix locations in **environment** table of PostgreSQL when updating Codenvy on-prem 5.0.0-M7 to 5.0.0-M8:
```
UPDATE environment
SET location=regexp_replace(location, '${host_protocol}://${host_url}/api', '')
```
=> (#1297) Add migration patch for Codenvy on-prem 5.0.0-M8

cdec/installation-manager-tests/src/main/resources/bin/codenvy/install/test-install-single-node-behind-the-proxy.sh
Increase timeout to wait start of workspace in integration tests of Installation Manager CLI.
=> Increase timeout to wait start of workspace in integration tests

docs/_data/docs.yml
replaces the old `developer guide` pages with the correct `white label guide`
=> Updated TOC to have white label guide

docs/_docs/admin-guide/cli.md, docs/_docs/admin-guide/installation.md, docs/_docs/admin-guide/managing.md
Updates content and adds in missing sections to the Admin Guide.
Added in updated syntax for how to run Codenvy in offline mode. These changes require this Eclipse Che PR to be merged.  https://github.com/eclipse/che/pull/3394.  The new offline mode only requires a single step to download everything, and it previously had 4 steps.
=> Content updates to Admin Guide docs section

dockerfiles/cli/build.sh, dockerfiles/cli/version/latest/images, dockerfiles/cli/version/nightly/images, dockerfiles/init/build.sh
As per https://github.com/codenvy/codenvy/pull/1188#issuecomment-261662827
all codenvy/* images defined in codenvy/codenvy repository should have version of codenvy/codenvy tag.
codenvy/codenvy:nightly inherit from codenvy/jdk:nightly
codenvy/haproxy, codenvy/puppet, codenvy/socat are need to match latest, 5.0.0-M7, etc
Change-Id: I3b5922ed22ac8db5bf041c3b23ce50c3306776de
=> Define all codenvy/* images to have codenvy versioning

assembly/onpremises-ide-packaging-war-ext-server/src/main/java/com/codenvy/ext/java/server/MachineServletModule.java
Fixes a problem with creating request url to ws-agent
https://github.com/eclipse/che/issues/3426
The URL `port_host/api/path1/.../pathn1/api/pathn2` was modified `/api/pathn2`
The URL `port_host/api/path1/.../pathn1/api/pathn2` will be modified `/api/path1/.../pathn1/api/pathn2`
=> CHE-3426: fix problem with regexp for api requests

dockerfiles/init/manifests/codenvy.env, docs/_docs/admin-guide/admin-configuration.md
1. Improves the docuemntation around how to setup a private registry for snaps.
2. Copies over Che documentation for configuring various Docker items like mirroring, private registry authentication, and Docker in Docker.
3. Moves some stuff around in the default codevy.env to make configuration easier.
=> Docker Configuration Docs

wsmaster/codenvy-hosted-machine-authentication-ide/src/main/java/com/codenvy/machine/authentication/ide/CodenvyMachineLinksModifier.java, wsmaster/codenvy-hosted-machine-authentication/src/main/java/com/codenvy/machine/authentication/server/MachineServiceAuthLinksInjector.java
Add link to the exec-agent for all machine. 
This is allow execute command on any machine not only on dev machine.
eclipse/che#3435
=> CHE-3435: Add link to the exec-agent for all machine

docs/_docs/admin-guide/admin-installation.md
Adds port information for Codenvy install guide.
=> Update ports for install guide

docs/_docs/admin-guide/admin-managing.md
1. Updates the disaster recovery section of admin-managing.md with information appropriate for dockerized codenvy.
=> update disaster recovery section

docs/_docs/admin-guide/admin-installation.md
- cleans up the internal ports needed for workspace nodes in install guide
=> Docs - cleanup internal ports in install guide

plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/agent/launcher/ExternalRsyncAgentLauncherImpl.java
Change way of verification that sync agent is launched in machine.
Fixes #1392 
Start of WS sometimes failed when ssh or/and rsync are not installed in container.
Start of WS finishes successfully when ssh or/and rsync are not installed in container.
No
=> CODENVY-1392: fix sync agent start check

cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/helper/NodeManagerHelperCodenvy4Impl.java, wsmaster/codenvy-hosted-api-system-license/src/main/java/com/codenvy/api/license/SystemLicense.java, wsmaster/codenvy-hosted-api-system-license/src/main/java/com/codenvy/api/license/SystemLicenseWorkspaceFilter.java, wsmaster/codenvy-hosted-api-system-license/src/main/java/com/codenvy/api/license/server/SystemLicenseManager.java, wsmaster/codenvy-hosted-api-system-license/src/main/java/com/codenvy/api/license/server/SystemLicenseService.java, wsmaster/codenvy-hosted-api-system-license/src/test/java/com/codenvy/api/license/SystemLicenseFactoryTest.java, wsmaster/codenvy-hosted-api-system-license/src/test/java/com/codenvy/api/license/SystemLicenseTest.java, wsmaster/codenvy-hosted-api-system-license/src/test/java/com/codenvy/api/license/SystemLicenseWorkspaceFilterTest.java, wsmaster/codenvy-hosted-api-system-license/src/test/java/com/codenvy/api/license/server/SystemLicenseManagerTest.java, wsmaster/codenvy-hosted-api-system-license/src/test/java/com/codenvy/api/license/server/SystemLicenseServiceTest.java
Fix error message on start of workspace by non-admin user in case of number of registered users more than license allows, but license hasn't expired yet.
Previous misleading message:
> The Codenvy license is expired - you can access the user dashboard but not the IDE.
Fixed message
> The Codenvy license has reached its user limit - you can access the user dashboard but not the IDE.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codenvy/codenvy/1446)
=> Fix license error message in case of license doesn't expire

dockerfiles/cli/scripts/cli.sh, dockerfiles/init/manifests/codenvy.pp, dockerfiles/init/modules/compose/templates/docker-compose.yml.erb
Adapts the Codenvy CLI to make use of debug_server() and local_repo(), so that users can now use local assemblies in production mode, and also debug embedded binaries in an existing Docker image.
Do not merge this until the Che changes have been merged.
https://github.com/eclipse/che/pull/3581
Also, adds in support for additional port checks for socat & swarm, along with simplifying the port check mechanism so that we avoid doing certain port checks twice.  This has improvements that would allow @riuvshin to close this PR:  https://github.com/codenvy/codenvy/pull/1471.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codenvy/codenvy/1458)
=> Adapt CHE-3581 - Enhance CLI to separate debugging from local repo mount

dockerfiles/cli/scripts/cli.sh, dockerfiles/init/modules/compose/templates/docker-compose.yml.erb
we have to expose JMX ports for codenvy API to be able to connect and analyze JVM state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codenvy/codenvy/1484)
=> expose codenvy jmx ports

wsmaster/codenvy-sql-schema/src/main/resources/codenvy-schema/5.1.0/0.1__remove_sync_agents.sql
Removes sync agents from existing WSs
Related to #1403. 
Related to eclipse/che#3676. Should be merged only after it.
No
=> CODENVY-1403: remove sync agents from existing WSs

dockerfiles/cli/scripts/cli.sh
https://github.com/codenvy/customer-saas/issues/101
use of mounting init files only if they're present in the repository
Also, do not specify pp file but use directory puppet manifest mode instead
and if there are extra manifests addon, mount them in the manifests folder. It allows to adds extra settings
Change-Id: I2191624f1bb12ce243fdc46eeb8b33ee0c99e32f
=> SAAS-101 : Allow cli inheritance without dockerfiles manifests 

assembly/onpremises-ide-packaging-tomcat-codenvy-allinone/src/assembly/assembly.xml, dockerfiles/codenvy/Dockerfile
Reduce image size from 552Mb to 355Mb.
Instead of copy zip file with one command and extract archive in next I've used tar.gz archive in combination with docker ADD command.
=> Make single docker image layer when adding tomcat

wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/jpa/JpaSystemPermissionsDao.java, wsmaster/codenvy-hosted-api-permission/src/test/java/com/codenvy/api/permission/server/spi/tck/SystemPermissionsDaoTest.java, wsmaster/codenvy-ldap/README.md, wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/LdapModule.java, wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/DBUserLinker.java, wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/DBUserLinkerProvider.java, wsmaster/codenvy-ldap/src/main/java/com/codenvy/ldap/sync/LdapSynchronizer.java, wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/sync/LdapSynchronizationFlowTest.java, wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/sync/LdapSynchronizerTest.java, wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/sync/UserFinderTest.java
Allows to update users while linking attribute is different from 'id'.
FIxes NPE when LDAP synchronization is on and default admin user is removed.
Introduces a few new updates:
- `LOG.debug` the entities which are going to be synchronized 
- Added `SyncResult.fetched` field which shows how many users were fetched from ldap
- Added an ability to link users by their names
=> Allow to update users while linking

wsmaster/codenvy-hosted-api-audit/src/main/java/com/codenvy/api/audit/server/AuditManager.java, wsmaster/codenvy-hosted-api-audit/src/test/java/com/codenvy/api/audit/server/AuditManagerTest.java, wsmaster/codenvy-hosted-api-resource/src/main/java/com/codenvy/resource/api/usage/tracker/RamResourceUsageTracker.java, wsmaster/codenvy-hosted-api-resource/src/main/java/com/codenvy/resource/api/usage/tracker/RuntimeResourceUsageTracker.java, wsmaster/codenvy-hosted-api-resource/src/main/java/com/codenvy/resource/api/usage/tracker/WorkspaceResourceUsageTracker.java, wsmaster/codenvy-hosted-api-resource/src/test/java/com/codenvy/resource/api/usage/tracker/RamResourceUsageTrackerTest.java, wsmaster/codenvy-hosted-api-resource/src/test/java/com/codenvy/resource/api/usage/tracker/RuntimeResourceUsageTrackerTest.java, wsmaster/codenvy-hosted-api-resource/src/test/java/com/codenvy/resource/api/usage/tracker/WorkspaceResourceUsageTrackerTest.java, wsmaster/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManagerTest.java
Use new workspace manager methods to fetch workspace lists with boolean parameter, and choose whether to fetch runtimes or not
https://github.com/codenvy/codenvy/issues/1506
=> CODENVY-1506 Rework workspace manager methods to optionally return runtime info

dockerfiles/init/modules/compose/templates/docker-compose.yml.erb
this is partial solution for https://github.com/codenvy/codenvy/issues/1554
stopping oder before fix
```
Stopping codenvy_registry_1 ... done
Stopping codenvy_zookeeper_1 ... done
Stopping codenvy_codenvy_1 ... done
Stopping codenvy_swarm_1 ... done
Stopping codenvy_haproxy_1 ... done
Stopping codenvy_postgres_1 ... done
Stopping codenvy_socat_1 ... done
Stopping codenvy_rsyslog_1 ... done
Stopping codenvy_nginx_1 ... done
Stopping codenvy_agents_1 ... done
```
stopping order after fix
```
Stopping codenvy_registry_1 ... done
Stopping codenvy_codenvy_1 ... done
Stopping codenvy_swarm_1 ... done
Stopping codenvy_haproxy_1 ... done
Stopping codenvy_postgres_1 ... done
Stopping codenvy_socat_1 ... done
Stopping codenvy_agents_1 ... done
Stopping codenvy_zookeeper_1 ... done
Stopping …
```
=> Fix compose containers ordering issue.

dockerfiles/cli/scripts/cli.sh
Fix #1564 : Invalid name for sync command
#1564
It was still "mount" while command has been renamed to "sync"
Use correct "sync" command
No
no (bugfix)
Change-Id: I5c0cafcf358db2a753a8b0a675ae58b4a2f69358
=> [cli] Fix #1564 : Invalid name for sync command

dockerfiles/cli/scripts/cli.sh, dockerfiles/cli/scripts/entrypoint.sh
1. Adds in ability to mount `:/assembly` so that it mounts a Tomcat binary directly without mounting the entire repository.
2. Adds in a refactoring of the preflight checks to test all ports at the same time.  This makes overall performance faster.  If any of the ports fail, then we iterate through each port check one at a time.
https://github.com/codenvy/codenvy/issues/1550
Adapt to Eclipse Che #1550 - adds `:/assembly` volume mount
N/A
N/A
=> CLI - Adapt to Che CLI changes for custom assembly, faster port check

dashboard/src/app/account/details/account-delete.controller.ts, dashboard/src/app/account/details/account-delete.html, dashboard/src/app/admin/user-management/add-user/add-user.html, dashboard/src/app/admin/user-management/add-user/add-user.styl, dashboard/src/app/admin/user-management/user-management.controller.ts, dashboard/src/app/factories/create-factory/action/factory-action-edit.controller.ts, dashboard/src/app/factories/create-factory/action/factory-action-edit.html, dashboard/src/app/factories/create-factory/command/factory-command-edit.html, dashboard/src/app/factories/factory-details/information-tab/factory-information/factory-information.controller.ts, dashboard/src/app/factories/factory-details/information-tab/factory-information/factory-information.html, dashboard/src/app/factories/list-factories/list-factories.controller.ts, dashboard/src/app/workspace/share-workspace/add-members/add-members.html, dashboard/src/app/workspace/share-workspace/add-members/add-members.styl, dashboard/src/app/workspace/share-workspace/share-workspace.controller.ts, dashboard/src/app/workspace/share-workspace/user-item/user-item.controller.ts, dashboard/src/app/workspace/share-workspace/user-item/user-item.html
Update style for popups in Dashboard
https://github.com/eclipse/che/issues/2813
No
=> CODENVY-2813 update style for popups in Dashboard

dockerfiles/init/manifests/codenvy.pp, dockerfiles/init/modules/codenvy/templates/general.properties.erb
today db schema was hardcoded in props because we don't want allow to modify them but now we need ability to change schema for saas
=> allow override flyway db schema in saas

assembly/onpremises-ide-packaging-war-platform-api/src/main/webapp/WEB-INF/classes/codenvy/codenvy-api-configuration.properties
This optional property is defined only on Mac and Windows by default
On linux a default value is also required.
**Changelog**: add default empty che.docker.ip.external value
**Release Notes**: bug
bugfix
Change-Id: If7ad1af2cb6a9b492d8926dfe1598f18737d2c19
=> Add property about che.docker.ip.external with a default null value

plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/agent/MachineInnerRsyncAgent.java
Replaces "sudo" with "sudo -E" which preserves user's environment
variables which may contain proxy settings.
Related to eclipse/che#3927
sudo used environment of root, so proxy variables weren't respected
sudo respects user's environment including proxy settings
No
Can someone point me to place where docs should be updated?
=> [WIP] CHE-3920: make rsync agent installation scripts respect environment variables

dockerfiles/init/modules/codenvy/templates/general.properties.erb
to be able to override default value of `db_schema_flyway_scripts_locations` for saas we need pick var value depending on scope where it is declared.
this approach needed for some rare cases where we want override default value, it was possible to change it by modifying `codenvy.env` but for saas that prop must be always different.
**Changelog**: set `db_schema_flyway_scripts_locations` property value depending on scope.
=> pick prop value depending on scope

dockerfiles/cli/scripts/cli.sh, dockerfiles/cli/scripts/entrypoint.sh, dockerfiles/init/modules/codenvy/templates/general.properties.erb
Signed-off-by: Tyler Jewell <tjewell@codenvy.com>
This PR adapts changes made to Eclipse Che to allow the inherited CLI to inherit its `usage()` statement from the core CLI so that as the base CLI makes improvements, the new CLI will have it inherited automatically.
Also provides a first implementation of a postflight check, which pulls the list of Swarm nodes from `codenvy.env` and then uses `curl` to ping each one's `/info` URL to see if it is reachable.
Must merge this at the same time as we merge: https://github.com/eclipse/che/pull/3940
Adapt CLI to changes in Eclipse Che #3940
Add postflight check of Swarm nodes as a test
We are working to make sure Codenvy starts in any environment perfectly every time. We've added some additional preflight checks related to mandatory minimums for …
=> Add postflight check of swarm nodes

assembly/onpremises-ide-compiling-war-ide/pom.xml, assembly/onpremises-ide-compiling-war-ide/src/main/resources/com/codenvy/ide/IDE.gwt.xml, assembly/onpremises-ide-packaging-war-ext-server/pom.xml
This PR is a proposal for decoupling testing framework core API from Java specific testing frameworks.
[#3452](https://github.com/eclipse/che/issues/3452)
In current state all of the testing frameworks that are Java specific are tightly coupled with the testing framework core API, which complicates "straight-forward" adding of new testing frameworks (i.e. PHPUnit). 
- Testing core framework API was moved to Che Core API packages (I was using the debugger API analogy)
- All code in testing framework core API that was tightly coupled to Java specific testing frameworks (i.e. JUnit, TestNG) was unbound and moved to related plug-ins 
That's more or less the general description of the changes that I have made. I am eager to answer all of the possible questions related to the details. …
=> Decouple testing framework API from Java test specific frameworks

dockerfiles/init/manifests/codenvy.pp, dockerfiles/init/modules/codenvy/templates/rsyncbackup.sh.erb, dockerfiles/init/modules/codenvy/templates/rsyncrestore.sh.erb, plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/backup/DockerEnvironmentBackupManager.java, plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/backup/DockerEnvironmentBackupManagerTest.java
Allow to configure rsync log level.
Disable attempts of password authentication by rsync.
Allow to configure rsync backup/restore throughput limit.
Adds possibility to set next env vars in codenvy.env (but they are not exposed in codenvy.env as commented lines):
RSYNC_RESTORE_BWLIMIT
RSYNC_BACKUP_BWLIMIT
RSYNC_SSH_LOG_LEVEL
Default values for RSYNC_RESTORE_BWLIMIT and RSYNC_BACKUP_BWLIMIT 7000KiB/s. Value without unit suffix interpreted in KiB per second. 
Default value of RSYNC_SSH_LOG_LEVEL is INFO. Possible values: QUIET, FATAL, ERROR, INFO, VERBOSE, DEBUG1, DEBUG2, and DEBUG3
Fixes #1728 
Fixes #1713 
Provides possibility to get helpful logs for cases like in #1662 
Adds logging for project synchronization errors.
Adds throughput limits for project synchronization.
n/a
n/a
=> CODENVY-1662: improve rsync configurability

dockerfiles/init/modules/postgres/templates/postgresql.conf.erb
I would like to change postgresql configuration to be able to use pgbadger to analyse postgresql state.
Example of report
https://transfer.sh/itzox/out.html
http://dalibo.github.io/pgbadger/samplev7.html
Also we might think about set ``` log_min_duration_statement = 0```  I think now we already doing that by ```log_statement = 'all'```
Change postgresql configuration to be able to use pgbadger to generate usage reports
=> PG configuration according http://dalibo.github.io/pgbadger/ 

assembly/assembly-wsmaster-war/pom.xml, assembly/compiling-ide-war/pom.xml, pom.xml
Adds 'classes' classifier for IDE war compiling, to allow archetypes  make dependency on it.
INFRA-68
Added 'classes' classifier for IDE war compiling, to allow archetypes  make dependency on it.
N/A
N/A
=> INFRA-68; add 'classes' classifier for IDE war compiling

dockerfiles/init/manifests/codenvy.env, dockerfiles/init/manifests/codenvy.pp, dockerfiles/init/modules/codenvy/templates/general.properties.erb, wsmaster/codenvy-hosted-api-machine/src/test/java/com/codenvy/api/machine/server/jpa/JpaRecipePermissionsDaoTest.java, wsmaster/codenvy-hosted-api-organization/pom.xml, wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/OrganizationApiModule.java, wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/permissions/OrganizationPermissionsFilter.java, wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/permissions/OrganizationResourceDistributionServicePermissionsFilter.java, wsmaster/codenvy-hosted-api-organization/src/test/java/com/codenvy/organization/api/permissions/OrganizationPermissionsFilterTest.java, wsmaster/codenvy-hosted-api-organization/src/test/java/com/codenvy/organization/api/permissions/OrganizationResourceDistributionServicePermissionsFilterTest.java, wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/SuperPrivilegesChecker.java, wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/filter/GetPermissionsFilter.java, wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/filter/RemovePermissionsFilter.java, wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/filter/SetPermissionsFilter.java, wsmaster/codenvy-hosted-api-permission/src/test/java/com/codenvy/api/permission/server/filter/GetPermissionsFilterTest.java, wsmaster/codenvy-hosted-api-permission/src/test/java/com/codenvy/api/permission/server/filter/RemovePermissionsFilterTest.java, wsmaster/codenvy-hosted-api-permission/src/test/java/com/codenvy/api/permission/server/filter/SetPermissionsFilterTest.java, wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/WorkspaceApiModule.java, wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/filters/WorkspacePermissionsFilter.java, wsmaster/codenvy-hosted-api-workspace/src/test/java/com/codenvy/api/workspace/server/filters/WorkspacePermissionsFilterTest.java, wsmaster/codenvy-hosted-api-workspace/src/test/java/com/codenvy/api/workspace/server/jpa/OnPremisesJpaWorkspaceDaoTest.java, wsmaster/codenvy-sql-schema/src/main/resources/codenvy-schema/5.3.0/0.1__remove_manageorganizations_action.sql
Adds configuration parameter `system.super_privileged_mode` that allow to extend default opportunities for users who have `manageSystem` permission.
https://github.com/codenvy/codenvy/issues/1302
Users who have `manageSystem` permission is able to perform following operations with workspaces: getByKey, getByNamespace, stop.
If corresponding configuration parameter is `true` then users who have `manageSystem` can getByKey, getByNamespace, stop workspaces and getResourcesInformation, getByParent, getByUser organizations. If user needs to perform any other action with workspace or organization, he is able to add permissions there for himself.
Yes
Issue link [https://github.com/codenvy/codenvy-docs/issues/41](https://github.com/codenvy/codenvy-docs/issues/41). No PR yet.
=> CODENVY-1302 Add super privileges for users who have manageSystem permission

README.md
Fixes a typo in the top-level README.
N/A
N/A
N/A
N/A
PS -- let me know if these "typo" PR's aren't helpful and I'll stop :)
=> README Typo ('moutn' to 'mount')

dockerfiles/cli/scripts/cmd_config.sh, dockerfiles/init/manifests/codenvy.pp, dockerfiles/init/modules/compose/templates/docker-compose.yml.erb
Allow to use :/assembly binaries with codenvy cli
Only :/repo mode was working
it checks that values are provided before trying to use them
For example it was trying to mount wsagent binaries but they're not inside the assembly so string was empty in docker compose file leading to errors
Also CHE_REPO was enabled when using a local assembly while we're not in that mode.
#1770 
Fix :/assembly volume mouting usage when using codenvy cli
N/A bug
N/A bug
=> [cli] allow to use :/assembly binaries with codenvy cli

wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/PermissionsManager.java, wsmaster/codenvy-hosted-api-permission/src/main/java/com/codenvy/api/permission/server/SystemDomain.java, wsmaster/codenvy-hosted-api-workspace/src/main/java/com/codenvy/api/workspace/server/filters/StackPermissionsFilter.java, wsmaster/codenvy-hosted-api-workspace/src/test/java/com/codenvy/api/workspace/server/filters/StackPermissionsFilterTest.java
Allows to users with `manageSystem` permission perform edit and delete operation with predefined (i.e. public for all users) stack.
https://github.com/codenvy/codenvy/issues/1711
Permissions granted to admins to perform `update` and `delete` action with predefined stacks.
Added ability to admins with `manageSystem` permission perform `update` and `delete` action with predefined stacks.
N/A
=> CODENVY-1711: Grant permissions to admins for predefined stacks

dockerfiles/init/modules/haproxy/templates/haproxy.cfg.erb
allows download agents via http
related to https://github.com/eclipse/che/pull/4029
allows download agents via http
=> do not redirect /agent-binaries to from http to https

dockerfiles/cli/scripts/cmd_config.sh
If Codenvy has been started with /assembly mount, it may contain ws-agent in assembly main (by default location lib/ws-agent.tar.gz). If CLI detects one, it will use this ws-agent.
https://github.com/codenvy/codenvy/issues/1829
The CLI can now use the ws-agent from a mounted assembly.
n/a
n/a
=> CODENVY-1829 Add ability to use ws-agent from main assembly

dockerfiles/init/modules/codenvy/templates/rsyncbackup.sh.erb, dockerfiles/init/modules/codenvy/templates/rsyncrestore.sh.erb
Change rsync scripts to save real ownership instead of setting it
to current user in container.
Change rsync scripts to save all permissions instead of
executabililty only.
Add a lot of comments to describe why such rsync options are used.
Improve rsync over ssh host key checking to not add useless entries
into hosts file.
Fixes #1814 
Fixes #1820 
Changed rsync scripts to save true ownership.
Changed rsync scripts to set all permissions.
Improved rsync over ssh host key checking.
n/a
n/a
=> CODENVY-1814: Rework project syncing to fix compatibility issue

wsmaster/codenvy-hosted-api-organization-shared/src/main/java/com/codenvy/organization/shared/dto/OrganizationDistributedResourcesDto.java, wsmaster/codenvy-hosted-api-organization-shared/src/main/java/com/codenvy/organization/shared/model/OrganizationDistributedResources.java, wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/DtoConverter.java, wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/permissions/OrganizationResourceDistributionServicePermissionsFilter.java, wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/resource/OrganizationResourcesDistributionService.java, wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/resource/OrganizationResourcesDistributor.java, wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/resource/OrganizationResourcesReserveTracker.java, wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/resource/SuborganizationResourcesProvider.java, wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/spi/impl/OrganizationDistributedResourcesImpl.java, wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/spi/jpa/JpaOrganizationDistributedResourcesDao.java, wsmaster/codenvy-hosted-api-organization/src/test/java/com/codenvy/organization/api/permissions/OrganizationResourceDistributionServicePermissionsFilterTest.java, wsmaster/codenvy-hosted-api-organization/src/test/java/com/codenvy/organization/api/resource/OrganizationResourcesDistributionServiceTest.java, wsmaster/codenvy-hosted-api-organization/src/test/java/com/codenvy/organization/api/resource/OrganizationResourcesDistributorTest.java, wsmaster/codenvy-hosted-api-organization/src/test/java/com/codenvy/organization/api/resource/OrganizationResourcesReserveTrackerTest.java, wsmaster/codenvy-hosted-api-organization/src/test/java/com/codenvy/organization/api/resource/SuborganizationResourcesProviderTest.java, wsmaster/codenvy-hosted-api-resource/src/main/java/com/codenvy/resource/api/ResourcesReserveTracker.java, wsmaster/codenvy-hosted-api-resource/src/main/java/com/codenvy/resource/api/free/FreeResourcesProvider.java, wsmaster/codenvy-hosted-api-resource/src/main/java/com/codenvy/resource/api/license/AccountLicenseService.java, wsmaster/codenvy-hosted-api-resource/src/main/java/com/codenvy/resource/api/usage/ResourceUsageManager.java, wsmaster/codenvy-hosted-api-resource/src/test/java/com/codenvy/resource/api/free/FreeResourcesProviderTest.java, wsmaster/codenvy-hosted-integration-tests/codenvy-integration-cascade-jpa/src/test/java/com/codenvy/integration/jpa/cascaderemoval/JpaEntitiesCascadeRemovalTest.java, wsmaster/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManager.java, wsmaster/codenvy-hosted-platform-api-impl/src/test/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManagerTest.java
Rework organization resources in following way:
- remove moving resources from parent organization to its suborganization
- add ability suborganizations to use parent organization resources by default
- add ability to parent to set cap on shared resources usage
https://github.com/codenvy/codenvy/issues/1729
- Rework organization distribution service to cap resource usage.
N/A part of teams
N/A part of teams
=> Implement resources capping for suborganizations

dashboard/src/app/billing/card-info/card-info.html, dashboard/src/app/billing/ram-info/more-ram-dialog.html, dashboard/src/app/billing/ram-info/ram-info.directive.ts, dashboard/src/app/teams/team-details/team-details.html
This PR adds fixes for Billing info tab and "Get More RAM" widget:
- restrict some inputs to enter only valid symbols;
- set focus to input when widget is shown;
- apply filter to round fractional part of calculated values in widget;
N/A
[UD] make inputs on "Get More RAM" widget and Billing info tab to allow to enter only valid symbols
N/A - bugfix
N/A - bugfix
=> [UD] fixes for "Get More RAM" widget and Billing info tab

dashboard/src/app/billing/billing-config.ts, dashboard/src/app/billing/billing.controller.ts, dashboard/src/app/billing/billing.html
This fix prevents changing tabs after reloading the "Billing" page.
#1832 
[UD] fixed changing tabs after reloading the "Billing" page.
N/A - bugfix
N/A - bugfix
=> CODENVY-1832: open same tab on "Billing" page after reload

assembly/assembly-wsagent-war/src/main/java/com/codenvy/ext/java/server/MachineModule.java
Removes deprecated RemotePreferenceDao.
https://github.com/eclipse/che/issues/4014
Removed the deprecated RemotePreferenceDao.
Advisories
As described in our [5.2 release notes](https://che.eclipse.org/release-notes-eclipse-che-5-2-dd6411626d18#.qpqbwunvv) the Machine API was deprecated and is in the process of being removed.
N/A
=> CHE-4014; remove deprecated RemotePreferenceDao

wsmaster/codenvy-hosted-api-system-license/pom.xml, wsmaster/codenvy-hosted-api-system-license/src/main/java/com/codenvy/api/license/SystemLicense.java, wsmaster/codenvy-hosted-api-system-license/src/main/java/com/codenvy/api/license/server/SystemLicenseManager.java, wsmaster/codenvy-hosted-api-system-license/src/main/java/com/codenvy/api/license/server/SystemLicenseService.java, wsmaster/codenvy-hosted-api-system-license/src/main/java/com/codenvy/api/license/server/filter/SystemLicenseServicePermissionsFilter.java, wsmaster/codenvy-hosted-api-system-license/src/test/java/com/codenvy/api/license/SystemLicenseTest.java, wsmaster/codenvy-hosted-api-system-license/src/test/java/com/codenvy/api/license/server/SystemLicenseManagerTest.java, wsmaster/codenvy-hosted-api-system-license/src/test/java/com/codenvy/api/license/server/SystemLicenseServiceTest.java, wsmaster/codenvy-hosted-api-system-license/src/test/java/com/codenvy/api/license/server/filter/SystemLicenseServicePermissionsFilterTest.java
It removes redundant getting number of nodes from the swarm connector, to avoid throwing next exception in case of swarm container is not accessible:
> HTTP Status 500 - org.eclipse.che.api.core.ServerException: Failed to check if Codenvy usage matches system License constraints.
[Selenium testing result](https://gist.github.com/dmytro-ndp/9d2abe938d9d35e9f90c19adf6c9d0d4).
This request is linked with #1928.
(there are no significant changes for changelog)
(there are no significant changes for release notes)
(there are no significant changes for Docs)
=> Don't take into account node number when check license usage legality

dockerfiles/rsyslog/Dockerfile, dockerfiles/rsyslog/entrypoint.sh
add entrypoint to rsyslog image where we kill pid file if it exist before start rsyslog, that may happen on force restart container and rsyslog wount be able to start.
fixes https://github.com/codenvy/codenvy/issues/1940
add rsyslog entrypoint
=> add rsyslog entrypoint

dockerfiles/cli/version/5.6.0/images, dockerfiles/cli/version/latest/images, dockerfiles/cli/version/nightly/images, dockerfiles/init/modules/compose/templates/docker-compose.yml.erb, dockerfiles/init/modules/registry/manifests/init.pp, dockerfiles/init/modules/registry/templates/registry_entrypoint.sh.erb, dockerfiles/init/modules/rsyslog/manifests/init.pp, dockerfiles/init/modules/rsyslog/templates/registry.conf.erb, dockerfiles/init/modules/rsyslog/templates/swarm.conf.erb, dockerfiles/init/modules/rsyslog/templates/zookeeper.conf.erb, dockerfiles/init/modules/swarm/manifests/init.pp, dockerfiles/init/modules/swarm/templates/swarm_entrypoint.sh.erb, dockerfiles/swarm/Dockerfile, dockerfiles/swarm/build.sh
in order to fix: https://github.com/codenvy/codenvy/issues/1940 afret some investigation i've figured out that our issues were due to using docker logging with syslog which we running as a container. That was a mistake, we should not do that because it works only with compose where we define start order, but when instance or docker daemon reboot containers start in random order which makes failure when image which wants to send logs to syslog started before syslog. And this kind of failures is kind of fatal for docker and docker daemon even don't trying to restart failed container although we've specified `restart: always`.
So here i;ve removed using docker logging with syslog which should fix the issue, but we still need to get logs from containers so i did some changes to make this …
=> Codenvy-1940: some containers became inaccessible after rebooting

plugins/plugin-gitlab/codenvy-plugin-gitlab-factory-resolver/pom.xml, plugins/plugin-gitlab/codenvy-plugin-gitlab-factory-resolver/src/main/java/com/codenvy/plugin/gitlab/factory/resolver/GitLabFactoryModule.java, plugins/plugin-gitlab/codenvy-plugin-gitlab-factory-resolver/src/main/java/com/codenvy/plugin/gitlab/factory/resolver/GitlabFactoryParametersResolver.java, plugins/plugin-gitlab/codenvy-plugin-gitlab-factory-resolver/src/main/java/com/codenvy/plugin/gitlab/factory/resolver/GitlabSourceStorageBuilder.java, plugins/plugin-gitlab/codenvy-plugin-gitlab-factory-resolver/src/main/java/com/codenvy/plugin/gitlab/factory/resolver/GitlabURLParser.java, plugins/plugin-gitlab/codenvy-plugin-gitlab-factory-resolver/src/main/java/com/codenvy/plugin/gitlab/factory/resolver/GitlabUrl.java, plugins/plugin-gitlab/codenvy-plugin-gitlab-factory-resolver/src/main/java/com/codenvy/plugin/gitlab/factory/resolver/LegacyGitlabURLParser.java, plugins/plugin-gitlab/codenvy-plugin-gitlab-factory-resolver/src/test/java/com/codenvy/plugin/gitlab/factory/resolver/GitlabFactoryParametersResolverTest.java, plugins/plugin-gitlab/codenvy-plugin-gitlab-factory-resolver/src/test/java/com/codenvy/plugin/gitlab/factory/resolver/GitlabURLParserTest.java, plugins/plugin-gitlab/codenvy-plugin-gitlab-factory-resolver/src/test/java/com/codenvy/plugin/gitlab/factory/resolver/GitlabUrlTest.java
Use new `.factory.dockerfile` and `.factory.properties` for repo URL based factories. (old filenames are supported as well)
CHE-4498 CHE-4499
Use new `.factory.dockerfile` and `.factory.properties` for repo URL based factories.
=> CHE-4499; support legaсy filenames for github factories

dockerfiles/init/modules/compose/templates/docker-compose.yml.erb, dockerfiles/init/modules/registry/templates/registry_entrypoint.sh.erb, dockerfiles/init/modules/swarm/manifests/init.pp, dockerfiles/swarm/Dockerfile, dockerfiles/swarm/entrypoint.sh
Fix very slow codenvy cli stop operation.
Thanks @akorneta for reporting this issue. After some investigation I figured out that this was introduced by: https://github.com/codenvy/codenvy/commit/79079d048c22d5c3cdd1e6c75ab7d41f1dc201de
That happened due to wrong entrypoint which spawned more than 1 process in a container which is antiPattern for docker flow. During docker stop docker send special signal to notify main process (usually pid = 1) in container that this container is going to be stopped, but in our case process with pid = 1 was entrypoint script instead of swarm. As result swarm didn't received stop signal and keep working so docker killed that container with force after timeout **~5min**.
To fix this issue I added logic to entrypoint scripts to handle termiation and properly …
=> Codenvy-1995: fix codenvy cli stop very slow

dashboard/src/app/teams/create-team/create-team.controller.ts, dashboard/src/app/teams/team-details/team-members/list-team-members.controller.ts, dashboard/src/app/teams/team-details/team-members/list-team-members.html, dashboard/src/app/teams/team-details/team-members/member-item/member-item.controller.ts, dashboard/src/app/teams/team-details/team-members/member-item/member-item.html, dashboard/src/app/teams/team-details/team-members/member-item/member-item.styl, dashboard/src/components/api/codenvy-api-config.ts, dashboard/src/components/api/codenvy-invite.factory.ts, dashboard/src/components/api/codenvy-permissions.factory.ts
Performs invite of unregistered users and displays the list of invites.
UI for https://github.com/codenvy/codenvy/issues/1851
[UD] added sending team invitations to unregistered users and display pending members for admin of the team.
When using team on `codenvy.io`, you can now invite user who are not yet having an account created. They will receive an email proposing to create an account and they'll be added into your team. Additionally when sharing a workspace, you can also invite other developers wether they are having an account on `codenvy.io` or not. 
https://github.com/codenvy/docs/pull/105
=> codenvy-1851: invite unregistered users to the team and display invited members

wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/OrganizationValidator.java
Allows to use single hyphen in the middle of organization name
https://github.com/codenvy/codenvy/issues/1610
Allowed to use single hyphen in the middle of organization name
Allowed to use single hyphen in the middle of organization name
N/A
=> CODENVY-1610 Allows to use single hyphen in the middle of organization name

plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/swarm/client/SwarmDockerConnector.java
Workaround docker exec not found problem in swarm by waiting extra second and sending request again.
Also Swarm connector tries to log docker exec inspect info. 
Related to #1734 
Add workaround for bug in Swarm when exec can't be found by Swarm
=> CODENVY-1734: workaround docker exec not found problem in swarm

dockerfiles/init/modules/base/manifests/init.pp
to fix permissions issue we have to create folder with 777 permissions before volume mount.
https://github.com/codenvy/codenvy/issues/2021
fix zookeeper logs issue
=> fix zookeeper logs issue

dockerfiles/init/modules/codenvy/manifests/init.pp, dockerfiles/init/modules/codenvy/templates/rsyncbackup.sh.erb, dockerfiles/init/modules/codenvy/templates/rsyncbase.sh.erb, dockerfiles/init/modules/codenvy/templates/rsyncrestore.sh.erb
Changes strategy of checking whether sudo should be used for rsync backuping.
Fixes #1996 
Improve checking sudo in rsync backup scripts
=> CODENVY-1996: Improve checking sudo in rsync backup scripts

plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/backup/DockerEnvironmentBackupManager.java
Prevents logging exception traces when WS start is interrupted by user while projects are restoring.
Fixes #1822 
Do not log exception about workspace restoring interruption when user stops workspace while it starting.
=> CODENVY-1822: do not log exception on WS start interruption

plugins/plugin-hosted/codenvy-hosted-ext-hosted/src/main/java/com/codenvy/ide/hosted/client/informers/HostedEnvConnectionClosedInformer.java, plugins/plugin-hosted/codenvy-hosted-ext-hosted/src/main/java/com/codenvy/ide/hosted/client/inject/HostedEnvironmentGinModule.java, plugins/plugin-hosted/codenvy-hosted-ext-hosted/src/main/resources/com/codenvy/ide/hosted/Hosted.gwt.xml
HostedEnvConnectionClosedInformer extends ConnectionClosedInformerImp from Che 
eclipse/che#4595
HostedEnvConnectionClosedInformer now extends class ConnectionClosedInformerImp from Che this allow make different behavior in Codenvy project.
N/A
=> CHE-4595: HostedEnvConnectionClosedInformer extends ConnectionClosedInformerImp

wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/OrganizationManager.java, wsmaster/codenvy-hosted-api-organization/src/test/java/com/codenvy/organization/api/OrganizationManagerTest.java
Add publishing BeforeAccountRemovedEvent by OrganizationManager. It is required because organizational account will be removed automatically before removing of organization. Earlier AccountEntityListener did it but original exception was not propagated in that case.
https://github.com/codenvy/codenvy/issues/1974
Added publishing BeforeAccountRemovedEvent by OrganizationManager.
N/A
N/A
=> CODENVY-1974 Add publishing BeforeAccountRemovedEvent by OrganizationManager

dockerfiles/init/modules/codenvy/templates/rsyncbase.sh.erb
This PR improves stability of workspace start by adding rsync exit code check and retrying if workspace restore fail.
Workspace restore could fail due to network errors, tricky cache system of user's OS after adding SSH key from concurrent thread, long sshd time start, etc.
https://github.com/codenvy/codenvy/issues/2053
Added check that SSH into workspace succeeds when doing backup/restore.
Added retry for initially failed workspace backup/restore.
N/A
N/A
=> CODENVY-2053: Retry rsync restore on unexpected fail

wsmaster/codenvy-hosted-system/src/main/java/com/codenvy/service/system/DockerBasedSystemRamInfoProvider.java
Add `Arrays.deepToString` when loggin system info, wich is introuduced in 2d array in `DockerBasedSystemRamInfoProvider` class, to view all data from system info object, not just first entry.
https://github.com/codenvy/codenvy/issues/1941
Fix logging system info when failed to recieve RAM values from docker
Bugfix
Bugfix
=> CODENVY-1941: Fix logging error in DockerBasedSystemRamInfoProvider

dockerfiles/init/modules/haproxy/templates/haproxy.cfg.erb
Removes all master authentication cookies from ws-agent request on haproxy
https://github.com/codenvy/infrastructure/issues/84
Remove all master authentication cookies from ws-agent request on haproxy
=> Removes all master authentication cookies from ws-agent request on haproxy

assembly/assembly-wsmaster-war/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiModule.java, plugins/plugin-bitbucket/codenvy-plugin-bitbucket-ext-bitbucket-server/pom.xml, plugins/plugin-bitbucket/codenvy-plugin-bitbucket-ext-bitbucket-server/src/main/java/org/eclipse/che/ide/ext/bitbucket/server/BitbucketConnectionImpl.java, plugins/plugin-bitbucket/codenvy-plugin-bitbucket-ext-bitbucket-server/src/main/java/org/eclipse/che/ide/ext/bitbucket/server/BitbucketConnectionProvider.java, plugins/plugin-bitbucket/codenvy-plugin-bitbucket-ext-bitbucket-server/src/main/java/org/eclipse/che/ide/ext/bitbucket/server/BitbucketKeyUploader.java, plugins/plugin-bitbucket/codenvy-plugin-bitbucket-ext-bitbucket-server/src/main/java/org/eclipse/che/ide/ext/bitbucket/server/BitbucketServerConnectionImpl.java, plugins/plugin-bitbucket/codenvy-plugin-bitbucket-git-provider/pom.xml, plugins/plugin-bitbucket/codenvy-plugin-bitbucket-git-provider/src/main/java/org/eclipse/che/ide/ext/git/server/nativegit/BitbucketOAuthCredentialProvider.java, plugins/plugin-bitbucket/codenvy-plugin-bitbucket-oauth/pom.xml, plugins/plugin-github/codenvy-plugin-github-webhooks/pom.xml, plugins/plugin-google/codenvy-plugin-google-oauth2/pom.xml, plugins/plugin-linkedin/codenvy-plugin-linkedin-oauth2/pom.xml, plugins/plugin-microsoft/codenvy-plugin-microsoft-git-provider/pom.xml, plugins/plugin-microsoft/codenvy-plugin-microsoft-git-provider/src/main/java/org/eclipse/che/ide/ext/git/server/nativegit/MicrosoftOAuthCredentialsProvider.java, plugins/plugin-microsoft/codenvy-plugin-microsoft-oauth2/pom.xml, plugins/plugin-microsoft/codenvy-plugin-microsoft-vsts-ext-server/pom.xml, plugins/plugin-microsoft/codenvy-plugin-microsoft-vsts-ext-server/src/main/java/org/eclipse/che/ide/ext/microsoft/server/MicrosoftVstsRestClient.java, plugins/plugin-microsoft/codenvy-plugin-microsoft-vsts-webhooks/pom.xml, plugins/plugin-projectlocker/codenvy-plugin-projectlocker-git-provider/pom.xml, plugins/plugin-projectlocker/codenvy-plugin-projectlocker-git-provider/src/main/java/org/eclipse/che/ide/ext/git/server/nativegit/ProjectLockerOAuthCredentialProvider.java, plugins/plugin-projectlocker/codenvy-plugin-projectlocker-oauth2/pom.xml, plugins/plugin-redhat/codenvy-plugin-redhat-oauth2/pom.xml, plugins/plugin-webhooks/codenvy-plugin-webhooks-base/pom.xml, plugins/plugin-wso2/codenvy-plugin-wso2-git-provider/pom.xml, plugins/plugin-wso2/codenvy-plugin-wso2-git-provider/src/main/java/org/eclipse/che/ide/ext/git/server/nativegit/WSO2OAuthCredentialsProvider.java, plugins/plugin-wso2/codenvy-plugin-wso2-oauth2/pom.xml, wsmaster/codenvy-hosted-platform-api-impl/pom.xml, wsmaster/codenvy-hosted-sso-oauth/pom.xml
Adopts moving `RemoteOAuthTokenProvider` and `RemoteOAuthAuthorizationHeaderProvider` to separate module included on wsagent, to avoid include whole auth-core module with AuthrorizationService etc.
https://github.com/eclipse/che/issues/4462
Decouple ws-agent and ws-master authorization dependencies
N/A
N/A
=> CHE-4462; Separate master and agents OAuth modules;

plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/swarm/client/SwarmDockerConnector.java
Due to casual error in docker/swarm our system got errors like:
`Error response from docker API, status: 500, message: Error response from daemon: repository eclipse-che/workspace****_machine****_****_dev-machine not found: does not exist or no pull access`
But actually image is present and repository is available. So it could be network issues or some unsynchronized stuff between docker and pure swarm. This PR just adds check for this type of error from docker and retries after little delay.
https://github.com/codenvy/codenvy/issues/2144
Retry interact with repository on fail.
N/A
N/A
=> CODENVY-2144: Retry interaction with repository on fail

plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedMachineProviderImpl.java, plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/HostedMachineProviderImplTest.java
Adds possibility to use dockerfile with `apt-get install` like instructions as a source of WS machine.
Note that in case sudo is used in build/inside container user has to use sudo -E to pass proxy variables into root's environment or set these variables himself.
Related to eclipse/che#3948
Add possibility to access external resources in docker image build phase of workspace start if Che is deployed in environment behind the proxy.
=> CHE-3948: fix build of dockerfiles behind a proxy

assembly/assembly-wsagent-war/src/main/java/com/codenvy/ext/java/server/AgentSwaggerConfig.java, assembly/assembly-wsagent-war/src/main/java/com/codenvy/ext/java/server/SwaggerServletModule.java
Sets correct base path for Swagger configuration on agent. Example:
http://172.17.0.1/37639_172.17.0.1/api/docs/swagger.json
https://github.com/codenvy/codenvy/issues/2047
Fixes the base path for Swagger configuration on the agent.
N/A
https://github.com/eclipse/che-docs/pull/219
=> CODENVY-2047; fix base path for Swagger configuration on agent

plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/backup/DockerEnvironmentBackupManager.java, plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/backup/DockerEnvironmentBackupManagerTest.java
Prevents throwing an exception if rsync returns 24 code on backup.
Fixes https://github.com/codenvy/codenvy/issues/2018
Fix false negative error of rsync backup when some files were vanished during backup was in progress.
=> CODENVY-2018: do not throw exception if rsync returns 24 code on backup

plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/RemoteDockerNode.java, plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/agent/launcher/MachineInnerRsyncAgentLauncherImpl.java, plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/backup/DockerEnvironmentBackupManager.java, plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/RemoteDockerNodeTest.java, plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/backup/DockerEnvironmentBackupManagerTest.java
Throws special exception that indicates abnormal state of docker machine if container is not in running state on backup/restore operations.
Fixes #1834 
Do not print stack traces into log when container exited before restore/backup operation.
=> CODENVY-1834: fix work of docker backup manager if container unexpectedly exited

wsagent/codenvy-wsagent-core/src/main/java/com/codenvy/wsagent/server/WsAgentServletModule.java
Preflight requests should be processed by CORS filter first, so it should be bound before the login filter.
https://github.com/codenvy/codenvy/issues/1826
Restore correct order of filters.
N/A
N/A
=> CODENVY-1826; restore filter order - CORS should be first;

dashboard/src/app/navbar/codenvy-navbar.html, dashboard/src/app/navbar/navbar.controller.ts
Show the user email as user nickname in the left bottom corner of UD NavBar in the case when user first name and user last name are empty.
https://github.com/codenvy/codenvy/issues/994
-- Show the user email in the case when user first name and user last name are empty.
N/A
=> CODENVY-994 Show the user nickname in the left bottom corner of UD

dashboard/src/assets/branding/product.json
Add docs links into branding JSON.
https://github.com/codenvy/codenvy/issues/2035
-- Add docs links into branding JSON.
=> CODENVY-2035: Add docs links into branding json

dockerfiles/codenvy/Dockerfile
Adds init process [Tini](https://github.com/krallin/tini) into codenvy container. It prevents zombie emergence after killing rsync scripts because of timed out execution.
BTW there is ability to use it from docker directly, but I didn't manage to use it because of probable [bug](https://github.com/docker/compose/issues/4797) in compose.
Related to #1905. To fix it we need to add the same changes in Saas, and customers repos.
Add init process to workspace master container to prevent zombie process appearance.
=> CODENVY-1905: add init process into master container

dashboard/src/app/admin/user-management/add-user/add-user.html, dashboard/src/app/admin/user-management/add-user/add-user.styl, dashboard/src/app/billing/ram-info/ram-info.controller.ts, dashboard/src/app/billing/ram-info/ram-info.html, dashboard/src/app/organizations/create-organizations/create-organizations.controller.ts, dashboard/src/app/organizations/list-organizations/list-organizations.controller.ts, dashboard/src/app/organizations/list-organizations/list-organizations.html, dashboard/src/app/organizations/list-organizations/organizations-item/organizations-item.html, dashboard/src/app/organizations/organization-details/organization-details.controller.ts, dashboard/src/app/organizations/organization-details/organization-details.html, dashboard/src/app/organizations/organizations-config.ts, dashboard/src/components/api/codenvy-organizations.factory.ts, wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/resource/OrganizationResourcesDistributor.java, wsmaster/codenvy-hosted-api-organization/src/main/java/com/codenvy/organization/api/resource/SuborganizationResourcesProvider.java, wsmaster/codenvy-hosted-api-organization/src/test/java/com/codenvy/organization/api/resource/OrganizationResourcesDistributorTest.java, wsmaster/codenvy-hosted-api-organization/src/test/java/com/codenvy/organization/api/resource/SuborganizationResourcesProviderTest.java, wsmaster/codenvy-hosted-api-resource-shared/src/main/java/com/codenvy/resource/model/Resource.java, wsmaster/codenvy-hosted-api-resource/src/main/java/com/codenvy/resource/api/ResourceAggregator.java, wsmaster/codenvy-hosted-api-resource/src/main/java/com/codenvy/resource/api/free/ResourceValidator.java, wsmaster/codenvy-hosted-api-resource/src/main/java/com/codenvy/resource/api/type/AbstractExhaustibleResource.java, wsmaster/codenvy-hosted-api-resource/src/test/java/com/codenvy/resource/api/ResourceAggregatorTest.java, wsmaster/codenvy-hosted-api-resource/src/test/java/com/codenvy/resource/api/free/ResourceValidatorTest.java, wsmaster/codenvy-hosted-api-resource/src/test/java/com/codenvy/resource/api/type/AbstractExhaustibleResourceTest.java, wsmaster/codenvy-hosted-personal-account/src/main/java/com/codenvy/api/account/personal/DefaultUserResourcesProvider.java
Adds ability to use -1 in the amount of resources while setting resources limits via external configurations or via free resources service.
https://github.com/codenvy/codenvy/issues/1812
Added ability to use -1 in the amount of resources.
N/A
N/A
=> CODENVY-1812 Add ability to use -1 in the amount of resources

dockerfiles/init/manifests/codenvy.pp
Enables UseStringDeduplication java flag for WS agent & uses newer G1GC collector.
https://github.com/eclipse/che/issues/4977
Enabled UseStringDeduplication java flag for WS agent.
Enabled UseStringDeduplication java flag for WS agent.
N/A
=> CHE-4977; enable UseStringDeduplication java flag for WS agent;

wsmaster/codenvy-hosted-api-admin/src/main/java/com/codenvy/api/user/server/AdminUserService.java, wsmaster/codenvy-hosted-api-admin/src/main/java/com/codenvy/api/user/server/AdminUserServicePermissionsFilter.java, wsmaster/codenvy-hosted-api-admin/src/test/java/com/codenvy/api/user/server/AdminUserServicePermissionsFilterTest.java, wsmaster/codenvy-hosted-api-admin/src/test/java/com/codenvy/api/user/server/AdminUserServiceTest.java
Provides a method for administrators that allow to search users by email/name parts. New method is case insensitive and finds users with names/emails that contains given part. 
**method path**: `api.endpoint/admin/user/find`
#2164 
Add search user method by email/username for admins
Add new API to allow system admin to search users by names and emails
=> CODENVY-2164: Add search user method by email/username for admins

assembly/assembly-ide-war/src/main/webapp/META-INF/context.xml, dockerfiles/init/modules/haproxy/templates/haproxy.cfg.erb, wsagent/codenvy-wsagent-core/src/main/java/com/codenvy/wsagent/server/SetSessionPathListener.java, wsagent/codenvy-wsagent-core/src/main/webapp/WEB-INF/web.xml
-- Do not allow  agent `JSESSIONID` cookies to be passed between agents and to master; That will be reached by setting cookie path to given WS - e.g: `path=/34011_172.17.0.1/api`
-- Do not allow  `JSESSIONID` cookies  from master `ROOT.war` to be passed on agent and master; It is renamed in `IDESESSIONID` and blocked on haproxy.
https://github.com/codenvy/infrastructure/issues/89
Do not allow  agent JSESSIONID cookies to be passed between agents and to master;
N/A
N/A
=> INFRA-89; do not allow JSESSIONID cookies to be pass between agents;

dockerfiles/init/entrypoint.sh
this improve allows to have `addon.env` file and inject values from `addon.env` to `codenvy.env` in custom CLI based on CODENVY CLI. As result user will have codenvy.env with ENV vars from addon.
This merge happens ONLY on first init where codenvy.env not yet generated, to prevent any collisions.
example of usage in saas assembly: https://github.com/codenvy/saas/pull/224
https://github.com/eclipse/che/issues/5117
Add possibility to extend codenvy.env with addon.env if it exist
=> Add possibility to extend codenvy.env with addon.env if it exist

assembly/assembly-ide-war/src/main/webapp/_app/activity.js, assembly/assembly-wsmaster-war/src/main/java/com/codenvy/api/deploy/OnPremisesIdeApiServletModule.java, dashboard/src/app/index.module.ts, dockerfiles/init/modules/haproxy/templates/haproxy.cfg.erb, site/app/site/scripts/models/account.js, site/app/site/scripts/views/form.js, wsmaster/codenvy-hosted-machine-authentication-ide/pom.xml, wsmaster/codenvy-hosted-machine-authentication-ide/src/main/java/com/codenvy/machine/authentication/ide/MachineAsyncRequestFactory.java, wsmaster/codenvy-hosted-sso-client/pom.xml, wsmaster/codenvy-hosted-sso-client/src/main/java/com/codenvy/auth/sso/client/CodenvyCsrfFilter.java, wsmaster/codenvy-hosted-sso-client/src/main/java/com/codenvy/auth/sso/client/token/CookieRequestTokenExtractor.java
Adds CSRF protection. Resolves codenvy/infrastructure#86.
Each request filtered by `LoginFilter` now also filtered by `CodenvyCsrfFilter`.
`CodenvyCsrfFilter` delegates csrf validation routine to the standard [filter](https://tomcat.apache.org/tomcat-7.0-doc/config/filter.html#CSRF_Prevention_Filter_for_REST_APIs)
when _COOKIE_ based authentication is used, which means that clients like CLI(those that use token) will continue to work without any refactoring.
Clients scenario:
- Get token
```
Request headers:
...
session-access-key=0XABCDE...
X-CSRF-Token=Fetch
...
Response headers:
...
X-CSRF-Token=0ABCD(token value)
...
```
- Use token for modification requests:
```
Request headers:
...
session-access-key=0XFFFABCDE...
X-CSRF-Token=0ABCD(token value)
...
```
- Use invalid token or no …
=> Add CSRF prevention filter and adapt clients

wsmaster/codenvy-hosted-system/src/main/java/com/codenvy/service/system/DockerBasedSystemRamInfoProvider.java
According to this error:
```
2017-05-15 22:29:47,690[ted-scheduler-9]  [ERROR] [ckerBasedSystemRamInfoProvider 105]  - System RAM values was not found in docker system info response. All system values from docker: [[Role, primary], [Strategy, spread], [Filters, health, port, containerslots, dependency, affinity, constraint, whitelist], [Nodes, 10], [ node1.codenvy.io, node1.codenvy.io:2375], [  └ ID, GOP3:RJ3L:ZAH4:PX67:5MZO:ELXA:WPFZ:HEFK:TUCB:7MVZ:SMKF:ROOY], [  └ Status, Healthy], [  └ Containers, 2 (2 Running, 0 Paused, 0 Stopped)], [  └ Reserved CPUs, 0 / 4], [  └ Reserved Memory, 4 GiB / 31.03 GiB], [  └ Labels, kernelversion=3.10.0-327.36.3.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper], [  └ UpdatedAt, 2017-05-15T22:29:47Z], [  └ ServerVersion, …
```
=> INFRASTRUCTURE-17: Reduce sensitivity of docker system RAM values parser

plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/agent/CodenvyInContainerInfrastructureProvisioner.java, plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/agent/CodenvyInContainerInfrastructureProvisionerTest.java
Prevents adding `/tmp` folder from a workspace container into a snapshot.
Adds ability to exclude other folders from snapshots.
https://github.com/codenvy/codenvy/issues/2199
Ignore /tmp folder when creating workspace snapshot.
Snapshots No Longer Capture `tmp`
We have implemented a small but important change in how we handle snapshots. In order to speed up snapshotting when stopping a workspace, and snapshot restore when workspaces startup we are no longer snapshotting the `tmp` directory.
=> CODENVY-2199: Do not snapshot /tmp folder

plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedMachineProviderImpl.java
Handles situation when docker failed to pull snapshot image.
https://github.com/codenvy/codenvy/issues/2228
Fallback to container recipe if snapshot image is unavailable.
N/A
N/A
=> CODENVY-2888: Fallback to start from recipe if snapshot is unavailable

plugins/plugin-hosted/codenvy-machine-hosted/pom.xml, plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/agent/CodenvyAgentModule.java
Add Git credentials agent binding
https://github.com/eclipse/che/pull/5285
https://github.com/eclipse/che/issues/5169
Add binding of Git credentials agent
N/A 
N/A
=> CHE-5169: Add Git credentials agent

assembly/assembly-main/pom.xml, assembly/assembly-wsagent-server/pom.xml, dockerfiles/agents/pom.xml
It will allow to upgrade maven assembly descriptor
Replace deprecated pom.xml entry and use the newer way
Linked to https://github.com/eclipse/che/issues/5326 (update plugin)
Replace deprecated pom.xml entry and use the newer way
N/A
N/A
Change-Id: Ieb85fc1fd45bf9d62b681edb7b3288f708ccf3c3
=> Remove the use of deprecated format of maven assembly plugin 

plugins/plugin-activity/codenvy-plugin-activity-ide/pom.xml
Fix plugin-activity IDE version (follow-up to https://github.com/codenvy/codenvy/pull/2347)
=> Fix plugin activity IDE version

selenium/codenvy-selenium-test/selenium-tests.sh
This request allows to run selenium tests from any directory (an issue https://github.com/codenvy/qa/issues/964).
Also it fixes **selenium-script.sh** not to pass _--suite=<default suite>_ to the **webdriver.sh** if there parameters _--test_ or _--suite_ have already present.
=> Run selenium tests from from any directory

dashboard/src/app/account/details/account-update-password.html, dashboard/src/app/account/details/account.html, dashboard/src/app/account/details/account.styl, dashboard/src/app/admin/user-management/user-details/user-details.html, dashboard/src/app/billing/billing.html, dashboard/src/app/login/login.html, dashboard/src/app/organizations/organization-details/organization-details.html, dashboard/src/app/organizations/organization-details/organization-details.styl, dashboard/src/app/organizations/organizations-config.service.ts, dashboard/src/app/teams/team-details/team-details.html, dashboard/src/app/workspace/share-workspace/share-workspace.html, dashboard/src/app/workspace/share-workspace/share-workspace.styl, dashboard/src/app/workspace/share-workspace/user-item/user-item.html, dashboard/src/app/workspace/share-workspace/user-item/user-item.styl, dashboard/src/components/api/codenvy-team.factory.spec.ts
Restyle main tab panels.
https://github.com/eclipse/che/issues/5257
-- Restyle main tab panels.
This version introduces a major usability improvement on the dashboard. In the latest versions of Che, we focused on providing a new flow to create workspaces. Now, we are introducing a new way of managing your workspace and configuring it. 
We splited the configuration of a workspace into new sections:
- **Overview**: Define the main workspace information
- **Projects**: Manage the projects from your workspace
- **Machines**: Define the runtime used by the workspace 
- **Agents**: Configure the tools that you want to install the workspace
- **Servers**: Access services that are running in your workspace and expose their ports
- **Env Variable**: Define the environment variable for the …
=> CHE 5258 Restyle main tab panels

wsmaster/codenvy-hosted-api-admin/pom.xml, wsmaster/codenvy-hosted-api-invite/pom.xml, wsmaster/codenvy-hosted-api-machine/pom.xml, wsmaster/codenvy-hosted-api-organization/pom.xml, wsmaster/codenvy-hosted-api-permission/pom.xml, wsmaster/codenvy-hosted-api-resource/pom.xml, wsmaster/codenvy-hosted-api-workspace/pom.xml, wsmaster/codenvy-hosted-integration-tests/codenvy-integration-cascade-jpa/pom.xml, wsmaster/codenvy-ldap/pom.xml
Require https://github.com/eclipse/che-dependencies/pull/58
Update to EclipseLink 2.7 changes
(avoid the use of eclipselink dependency as it provides also javax.persistence packages and there are signature conflicts)
https://github.com/eclipse/che/issues/5326
N/A
N/A
Change-Id: I1369eadf3faa4d4a793fe158d4804f2b08edc7a5
=> Update to EclipseLink 2.7

assembly/assembly-wsmaster-war/pom.xml
Add missing artifacts of EclipseLink for the runtime after the update to EclipseLink 2.7
Change-Id: Ib5bd2164f8405215935d0d3776bc3f5167678182
docker logs -f codenvy_codenvy_1
```
2017-09-28 05:42:52,697[main]             [INFO ] [o.a.c.core.StandardService 416]      - Starting service Catalina
2017-09-28 05:42:52,698[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.5.11
2017-09-28 05:42:52,921[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 923]        - Deploying web application archive /opt/codenvy-tomcat/webapps/api.war
2017-09-28 05:43:02,324[ost-startStop-1]  [INFO ] [o.f.c.i.d.DbSupportFactory 44]       - Database: jdbc:postgresql://codenvy-postgres:5432/dbcodenvy …
```
=> Add missing artifacts of EclipseLink for the runtime

selenium/codenvy-selenium-test/selenium-tests.sh
It prevents clearing of target directory for the special cases when selenium tests are executed with parameters **--compare-with-ci**, **----failed-tests**, **--regression-tests**.
https://github.com/eclipse/che/issues/6443
=> Fix comparing selenium tests execution results with CI

selenium/codenvy-selenium-test/src/test/resources/suites/CodenvyOnpremSuite.xml
Fixes name of selenium test **CheckMainFeatureForCharpLanguageTest**.
It is related to https://github.com/eclipse/che/pull/6542
=> Fix CheckMainFeatureForCharpLanguageTest name

wsmaster/codenvy-hosted-integration-tests/codenvy-integration-tck-jpa/pom.xml
Added missing org.eclipse.persistence.jpa dependency
CI fail with -Pintegration profile
N/a
N/a
N/a
=> Added missing org.eclipse.persistence.jpa dependency

selenium/codenvy-selenium-test/docker-compose.yml
It fixes problems with selenium tests of package **org.eclipse.che.selenium.filewatcher** which use two _chrome-node_ session at the same time, whereas old configuration described in _docker-compose_ file allowed only one session for the one _chrome-node_.
#2462
=> Increase the maximum number of sessions in chrome node

selenium/codenvy-selenium-test/src/test/resources/suites/CodenvyOnpremSuite.xml
According to the removal of the **Bitnami** stacks, we need to remove the selenium tests for them.
https://github.com/eclipse/che/pull/5888
=> Delete all selenium tests for Bitnami stacks

selenium/codenvy-selenium-test/src/main/java/com/codenvy/selenium/core/OnpremSeleniumSuiteModule.java, selenium/codenvy-selenium-test/src/main/java/com/codenvy/selenium/core/requestfactory/TestDefaultUserHttpJsonRequestFactory.java, selenium/codenvy-selenium-test/src/test/java/com/codenvy/selenium/factory/AuthenticateAndAcceptFactoryThroughGitHubOAuthTest.java
This request fixes selenium tests to don't remove default user unexpectedly - in _[tearDown()](https://github.com/codenvy/codenvy/blob/master/selenium/codenvy-selenium-test/src/test/java/com/codenvy/selenium/factory/AuthenticateAndAcceptFactoryThroughGitHubOAuthTest.java#L69)_ method of test **AuthenticateAndAcceptFactoryThroughGitHubOAuthTest**.
This PR is related to #2471.
=> Fix selenium test to don't remove default user unexpectedly

selenium/codenvy-selenium-test/src/main/java/com/codenvy/selenium/core/OnpremSeleniumSuiteModule.java, selenium/codenvy-selenium-test/src/main/java/com/codenvy/selenium/core/entrance/OnpremEntranceImpl.java, selenium/codenvy-selenium-test/src/main/java/com/codenvy/selenium/pageobject/PageObjectsInjectorImpl.java
This requests fixes an error after implementing Entrance class for Multiuser Che propose:
```
1) Unable to create binding for org.eclipse.che.selenium.core.entrance.Entrance. It was already configured on one or more child injectors or private modules
bound at org.eclipse.che.selenium.core.CheSeleniumWebDriverRelatedModule.getEntrance()
If it was in a PrivateModule, did you forget to expose the binding?
while locating org.eclipse.che.selenium.core.entrance.Entrance
```
The problem is the algorithm of implementing different webdrivers for different page objects by the class [PageObjectsInjector](https://github.com/eclipse/che/blob/5.18.0/selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/pageobject/PageObjectsInjector.java) was broken because of we instantiating Entrance …
=> Add ability to inject different webdrivers into the Entrance class

assembly/assembly-ide-war/src/test/java/com/codenvy/onpremises/DashboardRedirectionFilterTest.java, plugins/plugin-bitbucket/codenvy-plugin-bitbucket-pullrequest/pom.xml, plugins/plugin-bitbucket/codenvy-plugin-bitbucketserver-webhooks/pom.xml, plugins/plugin-github/codenvy-plugin-github-webhooks/pom.xml, plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/HostedDockerInstanceTest.java, plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/backup/DockerEnvironmentBackupManagerTest.java, plugins/plugin-hosted/codenvy-machine-hosted/src/test/java/com/codenvy/machine/backup/WorkspaceFsBackupSchedulerTest.java, plugins/plugin-microsoft/codenvy-plugin-microsoft-vsts-pullrequest/pom.xml, plugins/plugin-microsoft/codenvy-plugin-microsoft-vsts-webhooks/pom.xml, wsmaster/codenvy-hosted-api-admin/src/test/java/com/codenvy/api/user/server/AdminUserCreatorTest.java, wsmaster/codenvy-hosted-api-admin/src/test/java/com/codenvy/api/user/server/AdminUserServicePermissionsFilterTest.java, wsmaster/codenvy-hosted-api-admin/src/test/java/com/codenvy/api/user/server/AdminUserServiceTest.java, wsmaster/codenvy-hosted-api-organization/pom.xml, wsmaster/codenvy-hosted-authorization/pom.xml, wsmaster/codenvy-hosted-recoverpassword/src/test/java/com/codenvy/service/password/PasswordServiceTest.java, wsmaster/codenvy-hosted-sso-client/src/test/java/com/codenvy/auth/sso/client/LoginFilterTest.java, wsmaster/codenvy-ldap/src/test/java/com/codenvy/ldap/sync/LdapSynchronizerServiceTest.java
requires
Update mockito to v2.10
it allows to start to use Java9 as runtime
N/A
N/A
=> Update mockito to v2.10

assembly/assembly-dashboard-war/pom.xml, assembly/assembly-dashboard-war/src/main/webapp/META-INF/context.xml, assembly/assembly-dashboard-war/src/main/webapp/WEB-INF/web.xml, assembly/assembly-ide-war/pom.xml, assembly/assembly-ide-war/src/main/webapp/WEB-INF/web.xml, assembly/assembly-website-war/pom.xml, assembly/assembly-website-war/src/main/webapp/META-INF/context.xml, assembly/assembly-website-war/src/main/webapp/WEB-INF/web.xml, assembly/assembly-wsagent-war/pom.xml, assembly/assembly-wsmaster-war/pom.xml, assembly/assembly-wsmaster-war/src/main/webapp/META-INF/context.xml, assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/web.xml, wsagent/codenvy-wsagent-core/src/main/webapp/WEB-INF/web.xml
Use dynamodule generator plugin, to get list of dynamodules during WAR build, instead of scanning for them at runtime (Accordingly to respective changes in Che).
https://github.com/eclipse/che/issues/6283
workspace master and agent : avoid scan of classes at runtime in order to find DynaModules
N / A
N /A
=> Avoid scan of classes during runtime in order to find dynamodules

dockerfiles/init/manifests/codenvy.env, dockerfiles/init/manifests/codenvy.pp, dockerfiles/init/modules/codenvy/templates/machine.properties.erb
Upstream che is requiring new properties
https://github.com/eclipse/che/pull/6856
N/A
N/A
Change-Id: I71270374e1dc087b51ef8ec823c3de6681167015
=> Add new properties required in upstream che

selenium/codenvy-selenium-test/src/test/resources/suites/CodenvyOnpremOneThreadTestsSuite.xml, selenium/codenvy-selenium-test/src/test/resources/suites/CodenvyOnpremSuite.xml
Move selenium tests from package **org.eclipse.che.selenium.git**, which can affect each other, into the dedicated suite **CodenvyOnpremOneThreadTestsSuite.xml**.
https://github.com/eclipse/che/7018
=> Move git-specific selenium tests to one-thread suite.xml

selenium/codenvy-selenium-test/src/test/resources/suites/CodenvyOnpremSuite.xml
It removes code which aimed to separate selenium tests on three groups: stable/unstable/failed.
https://github.com/eclipse/che/issues/7508
=> Remove separation of selenium tests on stable/unstable/failed
